/* Constants.c generated by valac 0.34.7, the Vala compiler
 * generated from Constants.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>




#define CONSTANTS_DATADIR "/usr/share"
#define CONSTANTS_PKGDATADIR "/usr/share/indicator-kdeconnect"
#define CONSTANTS_GETTEXT_PACKAGE ""
#define CONSTANTS_RELEASE_NAME "beta"
#define CONSTANTS_VERSION "0.9.3"
#define CONSTANTS_VERSION_INFO "Indicator for KDE Connect daemon"
#define CONSTANTS_PLUGINDIR ""



