/* FirstTimeWizard.c generated by valac 0.34.7, the Vala compiler
 * generated from FirstTimeWizard.vala, do not modify */

/* Copyright 2014 KDE Connect Indicator Developers
 *
 * This software is licensed under the GNU Lesser General Public License
 * (version 2.1 or later).  See the COPYING file in this distribution.
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <glib/gi18n-lib.h>


#define KDE_CONNECT_INDICATOR_TYPE_FIRST_TIME_WIZARD (kde_connect_indicator_first_time_wizard_get_type ())
#define KDE_CONNECT_INDICATOR_FIRST_TIME_WIZARD(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), KDE_CONNECT_INDICATOR_TYPE_FIRST_TIME_WIZARD, KDEConnectIndicatorFirstTimeWizard))
#define KDE_CONNECT_INDICATOR_FIRST_TIME_WIZARD_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), KDE_CONNECT_INDICATOR_TYPE_FIRST_TIME_WIZARD, KDEConnectIndicatorFirstTimeWizardClass))
#define KDE_CONNECT_INDICATOR_IS_FIRST_TIME_WIZARD(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), KDE_CONNECT_INDICATOR_TYPE_FIRST_TIME_WIZARD))
#define KDE_CONNECT_INDICATOR_IS_FIRST_TIME_WIZARD_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), KDE_CONNECT_INDICATOR_TYPE_FIRST_TIME_WIZARD))
#define KDE_CONNECT_INDICATOR_FIRST_TIME_WIZARD_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), KDE_CONNECT_INDICATOR_TYPE_FIRST_TIME_WIZARD, KDEConnectIndicatorFirstTimeWizardClass))

typedef struct _KDEConnectIndicatorFirstTimeWizard KDEConnectIndicatorFirstTimeWizard;
typedef struct _KDEConnectIndicatorFirstTimeWizardClass KDEConnectIndicatorFirstTimeWizardClass;
typedef struct _KDEConnectIndicatorFirstTimeWizardPrivate KDEConnectIndicatorFirstTimeWizardPrivate;

#define KDE_CONNECT_INDICATOR_TYPE_KDE_CONNECT_MANAGER (kde_connect_indicator_kde_connect_manager_get_type ())
#define KDE_CONNECT_INDICATOR_KDE_CONNECT_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), KDE_CONNECT_INDICATOR_TYPE_KDE_CONNECT_MANAGER, KDEConnectIndicatorKDEConnectManager))
#define KDE_CONNECT_INDICATOR_KDE_CONNECT_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), KDE_CONNECT_INDICATOR_TYPE_KDE_CONNECT_MANAGER, KDEConnectIndicatorKDEConnectManagerClass))
#define KDE_CONNECT_INDICATOR_IS_KDE_CONNECT_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), KDE_CONNECT_INDICATOR_TYPE_KDE_CONNECT_MANAGER))
#define KDE_CONNECT_INDICATOR_IS_KDE_CONNECT_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), KDE_CONNECT_INDICATOR_TYPE_KDE_CONNECT_MANAGER))
#define KDE_CONNECT_INDICATOR_KDE_CONNECT_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), KDE_CONNECT_INDICATOR_TYPE_KDE_CONNECT_MANAGER, KDEConnectIndicatorKDEConnectManagerClass))

typedef struct _KDEConnectIndicatorKDEConnectManager KDEConnectIndicatorKDEConnectManager;
typedef struct _KDEConnectIndicatorKDEConnectManagerClass KDEConnectIndicatorKDEConnectManagerClass;

#define KDE_CONNECT_INDICATOR_TYPE_DEVICE (kde_connect_indicator_device_get_type ())
#define KDE_CONNECT_INDICATOR_DEVICE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), KDE_CONNECT_INDICATOR_TYPE_DEVICE, KDEConnectIndicatorDevice))
#define KDE_CONNECT_INDICATOR_DEVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), KDE_CONNECT_INDICATOR_TYPE_DEVICE, KDEConnectIndicatorDeviceClass))
#define KDE_CONNECT_INDICATOR_IS_DEVICE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), KDE_CONNECT_INDICATOR_TYPE_DEVICE))
#define KDE_CONNECT_INDICATOR_IS_DEVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), KDE_CONNECT_INDICATOR_TYPE_DEVICE))
#define KDE_CONNECT_INDICATOR_DEVICE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), KDE_CONNECT_INDICATOR_TYPE_DEVICE, KDEConnectIndicatorDeviceClass))

typedef struct _KDEConnectIndicatorDevice KDEConnectIndicatorDevice;
typedef struct _KDEConnectIndicatorDeviceClass KDEConnectIndicatorDeviceClass;
#define _kde_connect_indicator_kde_connect_manager_unref0(var) ((var == NULL) ? NULL : (var = (kde_connect_indicator_kde_connect_manager_unref (var), NULL)))
#define __g_slist_free__kde_connect_indicator_device_unref0_0(var) ((var == NULL) ? NULL : (var = (_g_slist_free__kde_connect_indicator_device_unref0_ (var), NULL)))
typedef struct _Block3Data Block3Data;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _kde_connect_indicator_device_unref0(var) ((var == NULL) ? NULL : (var = (kde_connect_indicator_device_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

struct _KDEConnectIndicatorFirstTimeWizard {
	GtkWindow parent_instance;
	KDEConnectIndicatorFirstTimeWizardPrivate * priv;
};

struct _KDEConnectIndicatorFirstTimeWizardClass {
	GtkWindowClass parent_class;
};

struct _KDEConnectIndicatorFirstTimeWizardPrivate {
	KDEConnectIndicatorKDEConnectManager* manager;
	GSList* list;
};

struct _Block3Data {
	int _ref_count_;
	KDEConnectIndicatorFirstTimeWizard* self;
	GtkStack* stack;
};


static gpointer kde_connect_indicator_first_time_wizard_parent_class = NULL;

GType kde_connect_indicator_first_time_wizard_get_type (void) G_GNUC_CONST;
gpointer kde_connect_indicator_kde_connect_manager_ref (gpointer instance);
void kde_connect_indicator_kde_connect_manager_unref (gpointer instance);
GParamSpec* kde_connect_indicator_param_spec_kde_connect_manager (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void kde_connect_indicator_value_set_kde_connect_manager (GValue* value, gpointer v_object);
void kde_connect_indicator_value_take_kde_connect_manager (GValue* value, gpointer v_object);
gpointer kde_connect_indicator_value_get_kde_connect_manager (const GValue* value);
GType kde_connect_indicator_kde_connect_manager_get_type (void) G_GNUC_CONST;
gpointer kde_connect_indicator_device_ref (gpointer instance);
void kde_connect_indicator_device_unref (gpointer instance);
GParamSpec* kde_connect_indicator_param_spec_device (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void kde_connect_indicator_value_set_device (GValue* value, gpointer v_object);
void kde_connect_indicator_value_take_device (GValue* value, gpointer v_object);
gpointer kde_connect_indicator_value_get_device (const GValue* value);
GType kde_connect_indicator_device_get_type (void) G_GNUC_CONST;
#define KDE_CONNECT_INDICATOR_FIRST_TIME_WIZARD_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), KDE_CONNECT_INDICATOR_TYPE_FIRST_TIME_WIZARD, KDEConnectIndicatorFirstTimeWizardPrivate))
enum  {
	KDE_CONNECT_INDICATOR_FIRST_TIME_WIZARD_DUMMY_PROPERTY
};
static void _kde_connect_indicator_device_unref0_ (gpointer var);
static void _g_slist_free__kde_connect_indicator_device_unref0_ (GSList* self);
KDEConnectIndicatorFirstTimeWizard* kde_connect_indicator_first_time_wizard_new (KDEConnectIndicatorKDEConnectManager* manager);
KDEConnectIndicatorFirstTimeWizard* kde_connect_indicator_first_time_wizard_construct (GType object_type, KDEConnectIndicatorKDEConnectManager* manager);
static Block3Data* block3_data_ref (Block3Data* _data3_);
static void block3_data_unref (void * _userdata_);
static GtkWidget* kde_connect_indicator_first_time_wizard_create_connect_page (KDEConnectIndicatorFirstTimeWizard* self);
static GtkWidget* kde_connect_indicator_first_time_wizard_create_pair_page (KDEConnectIndicatorFirstTimeWizard* self);
static GtkWidget* kde_connect_indicator_first_time_wizard_create_finish_page (KDEConnectIndicatorFirstTimeWizard* self);
static void __lambda26_ (Block3Data* _data3_, const gchar* id);
KDEConnectIndicatorDevice* kde_connect_indicator_device_new (const gchar* path);
KDEConnectIndicatorDevice* kde_connect_indicator_device_construct (GType object_type, const gchar* path);
static void ___lambda27_ (Block3Data* _data3_, gboolean trusted);
static void ____lambda27__kde_connect_indicator_device_trusted_changed (KDEConnectIndicatorDevice* _sender, gboolean trusted, gpointer self);
static void ___lambda26__kde_connect_indicator_kde_connect_manager_device_added (KDEConnectIndicatorKDEConnectManager* _sender, const gchar* id, gpointer self);
static GtkBox* kde_connect_indicator_first_time_wizard_create_box (KDEConnectIndicatorFirstTimeWizard* self, GtkOrientation orientation, const gchar* markup, const gchar* image_path);
#define CONSTANTS_DATADIR "/usr/share"
#define CONSTANTS_PKGDATADIR "/usr/share/indicator-kdeconnect"
static void kde_connect_indicator_first_time_wizard_finalize (GObject* obj);


static void _kde_connect_indicator_device_unref0_ (gpointer var) {
#line 9 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	(var == NULL) ? NULL : (var = (kde_connect_indicator_device_unref (var), NULL));
#line 122 "FirstTimeWizard.c"
}


static void _g_slist_free__kde_connect_indicator_device_unref0_ (GSList* self) {
#line 9 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	g_slist_foreach (self, (GFunc) _kde_connect_indicator_device_unref0_, NULL);
#line 9 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	g_slist_free (self);
#line 131 "FirstTimeWizard.c"
}


static Block3Data* block3_data_ref (Block3Data* _data3_) {
#line 11 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	g_atomic_int_inc (&_data3_->_ref_count_);
#line 11 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	return _data3_;
#line 140 "FirstTimeWizard.c"
}


static void block3_data_unref (void * _userdata_) {
	Block3Data* _data3_;
	_data3_ = (Block3Data*) _userdata_;
#line 11 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	if (g_atomic_int_dec_and_test (&_data3_->_ref_count_)) {
#line 149 "FirstTimeWizard.c"
		KDEConnectIndicatorFirstTimeWizard* self;
#line 11 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
		self = _data3_->self;
#line 11 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
		_g_object_unref0 (_data3_->stack);
#line 11 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
		_g_object_unref0 (self);
#line 11 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
		g_slice_free (Block3Data, _data3_);
#line 159 "FirstTimeWizard.c"
	}
}


static gpointer _kde_connect_indicator_kde_connect_manager_ref0 (gpointer self) {
#line 15 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	return self ? kde_connect_indicator_kde_connect_manager_ref (self) : NULL;
#line 167 "FirstTimeWizard.c"
}


static void ___lambda27_ (Block3Data* _data3_, gboolean trusted) {
	KDEConnectIndicatorFirstTimeWizard* self;
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
#line 38 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	self = _data3_->self;
#line 39 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp1_ = trusted;
#line 39 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	if (_tmp1_) {
#line 181 "FirstTimeWizard.c"
		const gchar* _tmp2_ = NULL;
		const gchar* _tmp3_ = NULL;
#line 39 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
		_tmp2_ = gtk_stack_get_visible_child_name (_data3_->stack);
#line 39 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
		_tmp3_ = _tmp2_;
#line 39 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
		_tmp0_ = g_strcmp0 (_tmp3_, "pair") == 0;
#line 190 "FirstTimeWizard.c"
	} else {
#line 39 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
		_tmp0_ = FALSE;
#line 194 "FirstTimeWizard.c"
	}
#line 39 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	if (_tmp0_) {
#line 40 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
		gtk_stack_set_visible_child_name (_data3_->stack, "finish");
#line 200 "FirstTimeWizard.c"
	}
}


static void ____lambda27__kde_connect_indicator_device_trusted_changed (KDEConnectIndicatorDevice* _sender, gboolean trusted, gpointer self) {
#line 38 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	___lambda27_ (self, trusted);
#line 208 "FirstTimeWizard.c"
}


static gpointer _kde_connect_indicator_device_ref0 (gpointer self) {
#line 42 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	return self ? kde_connect_indicator_device_ref (self) : NULL;
#line 215 "FirstTimeWizard.c"
}


static void __lambda26_ (Block3Data* _data3_, const gchar* id) {
	KDEConnectIndicatorFirstTimeWizard* self;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
#line 34 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	self = _data3_->self;
#line 34 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	g_return_if_fail (id != NULL);
#line 35 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp0_ = gtk_stack_get_visible_child_name (_data3_->stack);
#line 35 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp1_ = _tmp0_;
#line 35 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	if (g_strcmp0 (_tmp1_, "connect") == 0) {
#line 233 "FirstTimeWizard.c"
		KDEConnectIndicatorDevice* d = NULL;
		const gchar* _tmp2_ = NULL;
		KDEConnectIndicatorDevice* _tmp3_ = NULL;
		KDEConnectIndicatorDevice* _tmp4_ = NULL;
		KDEConnectIndicatorDevice* _tmp5_ = NULL;
		KDEConnectIndicatorDevice* _tmp6_ = NULL;
#line 36 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
		gtk_stack_set_visible_child_name (_data3_->stack, "pair");
#line 37 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
		_tmp2_ = id;
#line 37 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
		_tmp3_ = kde_connect_indicator_device_new (_tmp2_);
#line 37 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
		d = _tmp3_;
#line 38 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
		_tmp4_ = d;
#line 38 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
		g_signal_connect_data (_tmp4_, "trusted-changed", (GCallback) ____lambda27__kde_connect_indicator_device_trusted_changed, block3_data_ref (_data3_), (GClosureNotify) block3_data_unref, 0);
#line 42 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
		_tmp5_ = d;
#line 42 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
		_tmp6_ = _kde_connect_indicator_device_ref0 (_tmp5_);
#line 42 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
		self->priv->list = g_slist_append (self->priv->list, _tmp6_);
#line 35 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
		_kde_connect_indicator_device_unref0 (d);
#line 260 "FirstTimeWizard.c"
	}
}


static void ___lambda26__kde_connect_indicator_kde_connect_manager_device_added (KDEConnectIndicatorKDEConnectManager* _sender, const gchar* id, gpointer self) {
#line 34 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	__lambda26_ (self, id);
#line 268 "FirstTimeWizard.c"
}


KDEConnectIndicatorFirstTimeWizard* kde_connect_indicator_first_time_wizard_construct (GType object_type, KDEConnectIndicatorKDEConnectManager* manager) {
	KDEConnectIndicatorFirstTimeWizard * self = NULL;
	Block3Data* _data3_;
	KDEConnectIndicatorKDEConnectManager* _tmp0_ = NULL;
	KDEConnectIndicatorKDEConnectManager* _tmp1_ = NULL;
	GtkStack* _tmp2_ = NULL;
	GtkWidget* _tmp3_ = NULL;
	GtkWidget* _tmp4_ = NULL;
	GtkWidget* _tmp5_ = NULL;
	GtkWidget* _tmp6_ = NULL;
	GtkWidget* _tmp7_ = NULL;
	GtkWidget* _tmp8_ = NULL;
	KDEConnectIndicatorKDEConnectManager* _tmp9_ = NULL;
#line 11 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	g_return_val_if_fail (manager != NULL, NULL);
#line 11 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_data3_ = g_slice_new0 (Block3Data);
#line 11 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_data3_->_ref_count_ = 1;
#line 11 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	self = (KDEConnectIndicatorFirstTimeWizard*) g_object_new (object_type, NULL);
#line 11 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_data3_->self = g_object_ref (self);
#line 12 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	g_object_set ((GtkWindow*) self, "default-width", 600, NULL);
#line 13 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	g_object_set ((GtkWindow*) self, "default-height", 500, NULL);
#line 14 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	gtk_window_set_icon_name ((GtkWindow*) self, "kdeconnect");
#line 15 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp0_ = manager;
#line 15 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp1_ = _kde_connect_indicator_kde_connect_manager_ref0 (_tmp0_);
#line 15 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_kde_connect_indicator_kde_connect_manager_unref0 (self->priv->manager);
#line 15 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	self->priv->manager = _tmp1_;
#line 17 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp2_ = (GtkStack*) gtk_stack_new ();
#line 17 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	g_object_ref_sink (_tmp2_);
#line 17 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_data3_->stack = _tmp2_;
#line 18 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	g_object_set ((GtkWidget*) _data3_->stack, "margin", 20, NULL);
#line 19 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	gtk_stack_set_homogeneous (_data3_->stack, TRUE);
#line 20 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	gtk_stack_set_transition_duration (_data3_->stack, (guint) 1000);
#line 21 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	gtk_stack_set_transition_type (_data3_->stack, GTK_STACK_TRANSITION_TYPE_SLIDE_LEFT);
#line 23 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp3_ = kde_connect_indicator_first_time_wizard_create_connect_page (self);
#line 23 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp4_ = _tmp3_;
#line 23 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	gtk_stack_add_named (_data3_->stack, _tmp4_, "connect");
#line 23 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_g_object_unref0 (_tmp4_);
#line 24 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp5_ = kde_connect_indicator_first_time_wizard_create_pair_page (self);
#line 24 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp6_ = _tmp5_;
#line 24 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	gtk_stack_add_named (_data3_->stack, _tmp6_, "pair");
#line 24 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_g_object_unref0 (_tmp6_);
#line 25 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp7_ = kde_connect_indicator_first_time_wizard_create_finish_page (self);
#line 25 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp8_ = _tmp7_;
#line 25 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	gtk_stack_add_named (_data3_->stack, _tmp8_, "finish");
#line 25 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_g_object_unref0 (_tmp8_);
#line 27 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	gtk_stack_set_visible_child_name (_data3_->stack, "finish");
#line 29 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) _data3_->stack);
#line 30 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	gtk_widget_show_all ((GtkWidget*) self);
#line 32 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	__g_slist_free__kde_connect_indicator_device_unref0_0 (self->priv->list);
#line 32 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	self->priv->list = NULL;
#line 34 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp9_ = manager;
#line 34 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	g_signal_connect_data (_tmp9_, "device-added", (GCallback) ___lambda26__kde_connect_indicator_kde_connect_manager_device_added, block3_data_ref (_data3_), (GClosureNotify) block3_data_unref, 0);
#line 11 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	block3_data_unref (_data3_);
#line 11 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_data3_ = NULL;
#line 11 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	return self;
#line 367 "FirstTimeWizard.c"
}


KDEConnectIndicatorFirstTimeWizard* kde_connect_indicator_first_time_wizard_new (KDEConnectIndicatorKDEConnectManager* manager) {
#line 11 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	return kde_connect_indicator_first_time_wizard_construct (KDE_CONNECT_INDICATOR_TYPE_FIRST_TIME_WIZARD, manager);
#line 374 "FirstTimeWizard.c"
}


static GtkWidget* kde_connect_indicator_first_time_wizard_create_connect_page (KDEConnectIndicatorFirstTimeWizard* self) {
	GtkWidget* result = NULL;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	const gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	const gchar* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
	const gchar* _tmp10_ = NULL;
	gchar* _tmp11_ = NULL;
	gchar* _tmp12_ = NULL;
	gchar* _tmp13_ = NULL;
	gchar* _tmp14_ = NULL;
	const gchar* _tmp15_ = NULL;
	gchar* _tmp16_ = NULL;
	gchar* _tmp17_ = NULL;
	GtkBox* _tmp18_ = NULL;
	GtkWidget* _tmp19_ = NULL;
#line 47 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 48 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp0_ = _ ("<b>Are you ready for your first device pairing?</b>\n\n");
#line 48 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp1_ = _ ("Now connect your devices using wifi connection.\n");
#line 48 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp2_ = g_strconcat (_tmp0_, _tmp1_, NULL);
#line 48 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp3_ = _tmp2_;
#line 48 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp4_ = _ ("Tethering should work too!\n");
#line 48 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp5_ = g_strconcat (_tmp3_, _tmp4_, NULL);
#line 48 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp6_ = _tmp5_;
#line 48 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp7_ = _ ("If you have Firewall running, please open port 1714-1764 for TCP and U" \
"DP\n" \
"\n");
#line 48 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp8_ = g_strconcat (_tmp6_, _tmp7_, NULL);
#line 48 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp9_ = _tmp8_;
#line 48 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp10_ = _ ("Launch KDE Connect in your Android which you can download from ");
#line 48 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp11_ = g_strconcat (_tmp9_, _tmp10_, NULL);
#line 48 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp12_ = _tmp11_;
#line 48 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp13_ = g_strconcat (_tmp12_, "<a href=\"https://play.google.com/store/apps/details?id=org.kde.kdecon" \
"nect_tp\">", NULL);
#line 48 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp14_ = _tmp13_;
#line 48 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp15_ = _ ("Google Play</a>");
#line 48 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp16_ = g_strconcat (_tmp14_, _tmp15_, NULL);
#line 48 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp17_ = _tmp16_;
#line 48 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp18_ = kde_connect_indicator_first_time_wizard_create_box (self, GTK_ORIENTATION_HORIZONTAL, _tmp17_, CONSTANTS_DATADIR "/icons/hicolor/256x256/apps/kdeconnect.png");
#line 48 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp19_ = (GtkWidget*) _tmp18_;
#line 48 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_g_free0 (_tmp17_);
#line 48 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_g_free0 (_tmp14_);
#line 48 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_g_free0 (_tmp12_);
#line 48 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_g_free0 (_tmp9_);
#line 48 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_g_free0 (_tmp6_);
#line 48 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_g_free0 (_tmp3_);
#line 48 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	result = _tmp19_;
#line 48 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	return result;
#line 458 "FirstTimeWizard.c"
}


static GtkWidget* kde_connect_indicator_first_time_wizard_create_pair_page (KDEConnectIndicatorFirstTimeWizard* self) {
	GtkWidget* result = NULL;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	const gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	GtkBox* _tmp7_ = NULL;
	GtkWidget* _tmp8_ = NULL;
#line 62 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 63 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp0_ = _ ("Everytime there is a new device connected, a new indicator will appear" \
" in your panel.\n");
#line 63 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp1_ = _ ("There, you can pair and see its status\n\n");
#line 63 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp2_ = g_strconcat (_tmp0_, _tmp1_, NULL);
#line 63 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp3_ = _tmp2_;
#line 63 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp4_ = _ ("<b>Now try to pair your device</b>");
#line 63 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp5_ = g_strconcat (_tmp3_, _tmp4_, NULL);
#line 63 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp6_ = _tmp5_;
#line 63 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp7_ = kde_connect_indicator_first_time_wizard_create_box (self, GTK_ORIENTATION_VERTICAL, _tmp6_, CONSTANTS_PKGDATADIR "/indicator.jpg");
#line 63 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp8_ = (GtkWidget*) _tmp7_;
#line 63 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_g_free0 (_tmp6_);
#line 63 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_g_free0 (_tmp3_);
#line 63 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	result = _tmp8_;
#line 63 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	return result;
#line 501 "FirstTimeWizard.c"
}


static GtkWidget* kde_connect_indicator_first_time_wizard_create_finish_page (KDEConnectIndicatorFirstTimeWizard* self) {
	GtkWidget* result = NULL;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	const gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	const gchar* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
	GtkBox* _tmp10_ = NULL;
	GtkWidget* _tmp11_ = NULL;
#line 73 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 74 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp0_ = _ ("<b>Great! your device is all set</b>\n\n");
#line 74 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp1_ = _ ("Now you can enable or disable modules on KDE Connect settings.\n");
#line 74 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp2_ = g_strconcat (_tmp0_, _tmp1_, NULL);
#line 74 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp3_ = _tmp2_;
#line 74 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp4_ = _ ("Indicator already added to autostart.\n");
#line 74 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp5_ = g_strconcat (_tmp3_, _tmp4_, NULL);
#line 74 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp6_ = _tmp5_;
#line 74 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp7_ = _ ("Enjoy!");
#line 74 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp8_ = g_strconcat (_tmp6_, _tmp7_, NULL);
#line 74 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp9_ = _tmp8_;
#line 74 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp10_ = kde_connect_indicator_first_time_wizard_create_box (self, GTK_ORIENTATION_VERTICAL, _tmp9_, CONSTANTS_PKGDATADIR "/startup.jpg");
#line 74 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp11_ = (GtkWidget*) _tmp10_;
#line 74 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_g_free0 (_tmp9_);
#line 74 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_g_free0 (_tmp6_);
#line 74 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_g_free0 (_tmp3_);
#line 74 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	result = _tmp11_;
#line 74 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	return result;
#line 555 "FirstTimeWizard.c"
}


static GtkBox* kde_connect_indicator_first_time_wizard_create_box (KDEConnectIndicatorFirstTimeWizard* self, GtkOrientation orientation, const gchar* markup, const gchar* image_path) {
	GtkBox* result = NULL;
	GtkBox* box = NULL;
	GtkOrientation _tmp0_ = 0;
	GtkBox* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	GtkImage* _tmp3_ = NULL;
	GtkImage* _tmp4_ = NULL;
	GtkLabel* l = NULL;
	GtkLabel* _tmp5_ = NULL;
	const gchar* _tmp6_ = NULL;
#line 85 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 85 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	g_return_val_if_fail (markup != NULL, NULL);
#line 85 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	g_return_val_if_fail (image_path != NULL, NULL);
#line 86 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp0_ = orientation;
#line 86 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp1_ = (GtkBox*) gtk_box_new (_tmp0_, 10);
#line 86 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	g_object_ref_sink (_tmp1_);
#line 86 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	box = _tmp1_;
#line 88 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp2_ = image_path;
#line 88 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp3_ = (GtkImage*) gtk_image_new_from_file (_tmp2_);
#line 88 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	g_object_ref_sink (_tmp3_);
#line 88 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp4_ = _tmp3_;
#line 88 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	gtk_box_pack_start (box, (GtkWidget*) _tmp4_, TRUE, TRUE, (guint) 0);
#line 88 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_g_object_unref0 (_tmp4_);
#line 90 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp5_ = (GtkLabel*) gtk_label_new (NULL);
#line 90 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	g_object_ref_sink (_tmp5_);
#line 90 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	l = _tmp5_;
#line 91 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_tmp6_ = markup;
#line 91 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	gtk_label_set_markup (l, _tmp6_);
#line 92 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	g_object_set (l, "wrap", TRUE, NULL);
#line 93 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	gtk_label_set_justify (l, GTK_JUSTIFY_LEFT);
#line 94 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	gtk_box_pack_start (box, (GtkWidget*) l, TRUE, TRUE, (guint) 0);
#line 96 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	result = box;
#line 96 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_g_object_unref0 (l);
#line 96 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	return result;
#line 618 "FirstTimeWizard.c"
}


static void kde_connect_indicator_first_time_wizard_class_init (KDEConnectIndicatorFirstTimeWizardClass * klass) {
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	kde_connect_indicator_first_time_wizard_parent_class = g_type_class_peek_parent (klass);
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	g_type_class_add_private (klass, sizeof (KDEConnectIndicatorFirstTimeWizardPrivate));
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	G_OBJECT_CLASS (klass)->finalize = kde_connect_indicator_first_time_wizard_finalize;
#line 629 "FirstTimeWizard.c"
}


static void kde_connect_indicator_first_time_wizard_instance_init (KDEConnectIndicatorFirstTimeWizard * self) {
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	self->priv = KDE_CONNECT_INDICATOR_FIRST_TIME_WIZARD_GET_PRIVATE (self);
#line 636 "FirstTimeWizard.c"
}


static void kde_connect_indicator_first_time_wizard_finalize (GObject* obj) {
	KDEConnectIndicatorFirstTimeWizard * self;
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, KDE_CONNECT_INDICATOR_TYPE_FIRST_TIME_WIZARD, KDEConnectIndicatorFirstTimeWizard);
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	_kde_connect_indicator_kde_connect_manager_unref0 (self->priv->manager);
#line 9 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	__g_slist_free__kde_connect_indicator_device_unref0_0 (self->priv->list);
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/FirstTimeWizard.vala"
	G_OBJECT_CLASS (kde_connect_indicator_first_time_wizard_parent_class)->finalize (obj);
#line 650 "FirstTimeWizard.c"
}


GType kde_connect_indicator_first_time_wizard_get_type (void) {
	static volatile gsize kde_connect_indicator_first_time_wizard_type_id__volatile = 0;
	if (g_once_init_enter (&kde_connect_indicator_first_time_wizard_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (KDEConnectIndicatorFirstTimeWizardClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) kde_connect_indicator_first_time_wizard_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (KDEConnectIndicatorFirstTimeWizard), 0, (GInstanceInitFunc) kde_connect_indicator_first_time_wizard_instance_init, NULL };
		GType kde_connect_indicator_first_time_wizard_type_id;
		kde_connect_indicator_first_time_wizard_type_id = g_type_register_static (gtk_window_get_type (), "KDEConnectIndicatorFirstTimeWizard", &g_define_type_info, 0);
		g_once_init_leave (&kde_connect_indicator_first_time_wizard_type_id__volatile, kde_connect_indicator_first_time_wizard_type_id);
	}
	return kde_connect_indicator_first_time_wizard_type_id__volatile;
}



