/* main.c generated by valac 0.34.7, the Vala compiler
 * generated from main.vala, do not modify */

/* Copyright 2014 KDE Connect Indicator Developers
 *
 * This software is licensed under the GNU Lesser General Public License
 * (version 2.1 or later).  See the COPYING file in this distribution.
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>
#include <locale.h>
#include <glib/gi18n-lib.h>


#define KDE_CONNECT_INDICATOR_TYPE_APPLICATION (kde_connect_indicator_application_get_type ())
#define KDE_CONNECT_INDICATOR_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), KDE_CONNECT_INDICATOR_TYPE_APPLICATION, KDEConnectIndicatorApplication))
#define KDE_CONNECT_INDICATOR_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), KDE_CONNECT_INDICATOR_TYPE_APPLICATION, KDEConnectIndicatorApplicationClass))
#define KDE_CONNECT_INDICATOR_IS_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), KDE_CONNECT_INDICATOR_TYPE_APPLICATION))
#define KDE_CONNECT_INDICATOR_IS_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), KDE_CONNECT_INDICATOR_TYPE_APPLICATION))
#define KDE_CONNECT_INDICATOR_APPLICATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), KDE_CONNECT_INDICATOR_TYPE_APPLICATION, KDEConnectIndicatorApplicationClass))

typedef struct _KDEConnectIndicatorApplication KDEConnectIndicatorApplication;
typedef struct _KDEConnectIndicatorApplicationClass KDEConnectIndicatorApplicationClass;
typedef struct _KDEConnectIndicatorApplicationPrivate KDEConnectIndicatorApplicationPrivate;

#define KDE_CONNECT_INDICATOR_TYPE_KDE_CONNECT_MANAGER (kde_connect_indicator_kde_connect_manager_get_type ())
#define KDE_CONNECT_INDICATOR_KDE_CONNECT_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), KDE_CONNECT_INDICATOR_TYPE_KDE_CONNECT_MANAGER, KDEConnectIndicatorKDEConnectManager))
#define KDE_CONNECT_INDICATOR_KDE_CONNECT_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), KDE_CONNECT_INDICATOR_TYPE_KDE_CONNECT_MANAGER, KDEConnectIndicatorKDEConnectManagerClass))
#define KDE_CONNECT_INDICATOR_IS_KDE_CONNECT_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), KDE_CONNECT_INDICATOR_TYPE_KDE_CONNECT_MANAGER))
#define KDE_CONNECT_INDICATOR_IS_KDE_CONNECT_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), KDE_CONNECT_INDICATOR_TYPE_KDE_CONNECT_MANAGER))
#define KDE_CONNECT_INDICATOR_KDE_CONNECT_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), KDE_CONNECT_INDICATOR_TYPE_KDE_CONNECT_MANAGER, KDEConnectIndicatorKDEConnectManagerClass))

typedef struct _KDEConnectIndicatorKDEConnectManager KDEConnectIndicatorKDEConnectManager;
typedef struct _KDEConnectIndicatorKDEConnectManagerClass KDEConnectIndicatorKDEConnectManagerClass;

#define KDE_CONNECT_INDICATOR_TYPE_FIRST_TIME_WIZARD (kde_connect_indicator_first_time_wizard_get_type ())
#define KDE_CONNECT_INDICATOR_FIRST_TIME_WIZARD(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), KDE_CONNECT_INDICATOR_TYPE_FIRST_TIME_WIZARD, KDEConnectIndicatorFirstTimeWizard))
#define KDE_CONNECT_INDICATOR_FIRST_TIME_WIZARD_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), KDE_CONNECT_INDICATOR_TYPE_FIRST_TIME_WIZARD, KDEConnectIndicatorFirstTimeWizardClass))
#define KDE_CONNECT_INDICATOR_IS_FIRST_TIME_WIZARD(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), KDE_CONNECT_INDICATOR_TYPE_FIRST_TIME_WIZARD))
#define KDE_CONNECT_INDICATOR_IS_FIRST_TIME_WIZARD_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), KDE_CONNECT_INDICATOR_TYPE_FIRST_TIME_WIZARD))
#define KDE_CONNECT_INDICATOR_FIRST_TIME_WIZARD_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), KDE_CONNECT_INDICATOR_TYPE_FIRST_TIME_WIZARD, KDEConnectIndicatorFirstTimeWizardClass))

typedef struct _KDEConnectIndicatorFirstTimeWizard KDEConnectIndicatorFirstTimeWizard;
typedef struct _KDEConnectIndicatorFirstTimeWizardClass KDEConnectIndicatorFirstTimeWizardClass;
#define _kde_connect_indicator_kde_connect_manager_unref0(var) ((var == NULL) ? NULL : (var = (kde_connect_indicator_kde_connect_manager_unref (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define KDE_CONNECT_INDICATOR_TYPE_STARTUP_MANAGER (kde_connect_indicator_startup_manager_get_type ())
#define KDE_CONNECT_INDICATOR_STARTUP_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), KDE_CONNECT_INDICATOR_TYPE_STARTUP_MANAGER, KDEConnectIndicatorStartupManager))
#define KDE_CONNECT_INDICATOR_STARTUP_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), KDE_CONNECT_INDICATOR_TYPE_STARTUP_MANAGER, KDEConnectIndicatorStartupManagerClass))
#define KDE_CONNECT_INDICATOR_IS_STARTUP_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), KDE_CONNECT_INDICATOR_TYPE_STARTUP_MANAGER))
#define KDE_CONNECT_INDICATOR_IS_STARTUP_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), KDE_CONNECT_INDICATOR_TYPE_STARTUP_MANAGER))
#define KDE_CONNECT_INDICATOR_STARTUP_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), KDE_CONNECT_INDICATOR_TYPE_STARTUP_MANAGER, KDEConnectIndicatorStartupManagerClass))

typedef struct _KDEConnectIndicatorStartupManager KDEConnectIndicatorStartupManager;
typedef struct _KDEConnectIndicatorStartupManagerClass KDEConnectIndicatorStartupManagerClass;
#define _g_main_loop_unref0(var) ((var == NULL) ? NULL : (var = (g_main_loop_unref (var), NULL)))
#define _kde_connect_indicator_startup_manager_unref0(var) ((var == NULL) ? NULL : (var = (kde_connect_indicator_startup_manager_unref (var), NULL)))

struct _KDEConnectIndicatorApplication {
	GtkApplication parent_instance;
	KDEConnectIndicatorApplicationPrivate * priv;
};

struct _KDEConnectIndicatorApplicationClass {
	GtkApplicationClass parent_class;
};

struct _KDEConnectIndicatorApplicationPrivate {
	KDEConnectIndicatorKDEConnectManager* manager;
	KDEConnectIndicatorFirstTimeWizard* ftw;
};


static gpointer kde_connect_indicator_application_parent_class = NULL;

GType kde_connect_indicator_application_get_type (void) G_GNUC_CONST;
gpointer kde_connect_indicator_kde_connect_manager_ref (gpointer instance);
void kde_connect_indicator_kde_connect_manager_unref (gpointer instance);
GParamSpec* kde_connect_indicator_param_spec_kde_connect_manager (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void kde_connect_indicator_value_set_kde_connect_manager (GValue* value, gpointer v_object);
void kde_connect_indicator_value_take_kde_connect_manager (GValue* value, gpointer v_object);
gpointer kde_connect_indicator_value_get_kde_connect_manager (const GValue* value);
GType kde_connect_indicator_kde_connect_manager_get_type (void) G_GNUC_CONST;
GType kde_connect_indicator_first_time_wizard_get_type (void) G_GNUC_CONST;
#define KDE_CONNECT_INDICATOR_APPLICATION_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), KDE_CONNECT_INDICATOR_TYPE_APPLICATION, KDEConnectIndicatorApplicationPrivate))
enum  {
	KDE_CONNECT_INDICATOR_APPLICATION_DUMMY_PROPERTY
};
KDEConnectIndicatorApplication* kde_connect_indicator_application_new (void);
KDEConnectIndicatorApplication* kde_connect_indicator_application_construct (GType object_type);
static void kde_connect_indicator_application_real_startup (GApplication* base);
KDEConnectIndicatorKDEConnectManager* kde_connect_indicator_kde_connect_manager_new (void);
KDEConnectIndicatorKDEConnectManager* kde_connect_indicator_kde_connect_manager_construct (GType object_type);
gpointer kde_connect_indicator_startup_manager_ref (gpointer instance);
void kde_connect_indicator_startup_manager_unref (gpointer instance);
GParamSpec* kde_connect_indicator_param_spec_startup_manager (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void kde_connect_indicator_value_set_startup_manager (GValue* value, gpointer v_object);
void kde_connect_indicator_value_take_startup_manager (GValue* value, gpointer v_object);
gpointer kde_connect_indicator_value_get_startup_manager (const GValue* value);
GType kde_connect_indicator_startup_manager_get_type (void) G_GNUC_CONST;
KDEConnectIndicatorStartupManager* kde_connect_indicator_startup_manager_new (void);
KDEConnectIndicatorStartupManager* kde_connect_indicator_startup_manager_construct (GType object_type);
gint kde_connect_indicator_kde_connect_manager_get_devices_number (KDEConnectIndicatorKDEConnectManager* self);
gboolean kde_connect_indicator_startup_manager_is_installed (KDEConnectIndicatorStartupManager* self);
KDEConnectIndicatorFirstTimeWizard* kde_connect_indicator_first_time_wizard_new (KDEConnectIndicatorKDEConnectManager* manager);
KDEConnectIndicatorFirstTimeWizard* kde_connect_indicator_first_time_wizard_construct (GType object_type, KDEConnectIndicatorKDEConnectManager* manager);
void kde_connect_indicator_startup_manager_install (KDEConnectIndicatorStartupManager* self);
static void kde_connect_indicator_application_real_activate (GApplication* base);
static void kde_connect_indicator_application_finalize (GObject* obj);
gint kde_connect_indicator_main (gchar** args, int args_length1);


KDEConnectIndicatorApplication* kde_connect_indicator_application_construct (GType object_type) {
	KDEConnectIndicatorApplication * self = NULL;
#line 15 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
	self = (KDEConnectIndicatorApplication*) g_object_new (object_type, "application-id", "com.bajoja.indicator-kdeconnect", "flags", G_APPLICATION_FLAGS_NONE, NULL);
#line 14 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
	return self;
#line 126 "main.c"
}


KDEConnectIndicatorApplication* kde_connect_indicator_application_new (void) {
#line 14 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
	return kde_connect_indicator_application_construct (KDE_CONNECT_INDICATOR_TYPE_APPLICATION);
#line 133 "main.c"
}


static void kde_connect_indicator_application_real_startup (GApplication* base) {
	KDEConnectIndicatorApplication * self;
	KDEConnectIndicatorKDEConnectManager* _tmp0_ = NULL;
	KDEConnectIndicatorStartupManager* startup = NULL;
	KDEConnectIndicatorStartupManager* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	gboolean _tmp3_ = FALSE;
	KDEConnectIndicatorFirstTimeWizard* _tmp4_ = NULL;
	GMainLoop* _tmp12_ = NULL;
	GMainLoop* _tmp13_ = NULL;
#line 20 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
	self = (KDEConnectIndicatorApplication*) base;
#line 21 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
	G_APPLICATION_CLASS (kde_connect_indicator_application_parent_class)->startup ((GApplication*) G_TYPE_CHECK_INSTANCE_CAST (self, gtk_application_get_type (), GtkApplication));
#line 23 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
	_tmp0_ = kde_connect_indicator_kde_connect_manager_new ();
#line 23 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
	_kde_connect_indicator_kde_connect_manager_unref0 (self->priv->manager);
#line 23 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
	self->priv->manager = _tmp0_;
#line 24 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
	_tmp1_ = kde_connect_indicator_startup_manager_new ();
#line 24 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
	startup = _tmp1_;
#line 26 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
	_tmp4_ = self->priv->ftw;
#line 26 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
	if (_tmp4_ == NULL) {
#line 165 "main.c"
		KDEConnectIndicatorKDEConnectManager* _tmp5_ = NULL;
		gint _tmp6_ = 0;
#line 26 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
		_tmp5_ = self->priv->manager;
#line 26 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
		_tmp6_ = kde_connect_indicator_kde_connect_manager_get_devices_number (_tmp5_);
#line 26 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
		_tmp3_ = _tmp6_ == 0;
#line 174 "main.c"
	} else {
#line 26 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
		_tmp3_ = FALSE;
#line 178 "main.c"
	}
#line 26 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
	if (_tmp3_) {
#line 182 "main.c"
		KDEConnectIndicatorStartupManager* _tmp7_ = NULL;
		gboolean _tmp8_ = FALSE;
#line 26 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
		_tmp7_ = startup;
#line 26 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
		_tmp8_ = kde_connect_indicator_startup_manager_is_installed (_tmp7_);
#line 26 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
		_tmp2_ = !_tmp8_;
#line 191 "main.c"
	} else {
#line 26 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
		_tmp2_ = FALSE;
#line 195 "main.c"
	}
#line 26 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
	if (_tmp2_) {
#line 199 "main.c"
		KDEConnectIndicatorKDEConnectManager* _tmp9_ = NULL;
		KDEConnectIndicatorFirstTimeWizard* _tmp10_ = NULL;
		KDEConnectIndicatorStartupManager* _tmp11_ = NULL;
#line 27 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
		_tmp9_ = self->priv->manager;
#line 27 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
		_tmp10_ = kde_connect_indicator_first_time_wizard_new (_tmp9_);
#line 27 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
		g_object_ref_sink (_tmp10_);
#line 27 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
		_g_object_unref0 (self->priv->ftw);
#line 27 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
		self->priv->ftw = _tmp10_;
#line 28 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
		_tmp11_ = startup;
#line 28 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
		kde_connect_indicator_startup_manager_install (_tmp11_);
#line 217 "main.c"
	}
#line 31 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
	_tmp12_ = g_main_loop_new (NULL, FALSE);
#line 31 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
	_tmp13_ = _tmp12_;
#line 31 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
	g_main_loop_run (_tmp13_);
#line 31 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
	_g_main_loop_unref0 (_tmp13_);
#line 20 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
	_kde_connect_indicator_startup_manager_unref0 (startup);
#line 229 "main.c"
}


static void kde_connect_indicator_application_real_activate (GApplication* base) {
	KDEConnectIndicatorApplication * self;
	KDEConnectIndicatorKDEConnectManager* _tmp0_ = NULL;
	gint _tmp1_ = 0;
#line 34 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
	self = (KDEConnectIndicatorApplication*) base;
#line 35 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
	_tmp0_ = self->priv->manager;
#line 35 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
	_tmp1_ = kde_connect_indicator_kde_connect_manager_get_devices_number (_tmp0_);
#line 35 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
	if (_tmp1_ == 0) {
#line 245 "main.c"
		KDEConnectIndicatorKDEConnectManager* _tmp2_ = NULL;
		KDEConnectIndicatorFirstTimeWizard* _tmp3_ = NULL;
#line 36 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
		_tmp2_ = self->priv->manager;
#line 36 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
		_tmp3_ = kde_connect_indicator_first_time_wizard_new (_tmp2_);
#line 36 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
		g_object_ref_sink (_tmp3_);
#line 36 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
		_g_object_unref0 (self->priv->ftw);
#line 36 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
		self->priv->ftw = _tmp3_;
#line 258 "main.c"
	} else {
#line 38 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
		g_message ("main.vala:38: user already know how to pair, dont show FirstTimeWizard");
#line 262 "main.c"
	}
}


static void kde_connect_indicator_application_class_init (KDEConnectIndicatorApplicationClass * klass) {
#line 10 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
	kde_connect_indicator_application_parent_class = g_type_class_peek_parent (klass);
#line 10 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
	g_type_class_add_private (klass, sizeof (KDEConnectIndicatorApplicationPrivate));
#line 10 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
	((GApplicationClass *) klass)->startup = (void (*)(GApplication*)) kde_connect_indicator_application_real_startup;
#line 10 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
	((GApplicationClass *) klass)->activate = (void (*)(GApplication*)) kde_connect_indicator_application_real_activate;
#line 10 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
	G_OBJECT_CLASS (klass)->finalize = kde_connect_indicator_application_finalize;
#line 278 "main.c"
}


static void kde_connect_indicator_application_instance_init (KDEConnectIndicatorApplication * self) {
#line 10 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
	self->priv = KDE_CONNECT_INDICATOR_APPLICATION_GET_PRIVATE (self);
#line 285 "main.c"
}


static void kde_connect_indicator_application_finalize (GObject* obj) {
	KDEConnectIndicatorApplication * self;
#line 10 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, KDE_CONNECT_INDICATOR_TYPE_APPLICATION, KDEConnectIndicatorApplication);
#line 11 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
	_kde_connect_indicator_kde_connect_manager_unref0 (self->priv->manager);
#line 12 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
	_g_object_unref0 (self->priv->ftw);
#line 10 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
	G_OBJECT_CLASS (kde_connect_indicator_application_parent_class)->finalize (obj);
#line 299 "main.c"
}


GType kde_connect_indicator_application_get_type (void) {
	static volatile gsize kde_connect_indicator_application_type_id__volatile = 0;
	if (g_once_init_enter (&kde_connect_indicator_application_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (KDEConnectIndicatorApplicationClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) kde_connect_indicator_application_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (KDEConnectIndicatorApplication), 0, (GInstanceInitFunc) kde_connect_indicator_application_instance_init, NULL };
		GType kde_connect_indicator_application_type_id;
		kde_connect_indicator_application_type_id = g_type_register_static (gtk_application_get_type (), "KDEConnectIndicatorApplication", &g_define_type_info, 0);
		g_once_init_leave (&kde_connect_indicator_application_type_id__volatile, kde_connect_indicator_application_type_id);
	}
	return kde_connect_indicator_application_type_id__volatile;
}


gint kde_connect_indicator_main (gchar** args, int args_length1) {
	gint result = 0;
	KDEConnectIndicatorApplication* app = NULL;
	KDEConnectIndicatorApplication* _tmp0_ = NULL;
	gchar** _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	gint _tmp2_ = 0;
#line 43 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
	setlocale (LC_ALL, "");
#line 44 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
	bindtextdomain (GETTEXT_PACKAGE, LOCALEDIR);
#line 45 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
	bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
#line 46 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
	textdomain (GETTEXT_PACKAGE);
#line 48 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
	_tmp0_ = kde_connect_indicator_application_new ();
#line 48 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
	app = _tmp0_;
#line 49 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
	_tmp1_ = args;
#line 49 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
	_tmp1__length1 = args_length1;
#line 49 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
	_tmp2_ = g_application_run ((GApplication*) app, _tmp1__length1, _tmp1_);
#line 49 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
	result = _tmp2_;
#line 49 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
	_g_object_unref0 (app);
#line 49 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
	return result;
#line 346 "main.c"
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
#line 42 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/main.vala"
	return kde_connect_indicator_main (argv, argc);
#line 356 "main.c"
}



