/* StartupManager.c generated by valac 0.34.7, the Vala compiler
 * generated from StartupManager.vala, do not modify */

/* Copyright 2014 KDE Connect Indicator Developers
 *
 * This software is licensed under the GNU Lesser General Public License
 * (version 2.1 or later).  See the COPYING file in this distribution.
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>
#include <gobject/gvaluecollector.h>


#define KDE_CONNECT_INDICATOR_TYPE_STARTUP_MANAGER (kde_connect_indicator_startup_manager_get_type ())
#define KDE_CONNECT_INDICATOR_STARTUP_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), KDE_CONNECT_INDICATOR_TYPE_STARTUP_MANAGER, KDEConnectIndicatorStartupManager))
#define KDE_CONNECT_INDICATOR_STARTUP_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), KDE_CONNECT_INDICATOR_TYPE_STARTUP_MANAGER, KDEConnectIndicatorStartupManagerClass))
#define KDE_CONNECT_INDICATOR_IS_STARTUP_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), KDE_CONNECT_INDICATOR_TYPE_STARTUP_MANAGER))
#define KDE_CONNECT_INDICATOR_IS_STARTUP_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), KDE_CONNECT_INDICATOR_TYPE_STARTUP_MANAGER))
#define KDE_CONNECT_INDICATOR_STARTUP_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), KDE_CONNECT_INDICATOR_TYPE_STARTUP_MANAGER, KDEConnectIndicatorStartupManagerClass))

typedef struct _KDEConnectIndicatorStartupManager KDEConnectIndicatorStartupManager;
typedef struct _KDEConnectIndicatorStartupManagerClass KDEConnectIndicatorStartupManagerClass;
typedef struct _KDEConnectIndicatorStartupManagerPrivate KDEConnectIndicatorStartupManagerPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
typedef struct _KDEConnectIndicatorParamSpecStartupManager KDEConnectIndicatorParamSpecStartupManager;

struct _KDEConnectIndicatorStartupManager {
	GTypeInstance parent_instance;
	volatile int ref_count;
	KDEConnectIndicatorStartupManagerPrivate * priv;
};

struct _KDEConnectIndicatorStartupManagerClass {
	GTypeClass parent_class;
	void (*finalize) (KDEConnectIndicatorStartupManager *self);
};

struct _KDEConnectIndicatorStartupManagerPrivate {
	gchar* prefix_dir;
	gchar* autostart_folder;
	GFile* startup_file;
};

struct _KDEConnectIndicatorParamSpecStartupManager {
	GParamSpec parent_instance;
};


static gpointer kde_connect_indicator_startup_manager_parent_class = NULL;

gpointer kde_connect_indicator_startup_manager_ref (gpointer instance);
void kde_connect_indicator_startup_manager_unref (gpointer instance);
GParamSpec* kde_connect_indicator_param_spec_startup_manager (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void kde_connect_indicator_value_set_startup_manager (GValue* value, gpointer v_object);
void kde_connect_indicator_value_take_startup_manager (GValue* value, gpointer v_object);
gpointer kde_connect_indicator_value_get_startup_manager (const GValue* value);
GType kde_connect_indicator_startup_manager_get_type (void) G_GNUC_CONST;
#define KDE_CONNECT_INDICATOR_STARTUP_MANAGER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), KDE_CONNECT_INDICATOR_TYPE_STARTUP_MANAGER, KDEConnectIndicatorStartupManagerPrivate))
enum  {
	KDE_CONNECT_INDICATOR_STARTUP_MANAGER_DUMMY_PROPERTY
};
#define KDE_CONNECT_INDICATOR_STARTUP_MANAGER_desktop_file "indicator-kdeconnect.desktop"
KDEConnectIndicatorStartupManager* kde_connect_indicator_startup_manager_new (void);
KDEConnectIndicatorStartupManager* kde_connect_indicator_startup_manager_construct (GType object_type);
gboolean kde_connect_indicator_startup_manager_is_installed (KDEConnectIndicatorStartupManager* self);
void kde_connect_indicator_startup_manager_install (KDEConnectIndicatorStartupManager* self);
#define CONSTANTS_DATADIR "/usr/share"
static void kde_connect_indicator_startup_manager_finalize (KDEConnectIndicatorStartupManager* obj);


KDEConnectIndicatorStartupManager* kde_connect_indicator_startup_manager_construct (GType object_type) {
	KDEConnectIndicatorStartupManager* self = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	GFile* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
#line 13 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	self = (KDEConnectIndicatorStartupManager*) g_type_create_instance (object_type);
#line 14 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	_tmp0_ = g_get_user_config_dir ();
#line 14 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	_tmp1_ = g_strconcat (_tmp0_, "/autostart/", NULL);
#line 14 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	_g_free0 (self->priv->autostart_folder);
#line 14 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	self->priv->autostart_folder = _tmp1_;
#line 15 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	_tmp2_ = self->priv->autostart_folder;
#line 15 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	_tmp3_ = g_strconcat (_tmp2_, KDE_CONNECT_INDICATOR_STARTUP_MANAGER_desktop_file, NULL);
#line 15 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	_tmp4_ = _tmp3_;
#line 15 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	_tmp5_ = g_file_new_for_path (_tmp4_);
#line 15 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	_g_object_unref0 (self->priv->startup_file);
#line 15 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	self->priv->startup_file = _tmp5_;
#line 15 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	_g_free0 (_tmp4_);
#line 16 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	_tmp6_ = g_strdup ("/usr/share");
#line 16 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	_g_free0 (self->priv->prefix_dir);
#line 16 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	self->priv->prefix_dir = _tmp6_;
#line 13 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	return self;
#line 119 "StartupManager.c"
}


KDEConnectIndicatorStartupManager* kde_connect_indicator_startup_manager_new (void) {
#line 13 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	return kde_connect_indicator_startup_manager_construct (KDE_CONNECT_INDICATOR_TYPE_STARTUP_MANAGER);
#line 126 "StartupManager.c"
}


gboolean kde_connect_indicator_startup_manager_is_installed (KDEConnectIndicatorStartupManager* self) {
	gboolean result = FALSE;
	GFile* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
#line 19 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 20 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	_tmp0_ = self->priv->startup_file;
#line 20 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	_tmp1_ = g_file_query_exists (_tmp0_, NULL);
#line 20 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	result = _tmp1_;
#line 20 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	return result;
#line 144 "StartupManager.c"
}


void kde_connect_indicator_startup_manager_install (KDEConnectIndicatorStartupManager* self) {
	GFile* desktop_file = NULL;
	GFile* _tmp0_ = NULL;
	GFile* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	GError * _inner_error_ = NULL;
#line 23 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	g_return_if_fail (self != NULL);
#line 24 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	_tmp0_ = g_file_new_for_path (CONSTANTS_DATADIR "/applications/" KDE_CONNECT_INDICATOR_STARTUP_MANAGER_desktop_file);
#line 24 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	desktop_file = _tmp0_;
#line 29 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	_tmp1_ = desktop_file;
#line 29 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	_tmp2_ = g_file_query_exists (_tmp1_, NULL);
#line 29 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	if (_tmp2_) {
#line 166 "StartupManager.c"
		{
			GFile* startup_folder = NULL;
			GFile* _tmp3_ = NULL;
			GFile* _tmp4_ = NULL;
			GFile* _tmp5_ = NULL;
			gboolean _tmp6_ = FALSE;
			gboolean _tmp8_ = FALSE;
			GFile* _tmp9_ = NULL;
			GFile* _tmp10_ = NULL;
			gboolean _tmp11_ = FALSE;
#line 31 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
			_tmp3_ = self->priv->startup_file;
#line 31 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
			_tmp4_ = g_file_get_parent (_tmp3_);
#line 31 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
			startup_folder = _tmp4_;
#line 32 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
			_tmp5_ = startup_folder;
#line 32 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
			_tmp6_ = g_file_query_exists (_tmp5_, NULL);
#line 32 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
			if (!_tmp6_) {
#line 189 "StartupManager.c"
				GFile* _tmp7_ = NULL;
#line 33 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
				_tmp7_ = startup_folder;
#line 33 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
				g_file_make_directory_with_parents (_tmp7_, NULL, &_inner_error_);
#line 33 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
				if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 33 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
					_g_object_unref0 (startup_folder);
#line 199 "StartupManager.c"
					goto __catch34_g_error;
				}
			}
#line 34 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
			_tmp9_ = desktop_file;
#line 34 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
			_tmp10_ = self->priv->startup_file;
#line 34 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
			_tmp11_ = g_file_copy (_tmp9_, _tmp10_, G_FILE_COPY_NONE, NULL, NULL, NULL, &_inner_error_);
#line 34 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
			_tmp8_ = _tmp11_;
#line 34 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
			if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 34 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
				_g_object_unref0 (startup_folder);
#line 215 "StartupManager.c"
				goto __catch34_g_error;
			}
#line 34 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
			if (_tmp8_) {
#line 220 "StartupManager.c"
				GFile* _tmp12_ = NULL;
				gchar* _tmp13_ = NULL;
				gchar* _tmp14_ = NULL;
#line 35 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
				_tmp12_ = self->priv->startup_file;
#line 35 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
				_tmp13_ = g_file_get_path (_tmp12_);
#line 35 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
				_tmp14_ = _tmp13_;
#line 35 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
				g_message ("StartupManager.vala:35: autostart file installed in %s", _tmp14_);
#line 35 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
				_g_free0 (_tmp14_);
#line 234 "StartupManager.c"
			}
#line 30 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
			_g_object_unref0 (startup_folder);
#line 238 "StartupManager.c"
		}
		goto __finally34;
		__catch34_g_error:
		{
			GError* e = NULL;
			GError* _tmp15_ = NULL;
			const gchar* _tmp16_ = NULL;
#line 30 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
			e = _inner_error_;
#line 30 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
			_inner_error_ = NULL;
#line 38 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
			_tmp15_ = e;
#line 38 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
			_tmp16_ = _tmp15_->message;
#line 38 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
			g_message ("StartupManager.vala:38: %s", _tmp16_);
#line 30 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
			_g_error_free0 (e);
#line 258 "StartupManager.c"
		}
		__finally34:
#line 30 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 30 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
			_g_object_unref0 (desktop_file);
#line 30 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 30 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
			g_clear_error (&_inner_error_);
#line 30 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
			return;
#line 271 "StartupManager.c"
		}
	} else {
		GFile* _tmp17_ = NULL;
		gchar* _tmp18_ = NULL;
		gchar* _tmp19_ = NULL;
#line 41 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
		_tmp17_ = desktop_file;
#line 41 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
		_tmp18_ = g_file_get_path (_tmp17_);
#line 41 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
		_tmp19_ = _tmp18_;
#line 41 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
		g_message ("StartupManager.vala:41: cant find .desktop file in %s", _tmp19_);
#line 41 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
		_g_free0 (_tmp19_);
#line 287 "StartupManager.c"
	}
#line 23 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	_g_object_unref0 (desktop_file);
#line 291 "StartupManager.c"
}


static void kde_connect_indicator_value_startup_manager_init (GValue* value) {
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	value->data[0].v_pointer = NULL;
#line 298 "StartupManager.c"
}


static void kde_connect_indicator_value_startup_manager_free_value (GValue* value) {
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	if (value->data[0].v_pointer) {
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
		kde_connect_indicator_startup_manager_unref (value->data[0].v_pointer);
#line 307 "StartupManager.c"
	}
}


static void kde_connect_indicator_value_startup_manager_copy_value (const GValue* src_value, GValue* dest_value) {
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	if (src_value->data[0].v_pointer) {
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
		dest_value->data[0].v_pointer = kde_connect_indicator_startup_manager_ref (src_value->data[0].v_pointer);
#line 317 "StartupManager.c"
	} else {
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
		dest_value->data[0].v_pointer = NULL;
#line 321 "StartupManager.c"
	}
}


static gpointer kde_connect_indicator_value_startup_manager_peek_pointer (const GValue* value) {
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	return value->data[0].v_pointer;
#line 329 "StartupManager.c"
}


static gchar* kde_connect_indicator_value_startup_manager_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	if (collect_values[0].v_pointer) {
#line 336 "StartupManager.c"
		KDEConnectIndicatorStartupManager* object;
		object = collect_values[0].v_pointer;
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
		if (object->parent_instance.g_class == NULL) {
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 343 "StartupManager.c"
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 347 "StartupManager.c"
		}
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
		value->data[0].v_pointer = kde_connect_indicator_startup_manager_ref (object);
#line 351 "StartupManager.c"
	} else {
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
		value->data[0].v_pointer = NULL;
#line 355 "StartupManager.c"
	}
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	return NULL;
#line 359 "StartupManager.c"
}


static gchar* kde_connect_indicator_value_startup_manager_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	KDEConnectIndicatorStartupManager** object_p;
	object_p = collect_values[0].v_pointer;
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	if (!object_p) {
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
#line 370 "StartupManager.c"
	}
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	if (!value->data[0].v_pointer) {
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
		*object_p = NULL;
#line 376 "StartupManager.c"
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
		*object_p = value->data[0].v_pointer;
#line 380 "StartupManager.c"
	} else {
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
		*object_p = kde_connect_indicator_startup_manager_ref (value->data[0].v_pointer);
#line 384 "StartupManager.c"
	}
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	return NULL;
#line 388 "StartupManager.c"
}


GParamSpec* kde_connect_indicator_param_spec_startup_manager (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	KDEConnectIndicatorParamSpecStartupManager* spec;
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	g_return_val_if_fail (g_type_is_a (object_type, KDE_CONNECT_INDICATOR_TYPE_STARTUP_MANAGER), NULL);
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	G_PARAM_SPEC (spec)->value_type = object_type;
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	return G_PARAM_SPEC (spec);
#line 402 "StartupManager.c"
}


gpointer kde_connect_indicator_value_get_startup_manager (const GValue* value) {
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, KDE_CONNECT_INDICATOR_TYPE_STARTUP_MANAGER), NULL);
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	return value->data[0].v_pointer;
#line 411 "StartupManager.c"
}


void kde_connect_indicator_value_set_startup_manager (GValue* value, gpointer v_object) {
	KDEConnectIndicatorStartupManager* old;
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, KDE_CONNECT_INDICATOR_TYPE_STARTUP_MANAGER));
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	old = value->data[0].v_pointer;
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	if (v_object) {
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, KDE_CONNECT_INDICATOR_TYPE_STARTUP_MANAGER));
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
		value->data[0].v_pointer = v_object;
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
		kde_connect_indicator_startup_manager_ref (value->data[0].v_pointer);
#line 431 "StartupManager.c"
	} else {
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
		value->data[0].v_pointer = NULL;
#line 435 "StartupManager.c"
	}
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	if (old) {
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
		kde_connect_indicator_startup_manager_unref (old);
#line 441 "StartupManager.c"
	}
}


void kde_connect_indicator_value_take_startup_manager (GValue* value, gpointer v_object) {
	KDEConnectIndicatorStartupManager* old;
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, KDE_CONNECT_INDICATOR_TYPE_STARTUP_MANAGER));
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	old = value->data[0].v_pointer;
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	if (v_object) {
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, KDE_CONNECT_INDICATOR_TYPE_STARTUP_MANAGER));
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
		value->data[0].v_pointer = v_object;
#line 460 "StartupManager.c"
	} else {
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
		value->data[0].v_pointer = NULL;
#line 464 "StartupManager.c"
	}
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	if (old) {
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
		kde_connect_indicator_startup_manager_unref (old);
#line 470 "StartupManager.c"
	}
}


static void kde_connect_indicator_startup_manager_class_init (KDEConnectIndicatorStartupManagerClass * klass) {
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	kde_connect_indicator_startup_manager_parent_class = g_type_class_peek_parent (klass);
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	((KDEConnectIndicatorStartupManagerClass *) klass)->finalize = kde_connect_indicator_startup_manager_finalize;
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	g_type_class_add_private (klass, sizeof (KDEConnectIndicatorStartupManagerPrivate));
#line 482 "StartupManager.c"
}


static void kde_connect_indicator_startup_manager_instance_init (KDEConnectIndicatorStartupManager * self) {
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	self->priv = KDE_CONNECT_INDICATOR_STARTUP_MANAGER_GET_PRIVATE (self);
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	self->ref_count = 1;
#line 491 "StartupManager.c"
}


static void kde_connect_indicator_startup_manager_finalize (KDEConnectIndicatorStartupManager* obj) {
	KDEConnectIndicatorStartupManager * self;
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, KDE_CONNECT_INDICATOR_TYPE_STARTUP_MANAGER, KDEConnectIndicatorStartupManager);
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	g_signal_handlers_destroy (self);
#line 9 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	_g_free0 (self->priv->prefix_dir);
#line 10 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	_g_free0 (self->priv->autostart_folder);
#line 11 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	_g_object_unref0 (self->priv->startup_file);
#line 507 "StartupManager.c"
}


GType kde_connect_indicator_startup_manager_get_type (void) {
	static volatile gsize kde_connect_indicator_startup_manager_type_id__volatile = 0;
	if (g_once_init_enter (&kde_connect_indicator_startup_manager_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { kde_connect_indicator_value_startup_manager_init, kde_connect_indicator_value_startup_manager_free_value, kde_connect_indicator_value_startup_manager_copy_value, kde_connect_indicator_value_startup_manager_peek_pointer, "p", kde_connect_indicator_value_startup_manager_collect_value, "p", kde_connect_indicator_value_startup_manager_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (KDEConnectIndicatorStartupManagerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) kde_connect_indicator_startup_manager_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (KDEConnectIndicatorStartupManager), 0, (GInstanceInitFunc) kde_connect_indicator_startup_manager_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType kde_connect_indicator_startup_manager_type_id;
		kde_connect_indicator_startup_manager_type_id = g_type_register_fundamental (g_type_fundamental_next (), "KDEConnectIndicatorStartupManager", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&kde_connect_indicator_startup_manager_type_id__volatile, kde_connect_indicator_startup_manager_type_id);
	}
	return kde_connect_indicator_startup_manager_type_id__volatile;
}


gpointer kde_connect_indicator_startup_manager_ref (gpointer instance) {
	KDEConnectIndicatorStartupManager* self;
	self = instance;
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	g_atomic_int_inc (&self->ref_count);
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	return instance;
#line 532 "StartupManager.c"
}


void kde_connect_indicator_startup_manager_unref (gpointer instance) {
	KDEConnectIndicatorStartupManager* self;
	self = instance;
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
		KDE_CONNECT_INDICATOR_STARTUP_MANAGER_GET_CLASS (self)->finalize (self);
#line 7 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/StartupManager.vala"
		g_type_free_instance ((GTypeInstance *) self);
#line 545 "StartupManager.c"
	}
}



