/* InOut.c generated by valac 0.34.7, the Vala compiler
 * generated from InOut.vala, do not modify */

/* Copyright 2017 KDE Connect Indicator Developers
 *
 * This software is licensed under the GNU Lesser General Public License
 * (version 2.1 or later).  See the COPYING file in this distribution.
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>
#include <gobject/gvaluecollector.h>


#define KDE_CONNECT_INDICATOR_TYPE_IN_OUT (kde_connect_indicator_in_out_get_type ())
#define KDE_CONNECT_INDICATOR_IN_OUT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), KDE_CONNECT_INDICATOR_TYPE_IN_OUT, KDEConnectIndicatorInOut))
#define KDE_CONNECT_INDICATOR_IN_OUT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), KDE_CONNECT_INDICATOR_TYPE_IN_OUT, KDEConnectIndicatorInOutClass))
#define KDE_CONNECT_INDICATOR_IS_IN_OUT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), KDE_CONNECT_INDICATOR_TYPE_IN_OUT))
#define KDE_CONNECT_INDICATOR_IS_IN_OUT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), KDE_CONNECT_INDICATOR_TYPE_IN_OUT))
#define KDE_CONNECT_INDICATOR_IN_OUT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), KDE_CONNECT_INDICATOR_TYPE_IN_OUT, KDEConnectIndicatorInOutClass))

typedef struct _KDEConnectIndicatorInOut KDEConnectIndicatorInOut;
typedef struct _KDEConnectIndicatorInOutClass KDEConnectIndicatorInOutClass;
typedef struct _KDEConnectIndicatorInOutPrivate KDEConnectIndicatorInOutPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_string_free0(var) ((var == NULL) ? NULL : (var = (g_string_free (var, TRUE), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
typedef struct _KDEConnectIndicatorParamSpecInOut KDEConnectIndicatorParamSpecInOut;

struct _KDEConnectIndicatorInOut {
	GTypeInstance parent_instance;
	volatile int ref_count;
	KDEConnectIndicatorInOutPrivate * priv;
};

struct _KDEConnectIndicatorInOutClass {
	GTypeClass parent_class;
	void (*finalize) (KDEConnectIndicatorInOut *self);
};

struct _KDEConnectIndicatorParamSpecInOut {
	GParamSpec parent_instance;
};


static gpointer kde_connect_indicator_in_out_parent_class = NULL;
extern const gchar* kde_connect_indicator_in_out_visible_devices;
const gchar* kde_connect_indicator_in_out_visible_devices = "/tmp/devices";

gpointer kde_connect_indicator_in_out_ref (gpointer instance);
void kde_connect_indicator_in_out_unref (gpointer instance);
GParamSpec* kde_connect_indicator_param_spec_in_out (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void kde_connect_indicator_value_set_in_out (GValue* value, gpointer v_object);
void kde_connect_indicator_value_take_in_out (GValue* value, gpointer v_object);
gpointer kde_connect_indicator_value_get_in_out (const GValue* value);
GType kde_connect_indicator_in_out_get_type (void) G_GNUC_CONST;
enum  {
	KDE_CONNECT_INDICATOR_IN_OUT_DUMMY_PROPERTY
};
gint kde_connect_indicator_in_out_write_status (const gchar* id, const gchar* name);
static guint8* _vala_array_dup1 (guint8* self, int length);
gint kde_connect_indicator_in_out_delete_status (const gchar* id, const gchar* name);
static guint8* _vala_array_dup2 (guint8* self, int length);
KDEConnectIndicatorInOut* kde_connect_indicator_in_out_new (void);
KDEConnectIndicatorInOut* kde_connect_indicator_in_out_construct (GType object_type);
static void kde_connect_indicator_in_out_finalize (KDEConnectIndicatorInOut* obj);


static guint8* string_get_data (const gchar* self, int* result_length1) {
	guint8* result;
	guint8* res = NULL;
	gint res_length1 = 0;
	gint _res_size_ = 0;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	guint8* _tmp3_ = NULL;
	gint _tmp3__length1 = 0;
	guint8* _tmp4_ = NULL;
	gint _tmp4__length1 = 0;
#line 1398 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1399 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	res = (guint8*) self;
#line 1399 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	res_length1 = -1;
#line 1399 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_res_size_ = res_length1;
#line 1400 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_tmp0_ = strlen (self);
#line 1400 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_tmp1_ = _tmp0_;
#line 1400 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	res_length1 = (gint) _tmp1_;
#line 1400 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_tmp2_ = res_length1;
#line 1401 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_tmp3_ = res;
#line 1401 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_tmp3__length1 = res_length1;
#line 1401 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_tmp4_ = _tmp3_;
#line 1401 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_tmp4__length1 = _tmp3__length1;
#line 1401 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	if (result_length1) {
#line 1401 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		*result_length1 = _tmp4__length1;
#line 114 "InOut.c"
	}
#line 1401 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	result = _tmp4_;
#line 1401 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	return result;
#line 120 "InOut.c"
}


static guint8* _vala_array_dup1 (guint8* self, int length) {
#line 54 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	return g_memdup (self, length * sizeof (guint8));
#line 127 "InOut.c"
}


gint kde_connect_indicator_in_out_write_status (const gchar* id, const gchar* name) {
	gint result = 0;
	GFile* file = NULL;
	const gchar* _tmp0_ = NULL;
	GFile* _tmp1_ = NULL;
	GFile* _tmp2_ = NULL;
	gboolean _tmp3_ = FALSE;
	GString* sb = NULL;
	GString* _tmp10_ = NULL;
	gchar* name_id = NULL;
	const gchar* _tmp11_ = NULL;
	gchar* _tmp12_ = NULL;
	gchar* _tmp13_ = NULL;
	gchar* _tmp14_ = NULL;
	gchar* _tmp15_ = NULL;
	const gchar* _tmp16_ = NULL;
	gchar* _tmp17_ = NULL;
	gchar* _tmp18_ = NULL;
	GError * _inner_error_ = NULL;
#line 11 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	g_return_val_if_fail (id != NULL, 0);
#line 11 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	g_return_val_if_fail (name != NULL, 0);
#line 12 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	_tmp0_ = kde_connect_indicator_in_out_visible_devices;
#line 12 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	_tmp1_ = g_file_new_for_path (_tmp0_);
#line 12 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	file = _tmp1_;
#line 14 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	_tmp2_ = file;
#line 14 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	_tmp3_ = g_file_query_exists (_tmp2_, NULL);
#line 14 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	if (!_tmp3_) {
#line 166 "InOut.c"
		GFile* _tmp4_ = NULL;
		gchar* _tmp5_ = NULL;
		gchar* _tmp6_ = NULL;
#line 15 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp4_ = file;
#line 15 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp5_ = g_file_get_path (_tmp4_);
#line 15 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp6_ = _tmp5_;
#line 15 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		g_message ("InOut.vala:15: File '%s' doesn't exist.\n", _tmp6_);
#line 15 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_g_free0 (_tmp6_);
#line 16 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		result = 1;
#line 16 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_g_object_unref0 (file);
#line 16 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		return result;
#line 186 "InOut.c"
	} else {
		GFile* _tmp7_ = NULL;
		gchar* _tmp8_ = NULL;
		gchar* _tmp9_ = NULL;
#line 19 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp7_ = file;
#line 19 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp8_ = g_file_get_path (_tmp7_);
#line 19 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp9_ = _tmp8_;
#line 19 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		g_message ("InOut.vala:19: File path exist '%s'\n", _tmp9_);
#line 19 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_g_free0 (_tmp9_);
#line 201 "InOut.c"
	}
#line 22 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	_tmp10_ = g_string_new ("");
#line 22 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	sb = _tmp10_;
#line 24 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	_tmp11_ = name;
#line 24 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	_tmp12_ = g_strconcat ("- ", _tmp11_, NULL);
#line 24 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	_tmp13_ = _tmp12_;
#line 24 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	_tmp14_ = g_strconcat (_tmp13_, " : ", NULL);
#line 24 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	_tmp15_ = _tmp14_;
#line 24 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	_tmp16_ = id;
#line 24 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	_tmp17_ = g_strconcat (_tmp15_, _tmp16_, NULL);
#line 24 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	_tmp18_ = _tmp17_;
#line 24 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	_g_free0 (_tmp15_);
#line 24 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	_g_free0 (_tmp13_);
#line 24 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	name_id = _tmp18_;
#line 229 "InOut.c"
	{
		GFileInputStream* _tmp19_ = NULL;
		GFile* _tmp20_ = NULL;
		GFileInputStream* _tmp21_ = NULL;
		GDataInputStream* dis = NULL;
		GDataInputStream* _tmp22_ = NULL;
		gchar* line = NULL;
		GString* _tmp35_ = NULL;
		const gchar* _tmp36_ = NULL;
		gchar* _tmp37_ = NULL;
		gchar* _tmp38_ = NULL;
#line 27 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp20_ = file;
#line 27 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp21_ = g_file_read (_tmp20_, NULL, &_inner_error_);
#line 27 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp19_ = _tmp21_;
#line 27 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 249 "InOut.c"
			goto __catch5_g_error;
		}
#line 27 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp22_ = g_data_input_stream_new ((GInputStream*) _tmp19_);
#line 27 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		dis = _tmp22_;
#line 32 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		while (TRUE) {
#line 258 "InOut.c"
			gchar* _tmp23_ = NULL;
			GDataInputStream* _tmp24_ = NULL;
			gchar* _tmp25_ = NULL;
			gchar* _tmp26_ = NULL;
			const gchar* _tmp27_ = NULL;
			const gchar* _tmp28_ = NULL;
			const gchar* _tmp29_ = NULL;
			const gchar* _tmp30_ = NULL;
#line 32 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			_tmp24_ = dis;
#line 32 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			_tmp25_ = g_data_input_stream_read_line (_tmp24_, NULL, NULL, &_inner_error_);
#line 32 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			_tmp23_ = _tmp25_;
#line 32 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 32 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
				_g_free0 (line);
#line 32 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
				_g_object_unref0 (dis);
#line 32 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
				_g_object_unref0 (_tmp19_);
#line 281 "InOut.c"
				goto __catch5_g_error;
			}
#line 32 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			_tmp26_ = _tmp23_;
#line 32 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			_tmp23_ = NULL;
#line 32 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			_g_free0 (line);
#line 32 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			line = _tmp26_;
#line 32 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			_tmp27_ = line;
#line 32 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			if (!(_tmp27_ != NULL)) {
#line 32 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
				_g_free0 (_tmp23_);
#line 32 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
				break;
#line 300 "InOut.c"
			}
#line 33 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			_tmp28_ = line;
#line 33 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			g_message ("InOut.vala:33: Status found on file %s\n", _tmp28_);
#line 34 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			_tmp29_ = name_id;
#line 34 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			_tmp30_ = line;
#line 34 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			if (g_strcmp0 (_tmp29_, _tmp30_) != 0) {
#line 312 "InOut.c"
				GString* _tmp31_ = NULL;
				const gchar* _tmp32_ = NULL;
				gchar* _tmp33_ = NULL;
				gchar* _tmp34_ = NULL;
#line 35 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
				_tmp31_ = sb;
#line 35 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
				_tmp32_ = line;
#line 35 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
				_tmp33_ = g_strconcat (_tmp32_, "\n", NULL);
#line 35 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
				_tmp34_ = _tmp33_;
#line 35 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
				g_string_append (_tmp31_, _tmp34_);
#line 35 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
				_g_free0 (_tmp34_);
#line 329 "InOut.c"
			} else {
#line 37 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
				result = 1;
#line 37 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
				_g_free0 (_tmp23_);
#line 37 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
				_g_free0 (line);
#line 37 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
				_g_object_unref0 (dis);
#line 37 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
				_g_object_unref0 (_tmp19_);
#line 37 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
				_g_free0 (name_id);
#line 37 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
				_g_string_free0 (sb);
#line 37 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
				_g_object_unref0 (file);
#line 37 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
				return result;
#line 349 "InOut.c"
			}
#line 32 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			_g_free0 (_tmp23_);
#line 353 "InOut.c"
		}
#line 41 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp35_ = sb;
#line 41 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp36_ = name_id;
#line 41 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp37_ = g_strconcat (_tmp36_, "\n", NULL);
#line 41 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp38_ = _tmp37_;
#line 41 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		g_string_append (_tmp35_, _tmp38_);
#line 41 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_g_free0 (_tmp38_);
#line 26 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_g_free0 (line);
#line 26 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_g_object_unref0 (dis);
#line 26 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_g_object_unref0 (_tmp19_);
#line 373 "InOut.c"
	}
	goto __finally5;
	__catch5_g_error:
	{
		GError* e = NULL;
		const gchar* _tmp39_ = NULL;
#line 26 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		e = _inner_error_;
#line 26 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_inner_error_ = NULL;
#line 44 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp39_ = e->message;
#line 44 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		g_error ("InOut.vala:44: %s", _tmp39_);
#line 26 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_g_error_free0 (e);
#line 390 "InOut.c"
	}
	__finally5:
#line 26 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 395 "InOut.c"
		gint _tmp40_ = 0;
#line 26 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_g_free0 (name_id);
#line 26 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_g_string_free0 (sb);
#line 26 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_g_object_unref0 (file);
#line 26 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 26 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		g_clear_error (&_inner_error_);
#line 26 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		return _tmp40_;
#line 409 "InOut.c"
	}
	{
		GFile* _tmp41_ = NULL;
		gboolean _tmp42_ = FALSE;
		GFileOutputStream* _tmp44_ = NULL;
		GFile* _tmp45_ = NULL;
		GFileOutputStream* _tmp46_ = NULL;
		GDataOutputStream* dos = NULL;
		GDataOutputStream* _tmp47_ = NULL;
		guint8* data = NULL;
		GString* _tmp48_ = NULL;
		const gchar* _tmp49_ = NULL;
		guint8* _tmp50_ = NULL;
		gint _tmp50__length1 = 0;
		guint8* _tmp51_ = NULL;
		gint _tmp51__length1 = 0;
		guint8* _tmp52_ = NULL;
		gint _tmp52__length1 = 0;
		gint data_length1 = 0;
		gint _data_size_ = 0;
		glong written = 0L;
#line 48 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp41_ = file;
#line 48 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp42_ = g_file_query_exists (_tmp41_, NULL);
#line 48 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		if (_tmp42_) {
#line 437 "InOut.c"
			GFile* _tmp43_ = NULL;
#line 49 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			_tmp43_ = file;
#line 49 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			g_file_delete (_tmp43_, NULL, &_inner_error_);
#line 49 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 445 "InOut.c"
				goto __catch6_g_error;
			}
		}
#line 52 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp45_ = file;
#line 52 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp46_ = g_file_create (_tmp45_, G_FILE_CREATE_REPLACE_DESTINATION, NULL, &_inner_error_);
#line 52 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp44_ = _tmp46_;
#line 52 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 457 "InOut.c"
			goto __catch6_g_error;
		}
#line 52 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp47_ = g_data_output_stream_new ((GOutputStream*) _tmp44_);
#line 52 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		dos = _tmp47_;
#line 54 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp48_ = sb;
#line 54 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp49_ = _tmp48_->str;
#line 54 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp50_ = string_get_data (_tmp49_, &_tmp50__length1);
#line 54 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp51_ = _tmp50_;
#line 54 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp51__length1 = _tmp50__length1;
#line 54 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp52_ = (_tmp51_ != NULL) ? _vala_array_dup1 (_tmp51_, _tmp51__length1) : ((gpointer) _tmp51_);
#line 54 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp52__length1 = _tmp51__length1;
#line 54 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		data = _tmp52_;
#line 54 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		data_length1 = _tmp52__length1;
#line 54 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_data_size_ = data_length1;
#line 55 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		written = (glong) 0;
#line 56 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		while (TRUE) {
#line 488 "InOut.c"
			glong _tmp53_ = 0L;
			guint8* _tmp54_ = NULL;
			gint _tmp54__length1 = 0;
			gssize _tmp55_ = 0L;
			GDataOutputStream* _tmp56_ = NULL;
			guint8* _tmp57_ = NULL;
			gint _tmp57__length1 = 0;
			glong _tmp58_ = 0L;
			guint8* _tmp59_ = NULL;
			gint _tmp59__length1 = 0;
			gssize _tmp60_ = 0L;
			glong _tmp61_ = 0L;
#line 56 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			_tmp53_ = written;
#line 56 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			_tmp54_ = data;
#line 56 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			_tmp54__length1 = data_length1;
#line 56 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			if (!(_tmp53_ < ((glong) _tmp54__length1))) {
#line 56 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
				break;
#line 511 "InOut.c"
			}
#line 57 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			_tmp56_ = dos;
#line 57 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			_tmp57_ = data;
#line 57 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			_tmp57__length1 = data_length1;
#line 57 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			_tmp58_ = written;
#line 57 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			_tmp59_ = data;
#line 57 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			_tmp59__length1 = data_length1;
#line 57 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			_tmp60_ = g_output_stream_write ((GOutputStream*) _tmp56_, _tmp57_ + ((gint) _tmp58_), (gsize) (_tmp59__length1 - ((gint) _tmp58_)), NULL, &_inner_error_);
#line 57 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			_tmp55_ = _tmp60_;
#line 57 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 57 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
				data = (g_free (data), NULL);
#line 57 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
				_g_object_unref0 (dos);
#line 57 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
				_g_object_unref0 (_tmp44_);
#line 537 "InOut.c"
				goto __catch6_g_error;
			}
#line 57 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			_tmp61_ = written;
#line 57 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			written = _tmp61_ + _tmp55_;
#line 544 "InOut.c"
		}
#line 47 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		data = (g_free (data), NULL);
#line 47 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_g_object_unref0 (dos);
#line 47 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_g_object_unref0 (_tmp44_);
#line 552 "InOut.c"
	}
	goto __finally6;
	__catch6_g_error:
	{
		GError* e = NULL;
		GError* _tmp62_ = NULL;
		const gchar* _tmp63_ = NULL;
#line 47 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		e = _inner_error_;
#line 47 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_inner_error_ = NULL;
#line 60 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp62_ = e;
#line 60 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp63_ = _tmp62_->message;
#line 60 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		g_message ("InOut.vala:60: %s\n", _tmp63_);
#line 61 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		result = 1;
#line 61 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_g_error_free0 (e);
#line 61 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_g_free0 (name_id);
#line 61 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_g_string_free0 (sb);
#line 61 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_g_object_unref0 (file);
#line 61 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		return result;
#line 582 "InOut.c"
	}
	__finally6:
#line 47 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 587 "InOut.c"
		gint _tmp64_ = 0;
#line 47 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_g_free0 (name_id);
#line 47 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_g_string_free0 (sb);
#line 47 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_g_object_unref0 (file);
#line 47 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 47 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		g_clear_error (&_inner_error_);
#line 47 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		return _tmp64_;
#line 601 "InOut.c"
	}
#line 64 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	result = 0;
#line 64 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	_g_free0 (name_id);
#line 64 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	_g_string_free0 (sb);
#line 64 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	_g_object_unref0 (file);
#line 64 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	return result;
#line 613 "InOut.c"
}


static guint8* _vala_array_dup2 (guint8* self, int length) {
#line 103 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	return g_memdup (self, length * sizeof (guint8));
#line 620 "InOut.c"
}


gint kde_connect_indicator_in_out_delete_status (const gchar* id, const gchar* name) {
	gint result = 0;
	GFile* file = NULL;
	const gchar* _tmp0_ = NULL;
	GFile* _tmp1_ = NULL;
	GFile* _tmp2_ = NULL;
	gboolean _tmp3_ = FALSE;
	GString* sb = NULL;
	GString* _tmp10_ = NULL;
	gchar* name_id = NULL;
	const gchar* _tmp11_ = NULL;
	gchar* _tmp12_ = NULL;
	gchar* _tmp13_ = NULL;
	gchar* _tmp14_ = NULL;
	gchar* _tmp15_ = NULL;
	const gchar* _tmp16_ = NULL;
	gchar* _tmp17_ = NULL;
	gchar* _tmp18_ = NULL;
	GError * _inner_error_ = NULL;
#line 67 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	g_return_val_if_fail (id != NULL, 0);
#line 67 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	g_return_val_if_fail (name != NULL, 0);
#line 68 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	_tmp0_ = kde_connect_indicator_in_out_visible_devices;
#line 68 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	_tmp1_ = g_file_new_for_path (_tmp0_);
#line 68 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	file = _tmp1_;
#line 70 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	_tmp2_ = file;
#line 70 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	_tmp3_ = g_file_query_exists (_tmp2_, NULL);
#line 70 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	if (!_tmp3_) {
#line 659 "InOut.c"
		GFile* _tmp4_ = NULL;
		gchar* _tmp5_ = NULL;
		gchar* _tmp6_ = NULL;
#line 71 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp4_ = file;
#line 71 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp5_ = g_file_get_path (_tmp4_);
#line 71 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp6_ = _tmp5_;
#line 71 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		g_message ("InOut.vala:71: File '%s' doesn't exist.\n", _tmp6_);
#line 71 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_g_free0 (_tmp6_);
#line 72 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		result = 1;
#line 72 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_g_object_unref0 (file);
#line 72 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		return result;
#line 679 "InOut.c"
	} else {
		GFile* _tmp7_ = NULL;
		gchar* _tmp8_ = NULL;
		gchar* _tmp9_ = NULL;
#line 75 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp7_ = file;
#line 75 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp8_ = g_file_get_path (_tmp7_);
#line 75 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp9_ = _tmp8_;
#line 75 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		g_message ("InOut.vala:75: File path exist '%s'\n", _tmp9_);
#line 75 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_g_free0 (_tmp9_);
#line 694 "InOut.c"
	}
#line 78 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	_tmp10_ = g_string_new ("");
#line 78 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	sb = _tmp10_;
#line 80 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	_tmp11_ = name;
#line 80 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	_tmp12_ = g_strconcat ("- ", _tmp11_, NULL);
#line 80 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	_tmp13_ = _tmp12_;
#line 80 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	_tmp14_ = g_strconcat (_tmp13_, " : ", NULL);
#line 80 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	_tmp15_ = _tmp14_;
#line 80 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	_tmp16_ = id;
#line 80 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	_tmp17_ = g_strconcat (_tmp15_, _tmp16_, NULL);
#line 80 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	_tmp18_ = _tmp17_;
#line 80 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	_g_free0 (_tmp15_);
#line 80 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	_g_free0 (_tmp13_);
#line 80 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	name_id = _tmp18_;
#line 722 "InOut.c"
	{
		GFileInputStream* _tmp19_ = NULL;
		GFile* _tmp20_ = NULL;
		GFileInputStream* _tmp21_ = NULL;
		GDataInputStream* dis = NULL;
		GDataInputStream* _tmp22_ = NULL;
		gchar* line = NULL;
#line 83 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp20_ = file;
#line 83 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp21_ = g_file_read (_tmp20_, NULL, &_inner_error_);
#line 83 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp19_ = _tmp21_;
#line 83 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 738 "InOut.c"
			goto __catch7_g_error;
		}
#line 83 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp22_ = g_data_input_stream_new ((GInputStream*) _tmp19_);
#line 83 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		dis = _tmp22_;
#line 87 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		while (TRUE) {
#line 747 "InOut.c"
			gchar* _tmp23_ = NULL;
			GDataInputStream* _tmp24_ = NULL;
			gchar* _tmp25_ = NULL;
			gchar* _tmp26_ = NULL;
			const gchar* _tmp27_ = NULL;
			const gchar* _tmp28_ = NULL;
			const gchar* _tmp29_ = NULL;
			const gchar* _tmp30_ = NULL;
#line 87 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			_tmp24_ = dis;
#line 87 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			_tmp25_ = g_data_input_stream_read_line (_tmp24_, NULL, NULL, &_inner_error_);
#line 87 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			_tmp23_ = _tmp25_;
#line 87 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 87 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
				_g_free0 (line);
#line 87 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
				_g_object_unref0 (dis);
#line 87 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
				_g_object_unref0 (_tmp19_);
#line 770 "InOut.c"
				goto __catch7_g_error;
			}
#line 87 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			_tmp26_ = _tmp23_;
#line 87 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			_tmp23_ = NULL;
#line 87 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			_g_free0 (line);
#line 87 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			line = _tmp26_;
#line 87 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			_tmp27_ = line;
#line 87 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			if (!(_tmp27_ != NULL)) {
#line 87 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
				_g_free0 (_tmp23_);
#line 87 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
				break;
#line 789 "InOut.c"
			}
#line 88 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			_tmp28_ = line;
#line 88 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			g_message ("InOut.vala:88: Delete status found on file %s\n", _tmp28_);
#line 89 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			_tmp29_ = line;
#line 89 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			_tmp30_ = name_id;
#line 89 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			if (g_strcmp0 (_tmp29_, _tmp30_) != 0) {
#line 801 "InOut.c"
				GString* _tmp31_ = NULL;
				const gchar* _tmp32_ = NULL;
				gchar* _tmp33_ = NULL;
				gchar* _tmp34_ = NULL;
#line 90 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
				_tmp31_ = sb;
#line 90 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
				_tmp32_ = line;
#line 90 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
				_tmp33_ = g_strconcat (_tmp32_, "\n", NULL);
#line 90 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
				_tmp34_ = _tmp33_;
#line 90 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
				g_string_append (_tmp31_, _tmp34_);
#line 90 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
				_g_free0 (_tmp34_);
#line 818 "InOut.c"
			}
#line 87 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			_g_free0 (_tmp23_);
#line 822 "InOut.c"
		}
#line 82 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_g_free0 (line);
#line 82 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_g_object_unref0 (dis);
#line 82 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_g_object_unref0 (_tmp19_);
#line 830 "InOut.c"
	}
	goto __finally7;
	__catch7_g_error:
	{
		GError* e = NULL;
		const gchar* _tmp35_ = NULL;
#line 82 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		e = _inner_error_;
#line 82 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_inner_error_ = NULL;
#line 94 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp35_ = e->message;
#line 94 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		g_error ("InOut.vala:94: %s", _tmp35_);
#line 82 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_g_error_free0 (e);
#line 847 "InOut.c"
	}
	__finally7:
#line 82 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 852 "InOut.c"
		gint _tmp36_ = 0;
#line 82 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_g_free0 (name_id);
#line 82 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_g_string_free0 (sb);
#line 82 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_g_object_unref0 (file);
#line 82 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 82 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		g_clear_error (&_inner_error_);
#line 82 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		return _tmp36_;
#line 866 "InOut.c"
	}
	{
		GFile* _tmp37_ = NULL;
		gboolean _tmp38_ = FALSE;
		GFileOutputStream* _tmp40_ = NULL;
		GFile* _tmp41_ = NULL;
		GFileOutputStream* _tmp42_ = NULL;
		GDataOutputStream* dos = NULL;
		GDataOutputStream* _tmp43_ = NULL;
		guint8* data = NULL;
		GString* _tmp44_ = NULL;
		const gchar* _tmp45_ = NULL;
		guint8* _tmp46_ = NULL;
		gint _tmp46__length1 = 0;
		guint8* _tmp47_ = NULL;
		gint _tmp47__length1 = 0;
		guint8* _tmp48_ = NULL;
		gint _tmp48__length1 = 0;
		gint data_length1 = 0;
		gint _data_size_ = 0;
		glong written = 0L;
#line 98 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp37_ = file;
#line 98 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp38_ = g_file_query_exists (_tmp37_, NULL);
#line 98 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		if (_tmp38_) {
#line 894 "InOut.c"
			GFile* _tmp39_ = NULL;
#line 99 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			_tmp39_ = file;
#line 99 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			g_file_delete (_tmp39_, NULL, &_inner_error_);
#line 99 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 902 "InOut.c"
				goto __catch8_g_error;
			}
		}
#line 101 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp41_ = file;
#line 101 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp42_ = g_file_create (_tmp41_, G_FILE_CREATE_REPLACE_DESTINATION, NULL, &_inner_error_);
#line 101 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp40_ = _tmp42_;
#line 101 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 914 "InOut.c"
			goto __catch8_g_error;
		}
#line 101 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp43_ = g_data_output_stream_new ((GOutputStream*) _tmp40_);
#line 101 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		dos = _tmp43_;
#line 103 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp44_ = sb;
#line 103 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp45_ = _tmp44_->str;
#line 103 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp46_ = string_get_data (_tmp45_, &_tmp46__length1);
#line 103 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp47_ = _tmp46_;
#line 103 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp47__length1 = _tmp46__length1;
#line 103 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp48_ = (_tmp47_ != NULL) ? _vala_array_dup2 (_tmp47_, _tmp47__length1) : ((gpointer) _tmp47_);
#line 103 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp48__length1 = _tmp47__length1;
#line 103 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		data = _tmp48_;
#line 103 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		data_length1 = _tmp48__length1;
#line 103 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_data_size_ = data_length1;
#line 104 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		written = (glong) 0;
#line 105 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		while (TRUE) {
#line 945 "InOut.c"
			glong _tmp49_ = 0L;
			guint8* _tmp50_ = NULL;
			gint _tmp50__length1 = 0;
			gssize _tmp51_ = 0L;
			GDataOutputStream* _tmp52_ = NULL;
			guint8* _tmp53_ = NULL;
			gint _tmp53__length1 = 0;
			glong _tmp54_ = 0L;
			guint8* _tmp55_ = NULL;
			gint _tmp55__length1 = 0;
			gssize _tmp56_ = 0L;
			glong _tmp57_ = 0L;
#line 105 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			_tmp49_ = written;
#line 105 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			_tmp50_ = data;
#line 105 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			_tmp50__length1 = data_length1;
#line 105 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			if (!(_tmp49_ < ((glong) _tmp50__length1))) {
#line 105 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
				break;
#line 968 "InOut.c"
			}
#line 106 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			_tmp52_ = dos;
#line 106 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			_tmp53_ = data;
#line 106 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			_tmp53__length1 = data_length1;
#line 106 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			_tmp54_ = written;
#line 106 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			_tmp55_ = data;
#line 106 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			_tmp55__length1 = data_length1;
#line 106 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			_tmp56_ = g_output_stream_write ((GOutputStream*) _tmp52_, _tmp53_ + ((gint) _tmp54_), (gsize) (_tmp55__length1 - ((gint) _tmp54_)), NULL, &_inner_error_);
#line 106 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			_tmp51_ = _tmp56_;
#line 106 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 106 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
				data = (g_free (data), NULL);
#line 106 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
				_g_object_unref0 (dos);
#line 106 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
				_g_object_unref0 (_tmp40_);
#line 994 "InOut.c"
				goto __catch8_g_error;
			}
#line 106 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			_tmp57_ = written;
#line 106 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			written = _tmp57_ + _tmp51_;
#line 1001 "InOut.c"
		}
#line 97 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		data = (g_free (data), NULL);
#line 97 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_g_object_unref0 (dos);
#line 97 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_g_object_unref0 (_tmp40_);
#line 1009 "InOut.c"
	}
	goto __finally8;
	__catch8_g_error:
	{
		GError* e = NULL;
		GError* _tmp58_ = NULL;
		const gchar* _tmp59_ = NULL;
#line 97 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		e = _inner_error_;
#line 97 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_inner_error_ = NULL;
#line 109 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp58_ = e;
#line 109 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_tmp59_ = _tmp58_->message;
#line 109 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		g_message ("InOut.vala:109: %s\n", _tmp59_);
#line 97 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_g_error_free0 (e);
#line 1029 "InOut.c"
	}
	__finally8:
#line 97 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 1034 "InOut.c"
		gint _tmp60_ = 0;
#line 97 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_g_free0 (name_id);
#line 97 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_g_string_free0 (sb);
#line 97 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		_g_object_unref0 (file);
#line 97 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 97 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		g_clear_error (&_inner_error_);
#line 97 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		return _tmp60_;
#line 1048 "InOut.c"
	}
#line 112 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	result = 0;
#line 112 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	_g_free0 (name_id);
#line 112 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	_g_string_free0 (sb);
#line 112 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	_g_object_unref0 (file);
#line 112 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	return result;
#line 1060 "InOut.c"
}


KDEConnectIndicatorInOut* kde_connect_indicator_in_out_construct (GType object_type) {
	KDEConnectIndicatorInOut* self = NULL;
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	self = (KDEConnectIndicatorInOut*) g_type_create_instance (object_type);
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	return self;
#line 1070 "InOut.c"
}


KDEConnectIndicatorInOut* kde_connect_indicator_in_out_new (void) {
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	return kde_connect_indicator_in_out_construct (KDE_CONNECT_INDICATOR_TYPE_IN_OUT);
#line 1077 "InOut.c"
}


static void kde_connect_indicator_value_in_out_init (GValue* value) {
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	value->data[0].v_pointer = NULL;
#line 1084 "InOut.c"
}


static void kde_connect_indicator_value_in_out_free_value (GValue* value) {
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	if (value->data[0].v_pointer) {
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		kde_connect_indicator_in_out_unref (value->data[0].v_pointer);
#line 1093 "InOut.c"
	}
}


static void kde_connect_indicator_value_in_out_copy_value (const GValue* src_value, GValue* dest_value) {
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	if (src_value->data[0].v_pointer) {
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		dest_value->data[0].v_pointer = kde_connect_indicator_in_out_ref (src_value->data[0].v_pointer);
#line 1103 "InOut.c"
	} else {
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		dest_value->data[0].v_pointer = NULL;
#line 1107 "InOut.c"
	}
}


static gpointer kde_connect_indicator_value_in_out_peek_pointer (const GValue* value) {
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	return value->data[0].v_pointer;
#line 1115 "InOut.c"
}


static gchar* kde_connect_indicator_value_in_out_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	if (collect_values[0].v_pointer) {
#line 1122 "InOut.c"
		KDEConnectIndicatorInOut* object;
		object = collect_values[0].v_pointer;
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		if (object->parent_instance.g_class == NULL) {
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 1129 "InOut.c"
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 1133 "InOut.c"
		}
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		value->data[0].v_pointer = kde_connect_indicator_in_out_ref (object);
#line 1137 "InOut.c"
	} else {
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		value->data[0].v_pointer = NULL;
#line 1141 "InOut.c"
	}
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	return NULL;
#line 1145 "InOut.c"
}


static gchar* kde_connect_indicator_value_in_out_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	KDEConnectIndicatorInOut** object_p;
	object_p = collect_values[0].v_pointer;
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	if (!object_p) {
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
#line 1156 "InOut.c"
	}
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	if (!value->data[0].v_pointer) {
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		*object_p = NULL;
#line 1162 "InOut.c"
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		*object_p = value->data[0].v_pointer;
#line 1166 "InOut.c"
	} else {
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		*object_p = kde_connect_indicator_in_out_ref (value->data[0].v_pointer);
#line 1170 "InOut.c"
	}
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	return NULL;
#line 1174 "InOut.c"
}


GParamSpec* kde_connect_indicator_param_spec_in_out (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	KDEConnectIndicatorParamSpecInOut* spec;
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	g_return_val_if_fail (g_type_is_a (object_type, KDE_CONNECT_INDICATOR_TYPE_IN_OUT), NULL);
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	G_PARAM_SPEC (spec)->value_type = object_type;
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	return G_PARAM_SPEC (spec);
#line 1188 "InOut.c"
}


gpointer kde_connect_indicator_value_get_in_out (const GValue* value) {
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, KDE_CONNECT_INDICATOR_TYPE_IN_OUT), NULL);
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	return value->data[0].v_pointer;
#line 1197 "InOut.c"
}


void kde_connect_indicator_value_set_in_out (GValue* value, gpointer v_object) {
	KDEConnectIndicatorInOut* old;
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, KDE_CONNECT_INDICATOR_TYPE_IN_OUT));
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	old = value->data[0].v_pointer;
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	if (v_object) {
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, KDE_CONNECT_INDICATOR_TYPE_IN_OUT));
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		value->data[0].v_pointer = v_object;
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		kde_connect_indicator_in_out_ref (value->data[0].v_pointer);
#line 1217 "InOut.c"
	} else {
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		value->data[0].v_pointer = NULL;
#line 1221 "InOut.c"
	}
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	if (old) {
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		kde_connect_indicator_in_out_unref (old);
#line 1227 "InOut.c"
	}
}


void kde_connect_indicator_value_take_in_out (GValue* value, gpointer v_object) {
	KDEConnectIndicatorInOut* old;
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, KDE_CONNECT_INDICATOR_TYPE_IN_OUT));
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	old = value->data[0].v_pointer;
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	if (v_object) {
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, KDE_CONNECT_INDICATOR_TYPE_IN_OUT));
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		value->data[0].v_pointer = v_object;
#line 1246 "InOut.c"
	} else {
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		value->data[0].v_pointer = NULL;
#line 1250 "InOut.c"
	}
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	if (old) {
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		kde_connect_indicator_in_out_unref (old);
#line 1256 "InOut.c"
	}
}


static void kde_connect_indicator_in_out_class_init (KDEConnectIndicatorInOutClass * klass) {
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	kde_connect_indicator_in_out_parent_class = g_type_class_peek_parent (klass);
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	((KDEConnectIndicatorInOutClass *) klass)->finalize = kde_connect_indicator_in_out_finalize;
#line 1266 "InOut.c"
}


static void kde_connect_indicator_in_out_instance_init (KDEConnectIndicatorInOut * self) {
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	self->ref_count = 1;
#line 1273 "InOut.c"
}


static void kde_connect_indicator_in_out_finalize (KDEConnectIndicatorInOut* obj) {
	KDEConnectIndicatorInOut * self;
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, KDE_CONNECT_INDICATOR_TYPE_IN_OUT, KDEConnectIndicatorInOut);
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	g_signal_handlers_destroy (self);
#line 1283 "InOut.c"
}


GType kde_connect_indicator_in_out_get_type (void) {
	static volatile gsize kde_connect_indicator_in_out_type_id__volatile = 0;
	if (g_once_init_enter (&kde_connect_indicator_in_out_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { kde_connect_indicator_value_in_out_init, kde_connect_indicator_value_in_out_free_value, kde_connect_indicator_value_in_out_copy_value, kde_connect_indicator_value_in_out_peek_pointer, "p", kde_connect_indicator_value_in_out_collect_value, "p", kde_connect_indicator_value_in_out_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (KDEConnectIndicatorInOutClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) kde_connect_indicator_in_out_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (KDEConnectIndicatorInOut), 0, (GInstanceInitFunc) kde_connect_indicator_in_out_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType kde_connect_indicator_in_out_type_id;
		kde_connect_indicator_in_out_type_id = g_type_register_fundamental (g_type_fundamental_next (), "KDEConnectIndicatorInOut", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&kde_connect_indicator_in_out_type_id__volatile, kde_connect_indicator_in_out_type_id);
	}
	return kde_connect_indicator_in_out_type_id__volatile;
}


gpointer kde_connect_indicator_in_out_ref (gpointer instance) {
	KDEConnectIndicatorInOut* self;
	self = instance;
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	g_atomic_int_inc (&self->ref_count);
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	return instance;
#line 1308 "InOut.c"
}


void kde_connect_indicator_in_out_unref (gpointer instance) {
	KDEConnectIndicatorInOut* self;
	self = instance;
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		KDE_CONNECT_INDICATOR_IN_OUT_GET_CLASS (self)->finalize (self);
#line 8 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/InOut.vala"
		g_type_free_instance ((GTypeInstance *) self);
#line 1321 "InOut.c"
	}
}



