/* Settings.c generated by valac 0.34.7, the Vala compiler
 * generated from Settings.vala, do not modify */

/* Copyright 2017 KDE Connect Indicator Developers
 *
 * This software is licensed under the GNU Lesser General Public License
 * (version 2.1 or later).  See the COPYING file in this distribution.
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include <glib/gi18n-lib.h>
#include <stdlib.h>
#include <string.h>


#define KDE_CONNECT_INDICATOR_TYPE_SETTINGS_DIALOG (kde_connect_indicator_settings_dialog_get_type ())
#define KDE_CONNECT_INDICATOR_SETTINGS_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), KDE_CONNECT_INDICATOR_TYPE_SETTINGS_DIALOG, KDEConnectIndicatorSettingsDialog))
#define KDE_CONNECT_INDICATOR_SETTINGS_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), KDE_CONNECT_INDICATOR_TYPE_SETTINGS_DIALOG, KDEConnectIndicatorSettingsDialogClass))
#define KDE_CONNECT_INDICATOR_IS_SETTINGS_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), KDE_CONNECT_INDICATOR_TYPE_SETTINGS_DIALOG))
#define KDE_CONNECT_INDICATOR_IS_SETTINGS_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), KDE_CONNECT_INDICATOR_TYPE_SETTINGS_DIALOG))
#define KDE_CONNECT_INDICATOR_SETTINGS_DIALOG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), KDE_CONNECT_INDICATOR_TYPE_SETTINGS_DIALOG, KDEConnectIndicatorSettingsDialogClass))

typedef struct _KDEConnectIndicatorSettingsDialog KDEConnectIndicatorSettingsDialog;
typedef struct _KDEConnectIndicatorSettingsDialogClass KDEConnectIndicatorSettingsDialogClass;
typedef struct _KDEConnectIndicatorSettingsDialogPrivate KDEConnectIndicatorSettingsDialogPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
typedef struct _Block1Data Block1Data;
typedef struct _Block2Data Block2Data;

struct _KDEConnectIndicatorSettingsDialog {
	GtkApplication parent_instance;
	KDEConnectIndicatorSettingsDialogPrivate * priv;
};

struct _KDEConnectIndicatorSettingsDialogClass {
	GtkApplicationClass parent_class;
};

struct _KDEConnectIndicatorSettingsDialogPrivate {
	GSettings* settings;
	GtkApplicationWindow* window;
	GtkHeaderBar* headerBar;
	GtkButton* cancel_button;
	GtkButton* ok_button;
	GtkStyleContext* style_context;
	GtkStack* stack;
	GtkStackSwitcher* stack_switcher;
};

struct _Block1Data {
	int _ref_count_;
	KDEConnectIndicatorSettingsDialog* self;
	GtkSwitch* switch1;
	GtkSwitch* switch2;
};

struct _Block2Data {
	int _ref_count_;
	KDEConnectIndicatorSettingsDialog* self;
	GtkButton* button1;
	GFile* contacts;
	GFile* token;
};


static gpointer kde_connect_indicator_settings_dialog_parent_class = NULL;

GType kde_connect_indicator_settings_dialog_get_type (void) G_GNUC_CONST;
#define KDE_CONNECT_INDICATOR_SETTINGS_DIALOG_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), KDE_CONNECT_INDICATOR_TYPE_SETTINGS_DIALOG, KDEConnectIndicatorSettingsDialogPrivate))
enum  {
	KDE_CONNECT_INDICATOR_SETTINGS_DIALOG_DUMMY_PROPERTY
};
KDEConnectIndicatorSettingsDialog* kde_connect_indicator_settings_dialog_new (void);
KDEConnectIndicatorSettingsDialog* kde_connect_indicator_settings_dialog_construct (GType object_type);
static void kde_connect_indicator_settings_dialog_real_activate (GApplication* base);
static void kde_connect_indicator_settings_dialog_create_window (KDEConnectIndicatorSettingsDialog* self);
static GtkBox* kde_connect_indicator_settings_dialog_create_visibility_setts (KDEConnectIndicatorSettingsDialog* self);
static GtkBox* kde_connect_indicator_settings_dialog_create_sms_setts (KDEConnectIndicatorSettingsDialog* self);
static void kde_connect_indicator_settings_dialog_create_signals (KDEConnectIndicatorSettingsDialog* self);
static void __lambda7_ (KDEConnectIndicatorSettingsDialog* self);
static void ___lambda7__gtk_button_clicked (GtkButton* _sender, gpointer self);
static void __lambda8_ (KDEConnectIndicatorSettingsDialog* self);
static void kde_connect_indicator_settings_dialog_restart (KDEConnectIndicatorSettingsDialog* self);
static void ___lambda8__gtk_button_clicked (GtkButton* _sender, gpointer self);
static Block1Data* block1_data_ref (Block1Data* _data1_);
static void block1_data_unref (void * _userdata_);
static void __lambda4_ (Block1Data* _data1_);
static void ___lambda4__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static void __lambda5_ (Block1Data* _data1_);
static void ___lambda5__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static Block2Data* block2_data_ref (Block2Data* _data2_);
static void block2_data_unref (void * _userdata_);
static void __lambda6_ (Block2Data* _data2_);
static void ___lambda6__gtk_button_clicked (GtkButton* _sender, gpointer self);
static void kde_connect_indicator_settings_dialog_finalize (GObject* obj);
gint kde_connect_indicator_main (gchar** args, int args_length1);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


KDEConnectIndicatorSettingsDialog* kde_connect_indicator_settings_dialog_construct (GType object_type) {
	KDEConnectIndicatorSettingsDialog * self = NULL;
#line 25 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	self = (KDEConnectIndicatorSettingsDialog*) g_object_new (object_type, "application-id", "com.bajoja.indicator-kdeconnect-settings", "flags", G_APPLICATION_FLAGS_NONE, NULL);
#line 24 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	return self;
#line 113 "Settings.c"
}


KDEConnectIndicatorSettingsDialog* kde_connect_indicator_settings_dialog_new (void) {
#line 24 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	return kde_connect_indicator_settings_dialog_construct (KDE_CONNECT_INDICATOR_TYPE_SETTINGS_DIALOG);
#line 120 "Settings.c"
}


static void kde_connect_indicator_settings_dialog_real_activate (GApplication* base) {
	KDEConnectIndicatorSettingsDialog * self;
	GSettings* _tmp0_ = NULL;
#line 29 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	self = (KDEConnectIndicatorSettingsDialog*) base;
#line 30 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp0_ = g_settings_new ("com.bajoja.indicator-kdeconnect");
#line 30 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_g_object_unref0 (self->priv->settings);
#line 30 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	self->priv->settings = _tmp0_;
#line 31 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	kde_connect_indicator_settings_dialog_create_window (self);
#line 137 "Settings.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 46 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	return self ? g_object_ref (self) : NULL;
#line 144 "Settings.c"
}


static void kde_connect_indicator_settings_dialog_create_window (KDEConnectIndicatorSettingsDialog* self) {
	GtkApplicationWindow* _tmp0_ = NULL;
	GtkApplicationWindow* _tmp1_ = NULL;
	GtkApplicationWindow* _tmp2_ = NULL;
	GtkApplicationWindow* _tmp3_ = NULL;
	GtkHeaderBar* _tmp4_ = NULL;
	const gchar* _tmp5_ = NULL;
	GtkButton* _tmp6_ = NULL;
	GtkHeaderBar* _tmp7_ = NULL;
	GtkButton* _tmp8_ = NULL;
	const gchar* _tmp9_ = NULL;
	GtkButton* _tmp10_ = NULL;
	GtkButton* _tmp11_ = NULL;
	GtkStyleContext* _tmp12_ = NULL;
	GtkStyleContext* _tmp13_ = NULL;
	GtkStyleContext* _tmp14_ = NULL;
	GtkHeaderBar* _tmp15_ = NULL;
	GtkButton* _tmp16_ = NULL;
	GtkStack* _tmp17_ = NULL;
	GtkStack* _tmp18_ = NULL;
	GtkStack* _tmp19_ = NULL;
	GtkBox* _tmp20_ = NULL;
	GtkBox* _tmp21_ = NULL;
	const gchar* _tmp22_ = NULL;
	GtkStack* _tmp23_ = NULL;
	GtkBox* _tmp24_ = NULL;
	GtkBox* _tmp25_ = NULL;
	const gchar* _tmp26_ = NULL;
	GtkStackSwitcher* _tmp27_ = NULL;
	GtkStackSwitcher* _tmp28_ = NULL;
	GtkStackSwitcher* _tmp29_ = NULL;
	GtkStack* _tmp30_ = NULL;
	GtkBox* title = NULL;
	GtkBox* _tmp31_ = NULL;
	GtkStackSwitcher* _tmp32_ = NULL;
	GtkHeaderBar* _tmp33_ = NULL;
	GtkApplicationWindow* _tmp34_ = NULL;
	GtkHeaderBar* _tmp35_ = NULL;
	GtkApplicationWindow* _tmp36_ = NULL;
	GtkStack* _tmp37_ = NULL;
	GtkApplicationWindow* _tmp38_ = NULL;
#line 34 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	g_return_if_fail (self != NULL);
#line 35 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp0_ = (GtkApplicationWindow*) gtk_application_window_new ((GtkApplication*) self);
#line 35 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	g_object_ref_sink (_tmp0_);
#line 35 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_g_object_unref0 (self->priv->window);
#line 35 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	self->priv->window = _tmp0_;
#line 36 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp1_ = self->priv->window;
#line 36 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	gtk_window_set_icon_name ((GtkWindow*) _tmp1_, "kdeconnect");
#line 37 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp2_ = self->priv->window;
#line 37 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	gtk_window_set_default_size ((GtkWindow*) _tmp2_, 200, 150);
#line 38 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp3_ = self->priv->window;
#line 38 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	gtk_container_set_border_width ((GtkContainer*) _tmp3_, (guint) 10);
#line 40 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp4_ = (GtkHeaderBar*) gtk_header_bar_new ();
#line 40 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	g_object_ref_sink (_tmp4_);
#line 40 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_g_object_unref0 (self->priv->headerBar);
#line 40 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	self->priv->headerBar = _tmp4_;
#line 42 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp5_ = _ ("Cancel");
#line 42 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp6_ = (GtkButton*) gtk_button_new_with_label (_tmp5_);
#line 42 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	g_object_ref_sink (_tmp6_);
#line 42 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_g_object_unref0 (self->priv->cancel_button);
#line 42 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	self->priv->cancel_button = _tmp6_;
#line 43 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp7_ = self->priv->headerBar;
#line 43 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp8_ = self->priv->cancel_button;
#line 43 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	gtk_header_bar_pack_start (_tmp7_, (GtkWidget*) _tmp8_);
#line 45 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp9_ = _ ("Apply");
#line 45 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp10_ = (GtkButton*) gtk_button_new_with_label (_tmp9_);
#line 45 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	g_object_ref_sink (_tmp10_);
#line 45 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_g_object_unref0 (self->priv->ok_button);
#line 45 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	self->priv->ok_button = _tmp10_;
#line 46 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp11_ = self->priv->ok_button;
#line 46 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp12_ = gtk_widget_get_style_context ((GtkWidget*) _tmp11_);
#line 46 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp13_ = _g_object_ref0 (_tmp12_);
#line 46 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_g_object_unref0 (self->priv->style_context);
#line 46 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	self->priv->style_context = _tmp13_;
#line 47 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp14_ = self->priv->style_context;
#line 47 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	gtk_style_context_add_class (_tmp14_, "suggested-action");
#line 48 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp15_ = self->priv->headerBar;
#line 48 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp16_ = self->priv->ok_button;
#line 48 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	gtk_header_bar_pack_end (_tmp15_, (GtkWidget*) _tmp16_);
#line 50 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp17_ = (GtkStack*) gtk_stack_new ();
#line 50 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	g_object_ref_sink (_tmp17_);
#line 50 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_g_object_unref0 (self->priv->stack);
#line 50 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	self->priv->stack = _tmp17_;
#line 52 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp18_ = self->priv->stack;
#line 52 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	gtk_stack_set_transition_type (_tmp18_, GTK_STACK_TRANSITION_TYPE_SLIDE_LEFT_RIGHT);
#line 54 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp19_ = self->priv->stack;
#line 54 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp20_ = kde_connect_indicator_settings_dialog_create_visibility_setts (self);
#line 54 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp21_ = _tmp20_;
#line 54 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp22_ = _ ("Visibility");
#line 54 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	gtk_stack_add_titled (_tmp19_, (GtkWidget*) _tmp21_, "visibility", _tmp22_);
#line 54 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_g_object_unref0 (_tmp21_);
#line 56 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp23_ = self->priv->stack;
#line 56 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp24_ = kde_connect_indicator_settings_dialog_create_sms_setts (self);
#line 56 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp25_ = _tmp24_;
#line 56 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp26_ = _ ("SMS");
#line 56 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	gtk_stack_add_titled (_tmp23_, (GtkWidget*) _tmp25_, "sms", _tmp26_);
#line 56 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_g_object_unref0 (_tmp25_);
#line 58 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp27_ = (GtkStackSwitcher*) gtk_stack_switcher_new ();
#line 58 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	g_object_ref_sink (_tmp27_);
#line 58 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_g_object_unref0 (self->priv->stack_switcher);
#line 58 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	self->priv->stack_switcher = _tmp27_;
#line 59 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp28_ = self->priv->stack_switcher;
#line 59 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	gtk_widget_set_halign ((GtkWidget*) _tmp28_, GTK_ALIGN_CENTER);
#line 60 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp29_ = self->priv->stack_switcher;
#line 60 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp30_ = self->priv->stack;
#line 60 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	gtk_stack_switcher_set_stack (_tmp29_, _tmp30_);
#line 62 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp31_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_VERTICAL, 0);
#line 62 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	g_object_ref_sink (_tmp31_);
#line 62 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	title = _tmp31_;
#line 63 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp32_ = self->priv->stack_switcher;
#line 63 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	gtk_box_pack_start (title, (GtkWidget*) _tmp32_, FALSE, FALSE, (guint) 0);
#line 65 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	kde_connect_indicator_settings_dialog_create_signals (self);
#line 67 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp33_ = self->priv->headerBar;
#line 67 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	gtk_header_bar_set_custom_title (_tmp33_, (GtkWidget*) title);
#line 69 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp34_ = self->priv->window;
#line 69 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp35_ = self->priv->headerBar;
#line 69 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	gtk_window_set_titlebar ((GtkWindow*) _tmp34_, (GtkWidget*) _tmp35_);
#line 71 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp36_ = self->priv->window;
#line 71 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp37_ = self->priv->stack;
#line 71 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	gtk_container_add ((GtkContainer*) _tmp36_, (GtkWidget*) _tmp37_);
#line 73 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp38_ = self->priv->window;
#line 73 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	gtk_widget_show_all ((GtkWidget*) _tmp38_);
#line 34 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_g_object_unref0 (title);
#line 353 "Settings.c"
}


static void __lambda7_ (KDEConnectIndicatorSettingsDialog* self) {
	GtkApplicationWindow* _tmp0_ = NULL;
#line 79 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp0_ = self->priv->window;
#line 79 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	gtk_window_close ((GtkWindow*) _tmp0_);
#line 363 "Settings.c"
}


static void ___lambda7__gtk_button_clicked (GtkButton* _sender, gpointer self) {
#line 78 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	__lambda7_ ((KDEConnectIndicatorSettingsDialog*) self);
#line 370 "Settings.c"
}


static void __lambda8_ (KDEConnectIndicatorSettingsDialog* self) {
	GSettings* _tmp0_ = NULL;
	GtkApplicationWindow* _tmp1_ = NULL;
#line 83 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp0_ = self->priv->settings;
#line 83 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	g_settings_apply (_tmp0_);
#line 84 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	kde_connect_indicator_settings_dialog_restart (self);
#line 85 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp1_ = self->priv->window;
#line 85 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	gtk_window_close ((GtkWindow*) _tmp1_);
#line 387 "Settings.c"
}


static void ___lambda8__gtk_button_clicked (GtkButton* _sender, gpointer self) {
#line 82 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	__lambda8_ ((KDEConnectIndicatorSettingsDialog*) self);
#line 394 "Settings.c"
}


static void kde_connect_indicator_settings_dialog_create_signals (KDEConnectIndicatorSettingsDialog* self) {
	GtkButton* _tmp0_ = NULL;
	GtkButton* _tmp1_ = NULL;
#line 76 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	g_return_if_fail (self != NULL);
#line 78 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp0_ = self->priv->cancel_button;
#line 78 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	g_signal_connect_object (_tmp0_, "clicked", (GCallback) ___lambda7__gtk_button_clicked, self, 0);
#line 82 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp1_ = self->priv->ok_button;
#line 82 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	g_signal_connect_object (_tmp1_, "clicked", (GCallback) ___lambda8__gtk_button_clicked, self, 0);
#line 411 "Settings.c"
}


static void kde_connect_indicator_settings_dialog_restart (KDEConnectIndicatorSettingsDialog* self) {
	gchar* std_out = NULL;
	const gchar* _tmp7_ = NULL;
	GError * _inner_error_ = NULL;
#line 91 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	g_return_if_fail (self != NULL);
#line 94 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	g_message ("Settings.vala:94: Getting PID");
#line 423 "Settings.c"
	{
		gchar* _tmp0_ = NULL;
		gchar* _tmp1_ = NULL;
		gchar** _tmp2_ = NULL;
		gchar** _tmp3_ = NULL;
		gint _tmp3__length1 = 0;
		gchar* _tmp4_ = NULL;
#line 97 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
		_tmp0_ = g_strdup ("pidof");
#line 97 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
		_tmp1_ = g_strdup ("indicator-kdeconnect");
#line 97 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
		_tmp2_ = g_new0 (gchar*, 2 + 1);
#line 97 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
		_tmp2_[0] = _tmp0_;
#line 97 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
		_tmp2_[1] = _tmp1_;
#line 97 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
		_tmp3_ = _tmp2_;
#line 97 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
		_tmp3__length1 = 2;
#line 97 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
		g_spawn_sync (NULL, _tmp3_, NULL, G_SPAWN_SEARCH_PATH, NULL, NULL, &_tmp4_, NULL, NULL, &_inner_error_);
#line 97 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
		_g_free0 (std_out);
#line 97 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
		std_out = _tmp4_;
#line 97 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
		_tmp3_ = (_vala_array_free (_tmp3_, _tmp3__length1, (GDestroyNotify) g_free), NULL);
#line 97 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 455 "Settings.c"
			goto __catch0_g_error;
		}
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		GError* _tmp5_ = NULL;
		const gchar* _tmp6_ = NULL;
#line 96 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
		e = _inner_error_;
#line 96 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
		_inner_error_ = NULL;
#line 107 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
		_tmp5_ = e;
#line 107 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
		_tmp6_ = _tmp5_->message;
#line 107 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
		g_message ("Settings.vala:107: %s", _tmp6_);
#line 96 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
		_g_error_free0 (e);
#line 477 "Settings.c"
	}
	__finally0:
#line 96 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 96 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
		_g_free0 (std_out);
#line 96 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 96 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
		g_clear_error (&_inner_error_);
#line 96 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
		return;
#line 490 "Settings.c"
	}
#line 111 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp7_ = std_out;
#line 111 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	if (g_strcmp0 (_tmp7_, "") != 0) {
#line 496 "Settings.c"
		gint pid = 0;
		const gchar* _tmp8_ = NULL;
		gint _tmp9_ = 0;
#line 112 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
		g_message ("Settings.vala:112: Kill PID");
#line 114 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
		_tmp8_ = std_out;
#line 114 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
		_tmp9_ = atoi (_tmp8_);
#line 114 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
		pid = _tmp9_;
#line 508 "Settings.c"
		{
			gchar* _tmp10_ = NULL;
			gint _tmp11_ = 0;
			gchar* _tmp12_ = NULL;
			gchar** _tmp13_ = NULL;
			gchar** _tmp14_ = NULL;
			gint _tmp14__length1 = 0;
			gchar* _tmp15_ = NULL;
#line 117 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			_tmp10_ = g_strdup ("kill");
#line 117 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			_tmp11_ = pid;
#line 117 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			_tmp12_ = g_strdup_printf ("%i", _tmp11_);
#line 117 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			_tmp13_ = g_new0 (gchar*, 2 + 1);
#line 117 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			_tmp13_[0] = _tmp10_;
#line 117 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			_tmp13_[1] = _tmp12_;
#line 117 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			_tmp14_ = _tmp13_;
#line 117 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			_tmp14__length1 = 2;
#line 117 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			g_spawn_sync (NULL, _tmp14_, NULL, G_SPAWN_SEARCH_PATH, NULL, NULL, &_tmp15_, NULL, NULL, &_inner_error_);
#line 117 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			_g_free0 (std_out);
#line 117 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			std_out = _tmp15_;
#line 117 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			_tmp14_ = (_vala_array_free (_tmp14_, _tmp14__length1, (GDestroyNotify) g_free), NULL);
#line 117 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 543 "Settings.c"
				goto __catch1_g_error;
			}
		}
		goto __finally1;
		__catch1_g_error:
		{
			GError* e = NULL;
			GError* _tmp16_ = NULL;
			const gchar* _tmp17_ = NULL;
#line 116 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			e = _inner_error_;
#line 116 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			_inner_error_ = NULL;
#line 127 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			_tmp16_ = e;
#line 127 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			_tmp17_ = _tmp16_->message;
#line 127 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			g_message ("Settings.vala:127: %s", _tmp17_);
#line 116 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			_g_error_free0 (e);
#line 565 "Settings.c"
		}
		__finally1:
#line 116 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 116 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			_g_free0 (std_out);
#line 116 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 116 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			g_clear_error (&_inner_error_);
#line 116 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			return;
#line 578 "Settings.c"
		}
#line 131 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
		g_message ("Settings.vala:131: Restart process");
#line 582 "Settings.c"
		{
			gchar* _tmp18_ = NULL;
			gchar** _tmp19_ = NULL;
			gchar** _tmp20_ = NULL;
			gint _tmp20__length1 = 0;
#line 133 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			_tmp18_ = g_strdup ("indicator-kdeconnect");
#line 133 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			_tmp19_ = g_new0 (gchar*, 1 + 1);
#line 133 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			_tmp19_[0] = _tmp18_;
#line 133 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			_tmp20_ = _tmp19_;
#line 133 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			_tmp20__length1 = 1;
#line 133 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			g_spawn_async (NULL, _tmp20_, NULL, G_SPAWN_SEARCH_PATH, NULL, NULL, NULL, &_inner_error_);
#line 133 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			_tmp20_ = (_vala_array_free (_tmp20_, _tmp20__length1, (GDestroyNotify) g_free), NULL);
#line 133 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 604 "Settings.c"
				goto __catch2_g_error;
			}
		}
		goto __finally2;
		__catch2_g_error:
		{
			GError* e = NULL;
			GError* _tmp21_ = NULL;
			const gchar* _tmp22_ = NULL;
#line 132 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			e = _inner_error_;
#line 132 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			_inner_error_ = NULL;
#line 140 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			_tmp21_ = e;
#line 140 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			_tmp22_ = _tmp21_->message;
#line 140 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			g_message ("Settings.vala:140: %s", _tmp22_);
#line 132 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			_g_error_free0 (e);
#line 626 "Settings.c"
		}
		__finally2:
#line 132 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 132 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			_g_free0 (std_out);
#line 132 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 132 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			g_clear_error (&_inner_error_);
#line 132 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			return;
#line 639 "Settings.c"
		}
	}
#line 91 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_g_free0 (std_out);
#line 644 "Settings.c"
}


static Block1Data* block1_data_ref (Block1Data* _data1_) {
#line 145 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	g_atomic_int_inc (&_data1_->_ref_count_);
#line 145 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	return _data1_;
#line 653 "Settings.c"
}


static void block1_data_unref (void * _userdata_) {
	Block1Data* _data1_;
	_data1_ = (Block1Data*) _userdata_;
#line 145 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	if (g_atomic_int_dec_and_test (&_data1_->_ref_count_)) {
#line 662 "Settings.c"
		KDEConnectIndicatorSettingsDialog* self;
#line 145 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
		self = _data1_->self;
#line 145 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
		_g_object_unref0 (_data1_->switch2);
#line 145 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
		_g_object_unref0 (_data1_->switch1);
#line 145 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
		_g_object_unref0 (self);
#line 145 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
		g_slice_free (Block1Data, _data1_);
#line 674 "Settings.c"
	}
}


static void __lambda4_ (Block1Data* _data1_) {
	KDEConnectIndicatorSettingsDialog* self;
	GSettings* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
#line 151 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	self = _data1_->self;
#line 152 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp0_ = self->priv->settings;
#line 152 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp1_ = gtk_switch_get_active (_data1_->switch1);
#line 152 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp2_ = _tmp1_;
#line 152 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	g_settings_set_boolean (_tmp0_, "visibilitiy", _tmp2_);
#line 694 "Settings.c"
}


static void ___lambda4__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
#line 151 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	__lambda4_ (self);
#line 701 "Settings.c"
}


static void __lambda5_ (Block1Data* _data1_) {
	KDEConnectIndicatorSettingsDialog* self;
	GSettings* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
#line 171 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	self = _data1_->self;
#line 172 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp0_ = self->priv->settings;
#line 172 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp1_ = gtk_switch_get_active (_data1_->switch2);
#line 172 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp2_ = _tmp1_;
#line 172 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	g_settings_set_boolean (_tmp0_, "list-device-dir", _tmp2_);
#line 720 "Settings.c"
}


static void ___lambda5__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
#line 171 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	__lambda5_ (self);
#line 727 "Settings.c"
}


static GtkBox* kde_connect_indicator_settings_dialog_create_visibility_setts (KDEConnectIndicatorSettingsDialog* self) {
	GtkBox* result = NULL;
	Block1Data* _data1_;
	GtkLabel* label1 = NULL;
	const gchar* _tmp0_ = NULL;
	GtkLabel* _tmp1_ = NULL;
	GtkSwitch* _tmp2_ = NULL;
	GSettings* _tmp3_ = NULL;
	gboolean _tmp4_ = FALSE;
	GtkBox* hbox1 = NULL;
	GtkBox* _tmp5_ = NULL;
	GtkListBoxRow* boxrow1 = NULL;
	GtkListBoxRow* _tmp6_ = NULL;
	GtkLabel* label2 = NULL;
	const gchar* _tmp7_ = NULL;
	GtkLabel* _tmp8_ = NULL;
	GtkSwitch* _tmp9_ = NULL;
	GSettings* _tmp10_ = NULL;
	gboolean _tmp11_ = FALSE;
	GtkBox* hbox2 = NULL;
	GtkBox* _tmp12_ = NULL;
	GtkListBoxRow* boxrow2 = NULL;
	GtkListBoxRow* _tmp13_ = NULL;
	GtkListBox* list_box = NULL;
	GtkListBox* _tmp14_ = NULL;
	GtkBox* vbox = NULL;
	GtkBox* _tmp15_ = NULL;
#line 145 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 145 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_data1_ = g_slice_new0 (Block1Data);
#line 145 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_data1_->_ref_count_ = 1;
#line 145 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_data1_->self = g_object_ref (self);
#line 146 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp0_ = _ ("Show only paired devices: ");
#line 146 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp1_ = (GtkLabel*) gtk_label_new (_tmp0_);
#line 146 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	g_object_ref_sink (_tmp1_);
#line 146 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	label1 = _tmp1_;
#line 148 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp2_ = (GtkSwitch*) gtk_switch_new ();
#line 148 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	g_object_ref_sink (_tmp2_);
#line 148 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_data1_->switch1 = _tmp2_;
#line 149 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp3_ = self->priv->settings;
#line 149 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp4_ = g_settings_get_boolean (_tmp3_, "visibilitiy");
#line 149 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	gtk_switch_set_active (_data1_->switch1, _tmp4_);
#line 151 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	g_signal_connect_data ((GObject*) _data1_->switch1, "notify::active", (GCallback) ___lambda4__g_object_notify, block1_data_ref (_data1_), (GClosureNotify) block1_data_unref, 0);
#line 155 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp5_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 50);
#line 155 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	g_object_ref_sink (_tmp5_);
#line 155 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	hbox1 = _tmp5_;
#line 157 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	gtk_box_pack_start (hbox1, (GtkWidget*) label1, TRUE, TRUE, (guint) 0);
#line 158 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	gtk_box_pack_start (hbox1, (GtkWidget*) _data1_->switch1, TRUE, TRUE, (guint) 0);
#line 160 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp6_ = (GtkListBoxRow*) gtk_list_box_row_new ();
#line 160 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	g_object_ref_sink (_tmp6_);
#line 160 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	boxrow1 = _tmp6_;
#line 162 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	gtk_container_add ((GtkContainer*) boxrow1, (GtkWidget*) hbox1);
#line 166 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp7_ = _ ("Show device directories: ");
#line 166 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp8_ = (GtkLabel*) gtk_label_new (_tmp7_);
#line 166 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	g_object_ref_sink (_tmp8_);
#line 166 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	label2 = _tmp8_;
#line 168 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp9_ = (GtkSwitch*) gtk_switch_new ();
#line 168 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	g_object_ref_sink (_tmp9_);
#line 168 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_data1_->switch2 = _tmp9_;
#line 169 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp10_ = self->priv->settings;
#line 169 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp11_ = g_settings_get_boolean (_tmp10_, "list-device-dir");
#line 169 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	gtk_switch_set_active (_data1_->switch2, _tmp11_);
#line 171 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	g_signal_connect_data ((GObject*) _data1_->switch2, "notify::active", (GCallback) ___lambda5__g_object_notify, block1_data_ref (_data1_), (GClosureNotify) block1_data_unref, 0);
#line 175 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp12_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 50);
#line 175 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	g_object_ref_sink (_tmp12_);
#line 175 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	hbox2 = _tmp12_;
#line 177 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	gtk_box_pack_start (hbox2, (GtkWidget*) label2, TRUE, TRUE, (guint) 0);
#line 178 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	gtk_box_pack_start (hbox2, (GtkWidget*) _data1_->switch2, TRUE, TRUE, (guint) 0);
#line 180 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp13_ = (GtkListBoxRow*) gtk_list_box_row_new ();
#line 180 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	g_object_ref_sink (_tmp13_);
#line 180 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	boxrow2 = _tmp13_;
#line 182 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	gtk_container_add ((GtkContainer*) boxrow2, (GtkWidget*) hbox2);
#line 186 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp14_ = (GtkListBox*) gtk_list_box_new ();
#line 186 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	g_object_ref_sink (_tmp14_);
#line 186 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	list_box = _tmp14_;
#line 187 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	gtk_list_box_set_selection_mode (list_box, GTK_SELECTION_NONE);
#line 190 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	gtk_container_add ((GtkContainer*) list_box, (GtkWidget*) boxrow1);
#line 191 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	gtk_container_add ((GtkContainer*) list_box, (GtkWidget*) boxrow2);
#line 193 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp15_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 0);
#line 193 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	g_object_ref_sink (_tmp15_);
#line 193 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	vbox = _tmp15_;
#line 194 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	gtk_box_pack_start (vbox, (GtkWidget*) list_box, TRUE, TRUE, (guint) 0);
#line 196 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	result = vbox;
#line 196 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_g_object_unref0 (list_box);
#line 196 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_g_object_unref0 (boxrow2);
#line 196 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_g_object_unref0 (hbox2);
#line 196 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_g_object_unref0 (label2);
#line 196 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_g_object_unref0 (boxrow1);
#line 196 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_g_object_unref0 (hbox1);
#line 196 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_g_object_unref0 (label1);
#line 196 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	block1_data_unref (_data1_);
#line 196 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_data1_ = NULL;
#line 196 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	return result;
#line 888 "Settings.c"
}


static Block2Data* block2_data_ref (Block2Data* _data2_) {
#line 199 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	g_atomic_int_inc (&_data2_->_ref_count_);
#line 199 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	return _data2_;
#line 897 "Settings.c"
}


static void block2_data_unref (void * _userdata_) {
	Block2Data* _data2_;
	_data2_ = (Block2Data*) _userdata_;
#line 199 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	if (g_atomic_int_dec_and_test (&_data2_->_ref_count_)) {
#line 906 "Settings.c"
		KDEConnectIndicatorSettingsDialog* self;
#line 199 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
		self = _data2_->self;
#line 199 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
		_g_object_unref0 (_data2_->token);
#line 199 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
		_g_object_unref0 (_data2_->contacts);
#line 199 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
		_g_object_unref0 (_data2_->button1);
#line 199 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
		_g_object_unref0 (self);
#line 199 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
		g_slice_free (Block2Data, _data2_);
#line 920 "Settings.c"
	}
}


static void __lambda6_ (Block2Data* _data2_) {
	KDEConnectIndicatorSettingsDialog* self;
	gboolean tmp = FALSE;
	GFile* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	GFile* _tmp5_ = NULL;
	gboolean _tmp6_ = FALSE;
	gboolean _tmp10_ = FALSE;
	GError * _inner_error_ = NULL;
#line 218 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	self = _data2_->self;
#line 219 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	tmp = FALSE;
#line 221 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp0_ = _data2_->contacts;
#line 221 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp1_ = g_file_query_exists (_tmp0_, NULL);
#line 221 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	if (_tmp1_) {
#line 944 "Settings.c"
		{
			GFile* _tmp2_ = NULL;
#line 223 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			_tmp2_ = _data2_->contacts;
#line 223 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			g_file_delete (_tmp2_, NULL, &_inner_error_);
#line 223 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 953 "Settings.c"
				goto __catch3_g_error;
			}
#line 224 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			tmp = TRUE;
#line 958 "Settings.c"
		}
		goto __finally3;
		__catch3_g_error:
		{
			GError* e = NULL;
			GError* _tmp3_ = NULL;
			const gchar* _tmp4_ = NULL;
#line 222 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			e = _inner_error_;
#line 222 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			_inner_error_ = NULL;
#line 226 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			_tmp3_ = e;
#line 226 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			_tmp4_ = _tmp3_->message;
#line 226 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			g_message ("Settings.vala:226: %s", _tmp4_);
#line 227 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			tmp = FALSE;
#line 222 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			_g_error_free0 (e);
#line 980 "Settings.c"
		}
		__finally3:
#line 222 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 222 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 222 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			g_clear_error (&_inner_error_);
#line 222 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			return;
#line 991 "Settings.c"
		}
	}
#line 230 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp5_ = _data2_->token;
#line 230 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp6_ = g_file_query_exists (_tmp5_, NULL);
#line 230 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	if (_tmp6_) {
#line 1000 "Settings.c"
		{
			GFile* _tmp7_ = NULL;
#line 232 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			_tmp7_ = _data2_->token;
#line 232 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			g_file_delete (_tmp7_, NULL, &_inner_error_);
#line 232 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 1009 "Settings.c"
				goto __catch4_g_error;
			}
#line 233 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			tmp = TRUE;
#line 1014 "Settings.c"
		}
		goto __finally4;
		__catch4_g_error:
		{
			GError* e = NULL;
			GError* _tmp8_ = NULL;
			const gchar* _tmp9_ = NULL;
#line 231 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			e = _inner_error_;
#line 231 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			_inner_error_ = NULL;
#line 235 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			_tmp8_ = e;
#line 235 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			_tmp9_ = _tmp8_->message;
#line 235 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			g_message ("Settings.vala:235: %s", _tmp9_);
#line 236 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			tmp = FALSE;
#line 231 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			_g_error_free0 (e);
#line 1036 "Settings.c"
		}
		__finally4:
#line 231 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 231 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 231 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			g_clear_error (&_inner_error_);
#line 231 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
			return;
#line 1047 "Settings.c"
		}
	}
#line 239 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp10_ = tmp;
#line 239 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	if (_tmp10_) {
#line 1054 "Settings.c"
		GtkButton* _tmp11_ = NULL;
#line 240 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
		_tmp11_ = _data2_->button1;
#line 240 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
		gtk_widget_set_sensitive ((GtkWidget*) _tmp11_, FALSE);
#line 1060 "Settings.c"
	}
}


static void ___lambda6__gtk_button_clicked (GtkButton* _sender, gpointer self) {
#line 218 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	__lambda6_ (self);
#line 1068 "Settings.c"
}


static GtkBox* kde_connect_indicator_settings_dialog_create_sms_setts (KDEConnectIndicatorSettingsDialog* self) {
	GtkBox* result = NULL;
	Block2Data* _data2_;
	GtkLabel* label1 = NULL;
	const gchar* _tmp0_ = NULL;
	GtkLabel* _tmp1_ = NULL;
	GtkButton* _tmp2_ = NULL;
	GtkButton* _tmp3_ = NULL;
	gchar* _contacts = NULL;
	const gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* _token = NULL;
	const gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	const gchar* _tmp8_ = NULL;
	GFile* _tmp9_ = NULL;
	const gchar* _tmp10_ = NULL;
	GFile* _tmp11_ = NULL;
	gboolean _tmp12_ = FALSE;
	GFile* _tmp13_ = NULL;
	gboolean _tmp14_ = FALSE;
	GtkButton* _tmp18_ = NULL;
	GtkListBox* list_box = NULL;
	GtkListBox* _tmp19_ = NULL;
	GtkBox* hbox1 = NULL;
	GtkBox* _tmp20_ = NULL;
	GtkListBoxRow* boxrow1 = NULL;
	GtkListBoxRow* _tmp21_ = NULL;
	GtkLabel* _tmp22_ = NULL;
	GtkButton* _tmp23_ = NULL;
	GtkBox* vbox = NULL;
	GtkBox* _tmp24_ = NULL;
#line 199 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 199 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_data2_ = g_slice_new0 (Block2Data);
#line 199 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_data2_->_ref_count_ = 1;
#line 199 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_data2_->self = g_object_ref (self);
#line 200 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp0_ = _ ("Delete Google Contacts: ");
#line 200 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp1_ = (GtkLabel*) gtk_label_new (_tmp0_);
#line 200 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	g_object_ref_sink (_tmp1_);
#line 200 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	label1 = _tmp1_;
#line 202 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp2_ = (GtkButton*) gtk_button_new_from_icon_name ("user-trash", GTK_ICON_SIZE_BUTTON);
#line 202 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	g_object_ref_sink (_tmp2_);
#line 202 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_data2_->button1 = _tmp2_;
#line 204 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp3_ = _data2_->button1;
#line 204 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	gtk_widget_set_sensitive ((GtkWidget*) _tmp3_, FALSE);
#line 206 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp4_ = g_get_user_data_dir ();
#line 206 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp5_ = g_strconcat (_tmp4_, "/indicator-kdeconnect/sms/contacts.json", NULL);
#line 206 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_contacts = _tmp5_;
#line 209 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp6_ = g_get_user_data_dir ();
#line 209 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp7_ = g_strconcat (_tmp6_, "/indicator-kdeconnect/sms/token.json", NULL);
#line 209 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_token = _tmp7_;
#line 212 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp8_ = _contacts;
#line 212 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp9_ = g_file_new_for_path (_tmp8_);
#line 212 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_data2_->contacts = _tmp9_;
#line 213 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp10_ = _token;
#line 213 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp11_ = g_file_new_for_path (_tmp10_);
#line 213 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_data2_->token = _tmp11_;
#line 215 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp13_ = _data2_->contacts;
#line 215 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp14_ = g_file_query_exists (_tmp13_, NULL);
#line 215 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	if (_tmp14_) {
#line 215 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
		_tmp12_ = TRUE;
#line 1162 "Settings.c"
	} else {
		GFile* _tmp15_ = NULL;
		gboolean _tmp16_ = FALSE;
#line 215 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
		_tmp15_ = _data2_->token;
#line 215 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
		_tmp16_ = g_file_query_exists (_tmp15_, NULL);
#line 215 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
		_tmp12_ = _tmp16_;
#line 1172 "Settings.c"
	}
#line 215 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	if (_tmp12_) {
#line 1176 "Settings.c"
		GtkButton* _tmp17_ = NULL;
#line 216 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
		_tmp17_ = _data2_->button1;
#line 216 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
		gtk_widget_set_sensitive ((GtkWidget*) _tmp17_, TRUE);
#line 1182 "Settings.c"
	}
#line 218 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp18_ = _data2_->button1;
#line 218 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	g_signal_connect_data (_tmp18_, "clicked", (GCallback) ___lambda6__gtk_button_clicked, block2_data_ref (_data2_), (GClosureNotify) block2_data_unref, 0);
#line 243 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp19_ = (GtkListBox*) gtk_list_box_new ();
#line 243 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	g_object_ref_sink (_tmp19_);
#line 243 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	list_box = _tmp19_;
#line 244 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	gtk_list_box_set_selection_mode (list_box, GTK_SELECTION_NONE);
#line 246 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp20_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 50);
#line 246 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	g_object_ref_sink (_tmp20_);
#line 246 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	hbox1 = _tmp20_;
#line 248 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp21_ = (GtkListBoxRow*) gtk_list_box_row_new ();
#line 248 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	g_object_ref_sink (_tmp21_);
#line 248 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	boxrow1 = _tmp21_;
#line 250 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	gtk_container_add ((GtkContainer*) boxrow1, (GtkWidget*) hbox1);
#line 252 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp22_ = label1;
#line 252 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	gtk_box_pack_start (hbox1, (GtkWidget*) _tmp22_, TRUE, TRUE, (guint) 0);
#line 253 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp23_ = _data2_->button1;
#line 253 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	gtk_box_pack_start (hbox1, (GtkWidget*) _tmp23_, TRUE, TRUE, (guint) 0);
#line 255 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	gtk_container_add ((GtkContainer*) list_box, (GtkWidget*) boxrow1);
#line 257 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp24_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 0);
#line 257 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	g_object_ref_sink (_tmp24_);
#line 257 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	vbox = _tmp24_;
#line 258 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	gtk_box_pack_start (vbox, (GtkWidget*) list_box, TRUE, TRUE, (guint) 0);
#line 260 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	result = vbox;
#line 260 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_g_object_unref0 (boxrow1);
#line 260 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_g_object_unref0 (hbox1);
#line 260 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_g_object_unref0 (list_box);
#line 260 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_g_free0 (_token);
#line 260 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_g_free0 (_contacts);
#line 260 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_g_object_unref0 (label1);
#line 260 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	block2_data_unref (_data2_);
#line 260 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_data2_ = NULL;
#line 260 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	return result;
#line 1248 "Settings.c"
}


static void kde_connect_indicator_settings_dialog_class_init (KDEConnectIndicatorSettingsDialogClass * klass) {
#line 13 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	kde_connect_indicator_settings_dialog_parent_class = g_type_class_peek_parent (klass);
#line 13 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	g_type_class_add_private (klass, sizeof (KDEConnectIndicatorSettingsDialogPrivate));
#line 13 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	((GApplicationClass *) klass)->activate = (void (*)(GApplication*)) kde_connect_indicator_settings_dialog_real_activate;
#line 13 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	G_OBJECT_CLASS (klass)->finalize = kde_connect_indicator_settings_dialog_finalize;
#line 1261 "Settings.c"
}


static void kde_connect_indicator_settings_dialog_instance_init (KDEConnectIndicatorSettingsDialog * self) {
#line 13 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	self->priv = KDE_CONNECT_INDICATOR_SETTINGS_DIALOG_GET_PRIVATE (self);
#line 1268 "Settings.c"
}


static void kde_connect_indicator_settings_dialog_finalize (GObject* obj) {
	KDEConnectIndicatorSettingsDialog * self;
#line 13 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, KDE_CONNECT_INDICATOR_TYPE_SETTINGS_DIALOG, KDEConnectIndicatorSettingsDialog);
#line 14 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_g_object_unref0 (self->priv->settings);
#line 15 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_g_object_unref0 (self->priv->window);
#line 16 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_g_object_unref0 (self->priv->headerBar);
#line 17 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_g_object_unref0 (self->priv->cancel_button);
#line 18 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_g_object_unref0 (self->priv->ok_button);
#line 19 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_g_object_unref0 (self->priv->style_context);
#line 20 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_g_object_unref0 (self->priv->stack);
#line 21 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_g_object_unref0 (self->priv->stack_switcher);
#line 13 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	G_OBJECT_CLASS (kde_connect_indicator_settings_dialog_parent_class)->finalize (obj);
#line 1294 "Settings.c"
}


GType kde_connect_indicator_settings_dialog_get_type (void) {
	static volatile gsize kde_connect_indicator_settings_dialog_type_id__volatile = 0;
	if (g_once_init_enter (&kde_connect_indicator_settings_dialog_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (KDEConnectIndicatorSettingsDialogClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) kde_connect_indicator_settings_dialog_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (KDEConnectIndicatorSettingsDialog), 0, (GInstanceInitFunc) kde_connect_indicator_settings_dialog_instance_init, NULL };
		GType kde_connect_indicator_settings_dialog_type_id;
		kde_connect_indicator_settings_dialog_type_id = g_type_register_static (gtk_application_get_type (), "KDEConnectIndicatorSettingsDialog", &g_define_type_info, 0);
		g_once_init_leave (&kde_connect_indicator_settings_dialog_type_id__volatile, kde_connect_indicator_settings_dialog_type_id);
	}
	return kde_connect_indicator_settings_dialog_type_id__volatile;
}


gint kde_connect_indicator_main (gchar** args, int args_length1) {
	gint result = 0;
	KDEConnectIndicatorSettingsDialog* _tmp0_ = NULL;
	KDEConnectIndicatorSettingsDialog* _tmp1_ = NULL;
	gchar** _tmp2_ = NULL;
	gint _tmp2__length1 = 0;
	gint _tmp3_ = 0;
	gint _tmp4_ = 0;
#line 265 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp0_ = kde_connect_indicator_settings_dialog_new ();
#line 265 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp1_ = _tmp0_;
#line 265 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp2_ = args;
#line 265 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp2__length1 = args_length1;
#line 265 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp3_ = g_application_run ((GApplication*) _tmp1_, _tmp2__length1, _tmp2_);
#line 265 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_tmp4_ = _tmp3_;
#line 265 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	_g_object_unref0 (_tmp1_);
#line 265 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	result = _tmp4_;
#line 265 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	return result;
#line 1336 "Settings.c"
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
#line 264 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/settings/Settings.vala"
	return kde_connect_indicator_main (argv, argc);
#line 1346 "Settings.c"
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



