/* KDEConnectSend.c generated by valac 0.34.7, the Vala compiler
 * generated from KDEConnectSend.vala, do not modify */

/* Copyright 2014 KDE Connect Indicator Developers
 *
 * This software is licensed under the GNU Lesser General Public License
 * (version 2.1 or later).  See the COPYING file in this distribution.
 */

#include <glib.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <glib/gi18n-lib.h>


#define KDE_CONNECT_INDICATOR_TYPE_SEND_DIALOG (kde_connect_indicator_send_dialog_get_type ())
#define KDE_CONNECT_INDICATOR_SEND_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), KDE_CONNECT_INDICATOR_TYPE_SEND_DIALOG, KDEConnectIndicatorSendDialog))
#define KDE_CONNECT_INDICATOR_SEND_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), KDE_CONNECT_INDICATOR_TYPE_SEND_DIALOG, KDEConnectIndicatorSendDialogClass))
#define KDE_CONNECT_INDICATOR_IS_SEND_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), KDE_CONNECT_INDICATOR_TYPE_SEND_DIALOG))
#define KDE_CONNECT_INDICATOR_IS_SEND_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), KDE_CONNECT_INDICATOR_TYPE_SEND_DIALOG))
#define KDE_CONNECT_INDICATOR_SEND_DIALOG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), KDE_CONNECT_INDICATOR_TYPE_SEND_DIALOG, KDEConnectIndicatorSendDialogClass))

typedef struct _KDEConnectIndicatorSendDialog KDEConnectIndicatorSendDialog;
typedef struct _KDEConnectIndicatorSendDialogClass KDEConnectIndicatorSendDialogClass;
typedef struct _KDEConnectIndicatorSendDialogPrivate KDEConnectIndicatorSendDialogPrivate;

#define KDE_CONNECT_INDICATOR_TYPE_DEVICE (kde_connect_indicator_device_get_type ())
#define KDE_CONNECT_INDICATOR_DEVICE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), KDE_CONNECT_INDICATOR_TYPE_DEVICE, KDEConnectIndicatorDevice))
#define KDE_CONNECT_INDICATOR_DEVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), KDE_CONNECT_INDICATOR_TYPE_DEVICE, KDEConnectIndicatorDeviceClass))
#define KDE_CONNECT_INDICATOR_IS_DEVICE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), KDE_CONNECT_INDICATOR_TYPE_DEVICE))
#define KDE_CONNECT_INDICATOR_IS_DEVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), KDE_CONNECT_INDICATOR_TYPE_DEVICE))
#define KDE_CONNECT_INDICATOR_DEVICE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), KDE_CONNECT_INDICATOR_TYPE_DEVICE, KDEConnectIndicatorDeviceClass))

typedef struct _KDEConnectIndicatorDevice KDEConnectIndicatorDevice;
typedef struct _KDEConnectIndicatorDeviceClass KDEConnectIndicatorDeviceClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define __g_slist_free__kde_connect_indicator_device_unref0_0(var) ((var == NULL) ? NULL : (var = (_g_slist_free__kde_connect_indicator_device_unref0_ (var), NULL)))
#define __g_slist_free__g_object_unref0_0(var) ((var == NULL) ? NULL : (var = (_g_slist_free__g_object_unref0_ (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_slist_free0(var) ((var == NULL) ? NULL : (var = (g_slist_free (var), NULL)))
#define _gtk_tree_path_free0(var) ((var == NULL) ? NULL : (var = (gtk_tree_path_free (var), NULL)))
#define __g_list_free__gtk_tree_path_free0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__gtk_tree_path_free0_ (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_variant_unref0(var) ((var == NULL) ? NULL : (var = (g_variant_unref (var), NULL)))
#define _kde_connect_indicator_device_unref0(var) ((var == NULL) ? NULL : (var = (kde_connect_indicator_device_unref (var), NULL)))

struct _KDEConnectIndicatorSendDialog {
	GtkApplication parent_instance;
	KDEConnectIndicatorSendDialogPrivate * priv;
};

struct _KDEConnectIndicatorSendDialogClass {
	GtkApplicationClass parent_class;
};

struct _KDEConnectIndicatorSendDialogPrivate {
	GtkApplicationWindow* window;
	GtkHeaderBar* headerBar;
	GtkButton* cancel_button;
	GtkButton* send_button;
	GtkButton* reload_button;
	GtkStyleContext* style_context;
	GtkTreeView* tv;
	GtkListStore* list_store;
	GDBusConnection* conn;
	GtkTreeSelection* ts;
	GSList* device_list;
};


extern GSList* kde_connect_indicator_files;
GSList* kde_connect_indicator_files = NULL;
static gpointer kde_connect_indicator_send_dialog_parent_class = NULL;

GType kde_connect_indicator_send_dialog_get_type (void) G_GNUC_CONST;
gpointer kde_connect_indicator_device_ref (gpointer instance);
void kde_connect_indicator_device_unref (gpointer instance);
GParamSpec* kde_connect_indicator_param_spec_device (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void kde_connect_indicator_value_set_device (GValue* value, gpointer v_object);
void kde_connect_indicator_value_take_device (GValue* value, gpointer v_object);
gpointer kde_connect_indicator_value_get_device (const GValue* value);
GType kde_connect_indicator_device_get_type (void) G_GNUC_CONST;
#define KDE_CONNECT_INDICATOR_SEND_DIALOG_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), KDE_CONNECT_INDICATOR_TYPE_SEND_DIALOG, KDEConnectIndicatorSendDialogPrivate))
enum  {
	KDE_CONNECT_INDICATOR_SEND_DIALOG_DUMMY_PROPERTY
};
static void _kde_connect_indicator_device_unref0_ (gpointer var);
static void _g_slist_free__kde_connect_indicator_device_unref0_ (GSList* self);
KDEConnectIndicatorSendDialog* kde_connect_indicator_send_dialog_new (void);
KDEConnectIndicatorSendDialog* kde_connect_indicator_send_dialog_construct (GType object_type);
static void kde_connect_indicator_send_dialog_real_activate (GApplication* base);
static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender, gpointer self);
static void kde_connect_indicator_send_dialog_create_window (KDEConnectIndicatorSendDialog* self);
static void kde_connect_indicator_send_dialog_create_signals (KDEConnectIndicatorSendDialog* self);
static void kde_connect_indicator_send_dialog_reload_device_list (KDEConnectIndicatorSendDialog* self);
static void kde_connect_indicator_send_dialog_real_open (GApplication* base, GFile** _files, int _files_length1, const gchar* hint);
static void _g_object_unref0_ (gpointer var);
static void _g_slist_free__g_object_unref0_ (GSList* self);
static void __lambda5_ (KDEConnectIndicatorSendDialog* self);
static GSList* kde_connect_indicator_send_dialog_get_selected (KDEConnectIndicatorSendDialog* self);
static void ___lambda5__gtk_tree_view_cursor_changed (GtkTreeView* _sender, gpointer self);
static void __lambda6_ (KDEConnectIndicatorSendDialog* self, GtkTreePath* path, GtkTreeViewColumn* column);
static void kde_connect_indicator_send_dialog_send_items (KDEConnectIndicatorSendDialog* self);
static void ___lambda6__gtk_tree_view_row_activated (GtkTreeView* _sender, GtkTreePath* path, GtkTreeViewColumn* column, gpointer self);
static void __lambda7_ (KDEConnectIndicatorSendDialog* self);
static void ___lambda7__gtk_button_clicked (GtkButton* _sender, gpointer self);
static void __lambda8_ (KDEConnectIndicatorSendDialog* self);
static void ___lambda8__gtk_button_clicked (GtkButton* _sender, gpointer self);
static void __lambda9_ (KDEConnectIndicatorSendDialog* self);
static void ___lambda9__gtk_button_clicked (GtkButton* _sender, gpointer self);
static void _gtk_tree_path_free0_ (gpointer var);
static void _g_list_free__gtk_tree_path_free0_ (GList* self);
static void kde_connect_indicator_send_dialog_set_device_list (KDEConnectIndicatorSendDialog* self, GtkListStore* device_list);
KDEConnectIndicatorDevice* kde_connect_indicator_device_new (const gchar* path);
KDEConnectIndicatorDevice* kde_connect_indicator_device_construct (GType object_type, const gchar* path);
gboolean kde_connect_indicator_device_get_is_reachable (KDEConnectIndicatorDevice* self);
gboolean kde_connect_indicator_device_get_is_trusted (KDEConnectIndicatorDevice* self);
const gchar* kde_connect_indicator_device_get_name (KDEConnectIndicatorDevice* self);
void kde_connect_indicator_device_send_file (KDEConnectIndicatorDevice* self, const gchar* url);
static void kde_connect_indicator_send_dialog_finalize (GObject* obj);
gint kde_connect_indicator_main (gchar** args, int args_length1);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


static void _kde_connect_indicator_device_unref0_ (gpointer var) {
#line 25 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	(var == NULL) ? NULL : (var = (kde_connect_indicator_device_unref (var), NULL));
#line 133 "KDEConnectSend.c"
}


static void _g_slist_free__kde_connect_indicator_device_unref0_ (GSList* self) {
#line 25 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	g_slist_foreach (self, (GFunc) _kde_connect_indicator_device_unref0_, NULL);
#line 25 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	g_slist_free (self);
#line 142 "KDEConnectSend.c"
}


KDEConnectIndicatorSendDialog* kde_connect_indicator_send_dialog_construct (GType object_type) {
	KDEConnectIndicatorSendDialog * self = NULL;
#line 28 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	self = (KDEConnectIndicatorSendDialog*) g_object_new (object_type, "application-id", "com.bajoja.kdeconnect-send", "flags", G_APPLICATION_HANDLES_OPEN, NULL);
#line 27 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	return self;
#line 152 "KDEConnectSend.c"
}


KDEConnectIndicatorSendDialog* kde_connect_indicator_send_dialog_new (void) {
#line 27 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	return kde_connect_indicator_send_dialog_construct (KDE_CONNECT_INDICATOR_TYPE_SEND_DIALOG);
#line 159 "KDEConnectSend.c"
}


static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender, gpointer self) {
#line 44 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	gtk_main_quit ();
#line 166 "KDEConnectSend.c"
}


static void kde_connect_indicator_send_dialog_real_activate (GApplication* base) {
	KDEConnectIndicatorSendDialog * self;
	GSList* _tmp0_ = NULL;
	guint _tmp1_ = 0U;
#line 32 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	self = (KDEConnectIndicatorSendDialog*) base;
#line 33 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp0_ = kde_connect_indicator_files;
#line 33 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp1_ = g_slist_length (_tmp0_);
#line 33 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	if (_tmp1_ == ((guint) 0)) {
#line 182 "KDEConnectSend.c"
		GtkMessageDialog* msg = NULL;
		GtkMessageDialog* _tmp2_ = NULL;
		GtkMessageDialog* _tmp3_ = NULL;
		const gchar* _tmp4_ = NULL;
		GtkMessageDialog* _tmp5_ = NULL;
		GtkMessageDialog* _tmp6_ = NULL;
#line 34 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		g_message ("KDEConnectSend.vala:34: file(s) doesnt exist(s) or not found");
#line 36 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		_tmp2_ = (GtkMessageDialog*) gtk_message_dialog_new (NULL, GTK_DIALOG_MODAL, GTK_MESSAGE_WARNING, GTK_BUTTONS_OK, "msg");
#line 36 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		g_object_ref_sink (_tmp2_);
#line 36 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		msg = _tmp2_;
#line 42 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		_tmp3_ = msg;
#line 42 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		_tmp4_ = _ ("File(s) not found");
#line 42 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		gtk_message_dialog_set_markup (_tmp3_, _tmp4_);
#line 44 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		_tmp5_ = msg;
#line 44 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		g_signal_connect ((GtkWidget*) _tmp5_, "destroy", (GCallback) _gtk_main_quit_gtk_widget_destroy, NULL);
#line 45 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		_tmp6_ = msg;
#line 45 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		gtk_dialog_run ((GtkDialog*) _tmp6_);
#line 33 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		_g_object_unref0 (msg);
#line 213 "KDEConnectSend.c"
	} else {
#line 48 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		kde_connect_indicator_send_dialog_create_window (self);
#line 49 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		kde_connect_indicator_send_dialog_create_signals (self);
#line 50 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		kde_connect_indicator_send_dialog_reload_device_list (self);
#line 221 "KDEConnectSend.c"
	}
}


static void _g_object_unref0_ (gpointer var) {
#line 55 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	(var == NULL) ? NULL : (var = (g_object_unref (var), NULL));
#line 229 "KDEConnectSend.c"
}


static void _g_slist_free__g_object_unref0_ (GSList* self) {
#line 55 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	g_slist_foreach (self, (GFunc) _g_object_unref0_, NULL);
#line 55 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	g_slist_free (self);
#line 238 "KDEConnectSend.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 57 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	return self ? g_object_ref (self) : NULL;
#line 245 "KDEConnectSend.c"
}


static void kde_connect_indicator_send_dialog_real_open (GApplication* base, GFile** _files, int _files_length1, const gchar* hint) {
	KDEConnectIndicatorSendDialog * self;
	GFile** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	GSList* _tmp16_ = NULL;
	guint _tmp17_ = 0U;
#line 54 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	self = (KDEConnectIndicatorSendDialog*) base;
#line 54 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	g_return_if_fail (hint != NULL);
#line 55 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	__g_slist_free__g_object_unref0_0 (kde_connect_indicator_files);
#line 55 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	kde_connect_indicator_files = NULL;
#line 57 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp0_ = _files;
#line 57 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp0__length1 = _files_length1;
#line 267 "KDEConnectSend.c"
	{
		GFile** file_collection = NULL;
		gint file_collection_length1 = 0;
		gint _file_collection_size_ = 0;
		gint file_it = 0;
#line 57 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		file_collection = _tmp0_;
#line 57 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		file_collection_length1 = _tmp0__length1;
#line 57 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		for (file_it = 0; file_it < _tmp0__length1; file_it = file_it + 1) {
#line 279 "KDEConnectSend.c"
			GFile* _tmp1_ = NULL;
			GFile* file = NULL;
#line 57 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
			_tmp1_ = _g_object_ref0 (file_collection[file_it]);
#line 57 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
			file = _tmp1_;
#line 286 "KDEConnectSend.c"
			{
				GFile* _tmp2_ = NULL;
				gchar* _tmp3_ = NULL;
				gchar* _tmp4_ = NULL;
				gchar* _tmp5_ = NULL;
				gchar* _tmp6_ = NULL;
				gboolean _tmp7_ = FALSE;
				GFile* _tmp8_ = NULL;
				gchar* _tmp9_ = NULL;
				gchar* _tmp10_ = NULL;
				gboolean _tmp11_ = FALSE;
#line 58 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
				_tmp2_ = file;
#line 58 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
				_tmp3_ = g_file_get_uri (_tmp2_);
#line 58 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
				_tmp4_ = _tmp3_;
#line 58 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
				_tmp5_ = g_strdup_printf ("%s", _tmp4_);
#line 58 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
				_tmp6_ = _tmp5_;
#line 58 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
				g_message ("KDEConnectSend.vala:58: %s", _tmp6_);
#line 58 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
				_g_free0 (_tmp6_);
#line 58 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
				_g_free0 (_tmp4_);
#line 59 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
				_tmp8_ = file;
#line 59 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
				_tmp9_ = g_file_get_path (_tmp8_);
#line 59 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
				_tmp10_ = _tmp9_;
#line 59 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
				_tmp11_ = _tmp10_ != NULL;
#line 59 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
				_g_free0 (_tmp10_);
#line 59 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
				if (_tmp11_) {
#line 326 "KDEConnectSend.c"
					GFile* _tmp12_ = NULL;
					gboolean _tmp13_ = FALSE;
#line 60 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
					_tmp12_ = file;
#line 60 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
					_tmp13_ = g_file_query_exists (_tmp12_, NULL);
#line 60 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
					_tmp7_ = _tmp13_;
#line 335 "KDEConnectSend.c"
				} else {
#line 59 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
					_tmp7_ = FALSE;
#line 339 "KDEConnectSend.c"
				}
#line 59 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
				if (_tmp7_) {
#line 343 "KDEConnectSend.c"
					GFile* _tmp14_ = NULL;
					GFile* _tmp15_ = NULL;
#line 61 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
					_tmp14_ = file;
#line 61 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
					_tmp15_ = _g_object_ref0 (_tmp14_);
#line 61 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
					kde_connect_indicator_files = g_slist_append (kde_connect_indicator_files, _tmp15_);
#line 352 "KDEConnectSend.c"
				}
#line 57 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
				_g_object_unref0 (file);
#line 356 "KDEConnectSend.c"
			}
		}
	}
#line 64 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp16_ = kde_connect_indicator_files;
#line 64 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp17_ = g_slist_length (_tmp16_);
#line 64 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	if (_tmp17_ > ((guint) 0)) {
#line 65 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		g_application_activate ((GApplication*) self);
#line 368 "KDEConnectSend.c"
	}
}


static void kde_connect_indicator_send_dialog_create_window (KDEConnectIndicatorSendDialog* self) {
	GtkApplicationWindow* _tmp0_ = NULL;
	GtkApplicationWindow* _tmp1_ = NULL;
	GtkApplicationWindow* _tmp2_ = NULL;
	GtkApplicationWindow* _tmp3_ = NULL;
	GtkHeaderBar* _tmp4_ = NULL;
	GtkHeaderBar* _tmp5_ = NULL;
	GtkHeaderBar* _tmp6_ = NULL;
	const gchar* _tmp7_ = NULL;
	const gchar* _tmp8_ = NULL;
	GtkButton* _tmp9_ = NULL;
	GtkHeaderBar* _tmp10_ = NULL;
	GtkButton* _tmp11_ = NULL;
	const gchar* _tmp12_ = NULL;
	GtkButton* _tmp13_ = NULL;
	GtkButton* _tmp14_ = NULL;
	GtkStyleContext* _tmp15_ = NULL;
	GtkStyleContext* _tmp16_ = NULL;
	GtkStyleContext* _tmp17_ = NULL;
	GtkButton* _tmp18_ = NULL;
	GtkHeaderBar* _tmp19_ = NULL;
	GtkButton* _tmp20_ = NULL;
	GtkButton* _tmp21_ = NULL;
	GtkHeaderBar* _tmp22_ = NULL;
	GtkButton* _tmp23_ = NULL;
	GtkBox* content = NULL;
	GtkBox* _tmp24_ = NULL;
	const gchar* _tmp25_ = NULL;
	GSList* _tmp26_ = NULL;
	guint _tmp27_ = 0U;
	gchar* _tmp28_ = NULL;
	gchar* _tmp29_ = NULL;
	GtkLabel* _tmp30_ = NULL;
	GtkLabel* _tmp31_ = NULL;
	GtkTreeView* _tmp32_ = NULL;
	GtkTreeView* _tmp33_ = NULL;
	GtkTreeSelection* _tmp34_ = NULL;
	GtkTreeSelection* _tmp35_ = NULL;
	GtkTreeSelection* _tmp36_ = NULL;
	GtkTreeView* _tmp37_ = NULL;
	GtkCellRendererText* cell = NULL;
	GtkCellRendererText* _tmp38_ = NULL;
	GtkTreeView* _tmp39_ = NULL;
	GtkTreeView* _tmp40_ = NULL;
	GtkApplicationWindow* _tmp41_ = NULL;
	GtkHeaderBar* _tmp42_ = NULL;
	GtkApplicationWindow* _tmp43_ = NULL;
	GtkApplicationWindow* _tmp44_ = NULL;
#line 68 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	g_return_if_fail (self != NULL);
#line 69 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp0_ = (GtkApplicationWindow*) gtk_application_window_new ((GtkApplication*) self);
#line 69 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	g_object_ref_sink (_tmp0_);
#line 69 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_g_object_unref0 (self->priv->window);
#line 69 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	self->priv->window = _tmp0_;
#line 70 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp1_ = self->priv->window;
#line 70 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	gtk_window_set_icon_name ((GtkWindow*) _tmp1_, "kdeconnect");
#line 71 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp2_ = self->priv->window;
#line 71 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	gtk_window_set_default_size ((GtkWindow*) _tmp2_, 500, 350);
#line 72 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp3_ = self->priv->window;
#line 72 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	gtk_container_set_border_width ((GtkContainer*) _tmp3_, (guint) 10);
#line 74 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp4_ = (GtkHeaderBar*) gtk_header_bar_new ();
#line 74 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	g_object_ref_sink (_tmp4_);
#line 74 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_g_object_unref0 (self->priv->headerBar);
#line 74 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	self->priv->headerBar = _tmp4_;
#line 75 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp5_ = self->priv->headerBar;
#line 75 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	gtk_header_bar_set_title (_tmp5_, "KDEConnect-Send");
#line 76 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp6_ = self->priv->headerBar;
#line 76 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp7_ = _ ("Send To");
#line 76 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	gtk_header_bar_set_subtitle (_tmp6_, _tmp7_);
#line 78 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp8_ = _ ("Cancel");
#line 78 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp9_ = (GtkButton*) gtk_button_new_with_label (_tmp8_);
#line 78 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	g_object_ref_sink (_tmp9_);
#line 78 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_g_object_unref0 (self->priv->cancel_button);
#line 78 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	self->priv->cancel_button = _tmp9_;
#line 79 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp10_ = self->priv->headerBar;
#line 79 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp11_ = self->priv->cancel_button;
#line 79 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	gtk_header_bar_pack_start (_tmp10_, (GtkWidget*) _tmp11_);
#line 81 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp12_ = _ ("Send");
#line 81 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp13_ = (GtkButton*) gtk_button_new_with_label (_tmp12_);
#line 81 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	g_object_ref_sink (_tmp13_);
#line 81 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_g_object_unref0 (self->priv->send_button);
#line 81 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	self->priv->send_button = _tmp13_;
#line 82 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp14_ = self->priv->send_button;
#line 82 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp15_ = gtk_widget_get_style_context ((GtkWidget*) _tmp14_);
#line 82 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp16_ = _g_object_ref0 (_tmp15_);
#line 82 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_g_object_unref0 (self->priv->style_context);
#line 82 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	self->priv->style_context = _tmp16_;
#line 83 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp17_ = self->priv->style_context;
#line 83 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	gtk_style_context_add_class (_tmp17_, "suggested-action");
#line 84 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp18_ = self->priv->send_button;
#line 84 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	gtk_widget_set_sensitive ((GtkWidget*) _tmp18_, FALSE);
#line 85 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp19_ = self->priv->headerBar;
#line 85 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp20_ = self->priv->send_button;
#line 85 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	gtk_header_bar_pack_end (_tmp19_, (GtkWidget*) _tmp20_);
#line 87 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp21_ = (GtkButton*) gtk_button_new_from_icon_name ("reload", GTK_ICON_SIZE_LARGE_TOOLBAR);
#line 87 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	g_object_ref_sink (_tmp21_);
#line 87 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_g_object_unref0 (self->priv->reload_button);
#line 87 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	self->priv->reload_button = _tmp21_;
#line 89 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp22_ = self->priv->headerBar;
#line 89 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp23_ = self->priv->reload_button;
#line 89 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	gtk_header_bar_pack_end (_tmp22_, (GtkWidget*) _tmp23_);
#line 91 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp24_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_VERTICAL, 0);
#line 91 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	g_object_ref_sink (_tmp24_);
#line 91 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	content = _tmp24_;
#line 93 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp25_ = _ ("There's %u file(s) to be send");
#line 93 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp26_ = kde_connect_indicator_files;
#line 93 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp27_ = g_slist_length (_tmp26_);
#line 93 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp28_ = g_strdup_printf (_tmp25_, _tmp27_);
#line 93 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp29_ = _tmp28_;
#line 93 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp30_ = (GtkLabel*) gtk_label_new (_tmp29_);
#line 93 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	g_object_ref_sink (_tmp30_);
#line 93 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp31_ = _tmp30_;
#line 93 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	gtk_box_pack_start (content, (GtkWidget*) _tmp31_, FALSE, TRUE, (guint) 10);
#line 93 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_g_object_unref0 (_tmp31_);
#line 93 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_g_free0 (_tmp29_);
#line 97 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp32_ = (GtkTreeView*) gtk_tree_view_new ();
#line 97 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	g_object_ref_sink (_tmp32_);
#line 97 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_g_object_unref0 (self->priv->tv);
#line 97 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	self->priv->tv = _tmp32_;
#line 98 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp33_ = self->priv->tv;
#line 98 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp34_ = gtk_tree_view_get_selection (_tmp33_);
#line 98 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp35_ = _g_object_ref0 (_tmp34_);
#line 98 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_g_object_unref0 (self->priv->ts);
#line 98 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	self->priv->ts = _tmp35_;
#line 99 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp36_ = self->priv->ts;
#line 99 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	gtk_tree_selection_set_mode (_tmp36_, GTK_SELECTION_MULTIPLE);
#line 100 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp37_ = self->priv->tv;
#line 100 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	gtk_tree_view_set_headers_visible (_tmp37_, FALSE);
#line 101 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp38_ = (GtkCellRendererText*) gtk_cell_renderer_text_new ();
#line 101 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	g_object_ref_sink (_tmp38_);
#line 101 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	cell = _tmp38_;
#line 102 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp39_ = self->priv->tv;
#line 102 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	gtk_tree_view_insert_column_with_attributes (_tmp39_, -1, "Device", (GtkCellRenderer*) cell, "text", 0, NULL);
#line 103 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp40_ = self->priv->tv;
#line 103 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	gtk_box_pack_start (content, (GtkWidget*) _tmp40_, TRUE, TRUE, (guint) 0);
#line 105 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp41_ = self->priv->window;
#line 105 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp42_ = self->priv->headerBar;
#line 105 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	gtk_window_set_titlebar ((GtkWindow*) _tmp41_, (GtkWidget*) _tmp42_);
#line 106 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp43_ = self->priv->window;
#line 106 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	gtk_container_add ((GtkContainer*) _tmp43_, (GtkWidget*) content);
#line 108 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp44_ = self->priv->window;
#line 108 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	gtk_widget_show_all ((GtkWidget*) _tmp44_);
#line 68 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_g_object_unref0 (cell);
#line 68 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_g_object_unref0 (content);
#line 611 "KDEConnectSend.c"
}


static void __lambda5_ (KDEConnectIndicatorSendDialog* self) {
	GtkButton* _tmp0_ = NULL;
	GSList* _tmp1_ = NULL;
	GSList* _tmp2_ = NULL;
	guint _tmp3_ = 0U;
#line 113 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp0_ = self->priv->send_button;
#line 113 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp1_ = kde_connect_indicator_send_dialog_get_selected (self);
#line 113 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp2_ = _tmp1_;
#line 113 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp3_ = g_slist_length (_tmp2_);
#line 113 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	gtk_widget_set_sensitive ((GtkWidget*) _tmp0_, _tmp3_ > ((guint) 0));
#line 113 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_g_slist_free0 (_tmp2_);
#line 632 "KDEConnectSend.c"
}


static void ___lambda5__gtk_tree_view_cursor_changed (GtkTreeView* _sender, gpointer self) {
#line 112 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	__lambda5_ ((KDEConnectIndicatorSendDialog*) self);
#line 639 "KDEConnectSend.c"
}


static void __lambda6_ (KDEConnectIndicatorSendDialog* self, GtkTreePath* path, GtkTreeViewColumn* column) {
	GtkTreeView* _tmp0_ = NULL;
	GtkTreePath* _tmp1_ = NULL;
#line 117 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	g_return_if_fail (path != NULL);
#line 117 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	g_return_if_fail (column != NULL);
#line 118 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp0_ = self->priv->tv;
#line 118 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp1_ = path;
#line 118 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	gtk_tree_view_set_cursor (_tmp0_, _tmp1_, NULL, FALSE);
#line 119 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	kde_connect_indicator_send_dialog_send_items (self);
#line 658 "KDEConnectSend.c"
}


static void ___lambda6__gtk_tree_view_row_activated (GtkTreeView* _sender, GtkTreePath* path, GtkTreeViewColumn* column, gpointer self) {
#line 117 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	__lambda6_ ((KDEConnectIndicatorSendDialog*) self, path, column);
#line 665 "KDEConnectSend.c"
}


static void __lambda7_ (KDEConnectIndicatorSendDialog* self) {
	GtkApplicationWindow* _tmp0_ = NULL;
#line 124 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp0_ = self->priv->window;
#line 124 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	gtk_window_close ((GtkWindow*) _tmp0_);
#line 675 "KDEConnectSend.c"
}


static void ___lambda7__gtk_button_clicked (GtkButton* _sender, gpointer self) {
#line 123 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	__lambda7_ ((KDEConnectIndicatorSendDialog*) self);
#line 682 "KDEConnectSend.c"
}


static void __lambda8_ (KDEConnectIndicatorSendDialog* self) {
#line 128 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	kde_connect_indicator_send_dialog_send_items (self);
#line 689 "KDEConnectSend.c"
}


static void ___lambda8__gtk_button_clicked (GtkButton* _sender, gpointer self) {
#line 127 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	__lambda8_ ((KDEConnectIndicatorSendDialog*) self);
#line 696 "KDEConnectSend.c"
}


static void __lambda9_ (KDEConnectIndicatorSendDialog* self) {
#line 132 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	kde_connect_indicator_send_dialog_reload_device_list (self);
#line 703 "KDEConnectSend.c"
}


static void ___lambda9__gtk_button_clicked (GtkButton* _sender, gpointer self) {
#line 131 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	__lambda9_ ((KDEConnectIndicatorSendDialog*) self);
#line 710 "KDEConnectSend.c"
}


static void kde_connect_indicator_send_dialog_create_signals (KDEConnectIndicatorSendDialog* self) {
	GtkTreeView* _tmp0_ = NULL;
	GtkTreeView* _tmp1_ = NULL;
	GtkButton* _tmp2_ = NULL;
	GtkButton* _tmp3_ = NULL;
	GtkButton* _tmp4_ = NULL;
#line 111 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	g_return_if_fail (self != NULL);
#line 112 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp0_ = self->priv->tv;
#line 112 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	g_signal_connect_object (_tmp0_, "cursor-changed", (GCallback) ___lambda5__gtk_tree_view_cursor_changed, self, 0);
#line 117 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp1_ = self->priv->tv;
#line 117 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	g_signal_connect_object (_tmp1_, "row-activated", (GCallback) ___lambda6__gtk_tree_view_row_activated, self, 0);
#line 123 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp2_ = self->priv->cancel_button;
#line 123 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	g_signal_connect_object (_tmp2_, "clicked", (GCallback) ___lambda7__gtk_button_clicked, self, 0);
#line 127 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp3_ = self->priv->send_button;
#line 127 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	g_signal_connect_object (_tmp3_, "clicked", (GCallback) ___lambda8__gtk_button_clicked, self, 0);
#line 131 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp4_ = self->priv->reload_button;
#line 131 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	g_signal_connect_object (_tmp4_, "clicked", (GCallback) ___lambda9__gtk_button_clicked, self, 0);
#line 742 "KDEConnectSend.c"
}


static gpointer _gtk_tree_path_copy0 (gpointer self) {
#line 146 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	return self ? gtk_tree_path_copy (self) : NULL;
#line 749 "KDEConnectSend.c"
}


static void _gtk_tree_path_free0_ (gpointer var) {
#line 152 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	(var == NULL) ? NULL : (var = (gtk_tree_path_free (var), NULL));
#line 756 "KDEConnectSend.c"
}


static void _g_list_free__gtk_tree_path_free0_ (GList* self) {
#line 152 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	g_list_foreach (self, (GFunc) _gtk_tree_path_free0_, NULL);
#line 152 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	g_list_free (self);
#line 765 "KDEConnectSend.c"
}


static GSList* kde_connect_indicator_send_dialog_get_selected (KDEConnectIndicatorSendDialog* self) {
	GSList* result = NULL;
	GSList* selected_devices = NULL;
	GtkTreeModel* tm = NULL;
	GList* selected_paths = NULL;
	GtkTreeSelection* _tmp0_ = NULL;
	GtkTreeModel* _tmp1_ = NULL;
	GList* _tmp2_ = NULL;
	GtkTreeModel* _tmp3_ = NULL;
	GList* _tmp4_ = NULL;
	GSList* _tmp11_ = NULL;
	GSList* _tmp12_ = NULL;
#line 137 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 139 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	selected_devices = NULL;
#line 143 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp0_ = self->priv->ts;
#line 143 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp2_ = gtk_tree_selection_get_selected_rows (_tmp0_, &_tmp1_);
#line 143 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_g_object_unref0 (tm);
#line 143 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp3_ = _g_object_ref0 (_tmp1_);
#line 143 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	tm = _tmp3_;
#line 143 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	selected_paths = _tmp2_;
#line 146 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp4_ = selected_paths;
#line 799 "KDEConnectSend.c"
	{
		GList* path_collection = NULL;
		GList* path_it = NULL;
#line 146 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		path_collection = _tmp4_;
#line 146 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		for (path_it = path_collection; path_it != NULL; path_it = path_it->next) {
#line 807 "KDEConnectSend.c"
			GtkTreePath* _tmp5_ = NULL;
			GtkTreePath* path = NULL;
#line 146 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
			_tmp5_ = _gtk_tree_path_copy0 ((GtkTreePath*) path_it->data);
#line 146 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
			path = _tmp5_;
#line 814 "KDEConnectSend.c"
			{
				GtkTreePath* _tmp6_ = NULL;
#line 147 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
				_tmp6_ = path;
#line 147 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
				if (_tmp6_ != NULL) {
#line 821 "KDEConnectSend.c"
					GtkTreePath* _tmp7_ = NULL;
					gchar* _tmp8_ = NULL;
					gchar* _tmp9_ = NULL;
					gint _tmp10_ = 0;
#line 148 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
					_tmp7_ = path;
#line 148 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
					_tmp8_ = gtk_tree_path_to_string (_tmp7_);
#line 148 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
					_tmp9_ = _tmp8_;
#line 148 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
					_tmp10_ = atoi (_tmp9_);
#line 148 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
					selected_devices = g_slist_append (selected_devices, (gpointer) ((gintptr) _tmp10_));
#line 148 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
					_g_free0 (_tmp9_);
#line 838 "KDEConnectSend.c"
				}
#line 146 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
				_gtk_tree_path_free0 (path);
#line 842 "KDEConnectSend.c"
			}
		}
	}
#line 152 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp11_ = selected_devices;
#line 152 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp12_ = g_slist_copy (_tmp11_);
#line 152 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	result = _tmp12_;
#line 152 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	__g_list_free__gtk_tree_path_free0_0 (selected_paths);
#line 152 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_g_object_unref0 (tm);
#line 152 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_g_slist_free0 (selected_devices);
#line 152 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	return result;
#line 860 "KDEConnectSend.c"
}


static void kde_connect_indicator_send_dialog_set_device_list (KDEConnectIndicatorSendDialog* self, GtkListStore* device_list) {
	GtkTreeView* _tmp0_ = NULL;
	GtkListStore* _tmp1_ = NULL;
	GtkTreePath* path = NULL;
	GtkTreePath* _tmp2_ = NULL;
	GtkTreeView* _tmp3_ = NULL;
#line 155 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	g_return_if_fail (self != NULL);
#line 155 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	g_return_if_fail (device_list != NULL);
#line 156 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp0_ = self->priv->tv;
#line 156 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp1_ = device_list;
#line 156 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	gtk_tree_view_set_model (_tmp0_, (GtkTreeModel*) _tmp1_);
#line 159 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp2_ = gtk_tree_path_new_from_indices (0, -1, -1);
#line 159 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	path = _tmp2_;
#line 160 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp3_ = self->priv->tv;
#line 160 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	gtk_tree_view_set_cursor (_tmp3_, path, NULL, FALSE);
#line 155 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_gtk_tree_path_free0 (path);
#line 890 "KDEConnectSend.c"
}


static gpointer _kde_connect_indicator_device_ref0 (gpointer self) {
#line 199 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	return self ? kde_connect_indicator_device_ref (self) : NULL;
#line 897 "KDEConnectSend.c"
}


static void kde_connect_indicator_send_dialog_reload_device_list (KDEConnectIndicatorSendDialog* self) {
	gchar** id_list = NULL;
	gchar** _tmp6_ = NULL;
	gint id_list_length1 = 0;
	gint _id_list_size_ = 0;
	GtkListStore* _tmp18_ = NULL;
	gchar** _tmp19_ = NULL;
	gint _tmp19__length1 = 0;
	GtkListStore* _tmp45_ = NULL;
	GError * _inner_error_ = NULL;
#line 163 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	g_return_if_fail (self != NULL);
#line 913 "KDEConnectSend.c"
	{
		GDBusConnection* _tmp0_ = NULL;
		GDBusConnection* _tmp1_ = NULL;
		GDBusConnection* _tmp2_ = NULL;
#line 165 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		_tmp1_ = g_bus_get_sync (G_BUS_TYPE_SESSION, NULL, &_inner_error_);
#line 165 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		_tmp0_ = _tmp1_;
#line 165 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 924 "KDEConnectSend.c"
			goto __catch0_g_error;
		}
#line 165 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		_tmp2_ = _tmp0_;
#line 165 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		_tmp0_ = NULL;
#line 165 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		_g_object_unref0 (self->priv->conn);
#line 165 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		self->priv->conn = _tmp2_;
#line 164 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		_g_object_unref0 (_tmp0_);
#line 937 "KDEConnectSend.c"
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		GError* _tmp3_ = NULL;
		const gchar* _tmp4_ = NULL;
		GtkApplicationWindow* _tmp5_ = NULL;
#line 164 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		e = _inner_error_;
#line 164 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		_inner_error_ = NULL;
#line 168 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		_tmp3_ = e;
#line 168 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		_tmp4_ = _tmp3_->message;
#line 168 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		g_message ("KDEConnectSend.vala:168: %s", _tmp4_);
#line 169 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		_tmp5_ = self->priv->window;
#line 169 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		gtk_window_close ((GtkWindow*) _tmp5_);
#line 164 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		_g_error_free0 (e);
#line 962 "KDEConnectSend.c"
	}
	__finally0:
#line 164 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 164 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 164 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		g_clear_error (&_inner_error_);
#line 164 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		return;
#line 973 "KDEConnectSend.c"
	}
#line 172 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp6_ = g_new0 (gchar*, 0 + 1);
#line 172 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	id_list = _tmp6_;
#line 172 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	id_list_length1 = 0;
#line 172 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_id_list_size_ = id_list_length1;
#line 983 "KDEConnectSend.c"
	{
		GVariant* return_variant = NULL;
		GDBusConnection* _tmp7_ = NULL;
		GVariant* _tmp8_ = NULL;
		GVariant* _tmp9_ = NULL;
		GVariant* _tmp10_ = NULL;
		GVariant* _tmp11_ = NULL;
		GVariant* i = NULL;
		GVariant* _tmp12_ = NULL;
		GVariant* _tmp13_ = NULL;
		size_t _tmp14_;
		gchar** _tmp15_ = NULL;
#line 174 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		_tmp7_ = self->priv->conn;
#line 174 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		_tmp8_ = g_variant_new ("(b)", TRUE, NULL);
#line 174 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		g_variant_ref_sink (_tmp8_);
#line 174 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		_tmp9_ = _tmp8_;
#line 174 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		_tmp10_ = g_dbus_connection_call_sync (_tmp7_, "org.kde.kdeconnect", "/modules/kdeconnect", "org.kde.kdeconnect.daemon", "devices", _tmp9_, NULL, G_DBUS_CALL_FLAGS_NONE, -1, NULL, &_inner_error_);
#line 174 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		_tmp11_ = _tmp10_;
#line 174 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		_g_variant_unref0 (_tmp9_);
#line 174 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		return_variant = _tmp11_;
#line 174 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 1014 "KDEConnectSend.c"
			goto __catch1_g_error;
		}
#line 186 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		_tmp12_ = g_variant_get_child_value (return_variant, (gsize) 0);
#line 186 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		i = _tmp12_;
#line 187 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		_tmp13_ = i;
#line 187 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		_tmp15_ = g_variant_dup_strv (_tmp13_, &_tmp14_);
#line 187 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		id_list = (_vala_array_free (id_list, id_list_length1, (GDestroyNotify) g_free), NULL);
#line 187 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		id_list = _tmp15_;
#line 187 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		id_list_length1 = _tmp14_;
#line 187 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		_id_list_size_ = id_list_length1;
#line 173 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		_g_variant_unref0 (i);
#line 173 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		_g_variant_unref0 (return_variant);
#line 1037 "KDEConnectSend.c"
	}
	goto __finally1;
	__catch1_g_error:
	{
		GError* e = NULL;
		GError* _tmp16_ = NULL;
		const gchar* _tmp17_ = NULL;
#line 173 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		e = _inner_error_;
#line 173 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		_inner_error_ = NULL;
#line 190 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		_tmp16_ = e;
#line 190 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		_tmp17_ = _tmp16_->message;
#line 190 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		g_message ("KDEConnectSend.vala:190: %s", _tmp17_);
#line 173 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		_g_error_free0 (e);
#line 1057 "KDEConnectSend.c"
	}
	__finally1:
#line 173 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 173 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		id_list = (_vala_array_free (id_list, id_list_length1, (GDestroyNotify) g_free), NULL);
#line 173 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 173 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		g_clear_error (&_inner_error_);
#line 173 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		return;
#line 1070 "KDEConnectSend.c"
	}
#line 193 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp18_ = gtk_list_store_new (1, G_TYPE_STRING, -1);
#line 193 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_g_object_unref0 (self->priv->list_store);
#line 193 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	self->priv->list_store = _tmp18_;
#line 194 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	__g_slist_free__kde_connect_indicator_device_unref0_0 (self->priv->device_list);
#line 194 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	self->priv->device_list = NULL;
#line 196 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp19_ = id_list;
#line 196 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp19__length1 = id_list_length1;
#line 1086 "KDEConnectSend.c"
	{
		gchar** id_collection = NULL;
		gint id_collection_length1 = 0;
		gint _id_collection_size_ = 0;
		gint id_it = 0;
#line 196 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		id_collection = _tmp19_;
#line 196 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		id_collection_length1 = _tmp19__length1;
#line 196 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		for (id_it = 0; id_it < _tmp19__length1; id_it = id_it + 1) {
#line 1098 "KDEConnectSend.c"
			gchar* _tmp20_ = NULL;
			gchar* id = NULL;
#line 196 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
			_tmp20_ = g_strdup (id_collection[id_it]);
#line 196 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
			id = _tmp20_;
#line 1105 "KDEConnectSend.c"
			{
				KDEConnectIndicatorDevice* d = NULL;
				const gchar* _tmp21_ = NULL;
				gchar* _tmp22_ = NULL;
				gchar* _tmp23_ = NULL;
				KDEConnectIndicatorDevice* _tmp24_ = NULL;
				KDEConnectIndicatorDevice* _tmp25_ = NULL;
				gboolean _tmp26_ = FALSE;
				KDEConnectIndicatorDevice* _tmp27_ = NULL;
				gboolean _tmp28_ = FALSE;
				gboolean _tmp29_ = FALSE;
#line 197 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
				_tmp21_ = id;
#line 197 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
				_tmp22_ = g_strconcat ("/modules/kdeconnect/devices/", _tmp21_, NULL);
#line 197 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
				_tmp23_ = _tmp22_;
#line 197 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
				_tmp24_ = kde_connect_indicator_device_new (_tmp23_);
#line 197 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
				_tmp25_ = _tmp24_;
#line 197 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
				_g_free0 (_tmp23_);
#line 197 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
				d = _tmp25_;
#line 198 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
				_tmp27_ = d;
#line 198 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
				_tmp28_ = kde_connect_indicator_device_get_is_reachable (_tmp27_);
#line 198 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
				_tmp29_ = _tmp28_;
#line 198 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
				if (_tmp29_) {
#line 1139 "KDEConnectSend.c"
					KDEConnectIndicatorDevice* _tmp30_ = NULL;
					gboolean _tmp31_ = FALSE;
					gboolean _tmp32_ = FALSE;
#line 198 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
					_tmp30_ = d;
#line 198 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
					_tmp31_ = kde_connect_indicator_device_get_is_trusted (_tmp30_);
#line 198 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
					_tmp32_ = _tmp31_;
#line 198 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
					_tmp26_ = _tmp32_;
#line 1151 "KDEConnectSend.c"
				} else {
#line 198 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
					_tmp26_ = FALSE;
#line 1155 "KDEConnectSend.c"
				}
#line 198 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
				if (_tmp26_) {
#line 1159 "KDEConnectSend.c"
					KDEConnectIndicatorDevice* _tmp33_ = NULL;
					KDEConnectIndicatorDevice* _tmp34_ = NULL;
					GtkTreeIter iter = {0};
					GtkListStore* _tmp35_ = NULL;
					GtkTreeIter _tmp36_ = {0};
					KDEConnectIndicatorDevice* _tmp37_ = NULL;
					const gchar* _tmp38_ = NULL;
					const gchar* _tmp39_ = NULL;
					GtkListStore* _tmp40_ = NULL;
					GtkTreeIter _tmp41_ = {0};
					KDEConnectIndicatorDevice* _tmp42_ = NULL;
					const gchar* _tmp43_ = NULL;
					const gchar* _tmp44_ = NULL;
#line 199 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
					_tmp33_ = d;
#line 199 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
					_tmp34_ = _kde_connect_indicator_device_ref0 (_tmp33_);
#line 199 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
					self->priv->device_list = g_slist_append (self->priv->device_list, _tmp34_);
#line 201 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
					_tmp35_ = self->priv->list_store;
#line 201 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
					gtk_list_store_append (_tmp35_, &_tmp36_);
#line 201 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
					iter = _tmp36_;
#line 202 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
					_tmp37_ = d;
#line 202 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
					_tmp38_ = kde_connect_indicator_device_get_name (_tmp37_);
#line 202 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
					_tmp39_ = _tmp38_;
#line 202 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
					g_message ("KDEConnectSend.vala:202: %s", _tmp39_);
#line 203 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
					_tmp40_ = self->priv->list_store;
#line 203 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
					_tmp41_ = iter;
#line 203 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
					_tmp42_ = d;
#line 203 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
					_tmp43_ = kde_connect_indicator_device_get_name (_tmp42_);
#line 203 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
					_tmp44_ = _tmp43_;
#line 203 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
					gtk_list_store_set (_tmp40_, &_tmp41_, 0, _tmp44_, -1);
#line 1205 "KDEConnectSend.c"
				}
#line 196 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
				_kde_connect_indicator_device_unref0 (d);
#line 196 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
				_g_free0 (id);
#line 1211 "KDEConnectSend.c"
			}
		}
	}
#line 207 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp45_ = self->priv->list_store;
#line 207 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	kde_connect_indicator_send_dialog_set_device_list (self, _tmp45_);
#line 163 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	id_list = (_vala_array_free (id_list, id_list_length1, (GDestroyNotify) g_free), NULL);
#line 1221 "KDEConnectSend.c"
}


static void kde_connect_indicator_send_dialog_send_items (KDEConnectIndicatorSendDialog* self) {
	GSList* selected_devs = NULL;
	GSList* _tmp0_ = NULL;
	GSList* _tmp1_ = NULL;
	GtkApplicationWindow* _tmp12_ = NULL;
#line 211 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	g_return_if_fail (self != NULL);
#line 212 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp0_ = kde_connect_indicator_send_dialog_get_selected (self);
#line 212 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	selected_devs = _tmp0_;
#line 214 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp1_ = kde_connect_indicator_files;
#line 1238 "KDEConnectSend.c"
	{
		GSList* file_collection = NULL;
		GSList* file_it = NULL;
#line 214 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		file_collection = _tmp1_;
#line 214 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
		for (file_it = file_collection; file_it != NULL; file_it = file_it->next) {
#line 1246 "KDEConnectSend.c"
			GFile* _tmp2_ = NULL;
			GFile* file = NULL;
#line 214 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
			_tmp2_ = _g_object_ref0 ((GFile*) file_it->data);
#line 214 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
			file = _tmp2_;
#line 1253 "KDEConnectSend.c"
			{
				GSList* _tmp3_ = NULL;
#line 215 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
				_tmp3_ = selected_devs;
#line 1258 "KDEConnectSend.c"
				{
					GSList* selected_collection = NULL;
					GSList* selected_it = NULL;
#line 215 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
					selected_collection = _tmp3_;
#line 215 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
					for (selected_it = selected_collection; selected_it != NULL; selected_it = selected_it->next) {
#line 1266 "KDEConnectSend.c"
						gint selected = 0;
#line 215 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
						selected = (gint) ((gintptr) selected_it->data);
#line 1270 "KDEConnectSend.c"
						{
							KDEConnectIndicatorDevice* selected_dev = NULL;
							GSList* _tmp4_ = NULL;
							gint _tmp5_ = 0;
							gconstpointer _tmp6_ = NULL;
							KDEConnectIndicatorDevice* _tmp7_ = NULL;
							KDEConnectIndicatorDevice* _tmp8_ = NULL;
							GFile* _tmp9_ = NULL;
							gchar* _tmp10_ = NULL;
							gchar* _tmp11_ = NULL;
#line 216 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
							_tmp4_ = self->priv->device_list;
#line 216 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
							_tmp5_ = selected;
#line 216 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
							_tmp6_ = g_slist_nth_data (_tmp4_, (guint) _tmp5_);
#line 216 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
							_tmp7_ = _kde_connect_indicator_device_ref0 ((KDEConnectIndicatorDevice*) _tmp6_);
#line 216 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
							selected_dev = _tmp7_;
#line 219 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
							_tmp8_ = selected_dev;
#line 219 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
							_tmp9_ = file;
#line 219 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
							_tmp10_ = g_file_get_uri (_tmp9_);
#line 219 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
							_tmp11_ = _tmp10_;
#line 219 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
							kde_connect_indicator_device_send_file (_tmp8_, _tmp11_);
#line 219 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
							_g_free0 (_tmp11_);
#line 215 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
							_kde_connect_indicator_device_unref0 (selected_dev);
#line 1305 "KDEConnectSend.c"
						}
					}
				}
#line 214 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
				_g_object_unref0 (file);
#line 1311 "KDEConnectSend.c"
			}
		}
	}
#line 223 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp12_ = self->priv->window;
#line 223 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	gtk_window_close ((GtkWindow*) _tmp12_);
#line 211 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_g_slist_free0 (selected_devs);
#line 1321 "KDEConnectSend.c"
}


static void kde_connect_indicator_send_dialog_class_init (KDEConnectIndicatorSendDialogClass * klass) {
#line 14 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	kde_connect_indicator_send_dialog_parent_class = g_type_class_peek_parent (klass);
#line 14 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	g_type_class_add_private (klass, sizeof (KDEConnectIndicatorSendDialogPrivate));
#line 14 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	((GApplicationClass *) klass)->activate = (void (*)(GApplication*)) kde_connect_indicator_send_dialog_real_activate;
#line 14 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	((GApplicationClass *) klass)->open = (void (*)(GApplication*, GFile**, int, const gchar*)) kde_connect_indicator_send_dialog_real_open;
#line 14 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	G_OBJECT_CLASS (klass)->finalize = kde_connect_indicator_send_dialog_finalize;
#line 1336 "KDEConnectSend.c"
}


static void kde_connect_indicator_send_dialog_instance_init (KDEConnectIndicatorSendDialog * self) {
#line 14 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	self->priv = KDE_CONNECT_INDICATOR_SEND_DIALOG_GET_PRIVATE (self);
#line 1343 "KDEConnectSend.c"
}


static void kde_connect_indicator_send_dialog_finalize (GObject* obj) {
	KDEConnectIndicatorSendDialog * self;
#line 14 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, KDE_CONNECT_INDICATOR_TYPE_SEND_DIALOG, KDEConnectIndicatorSendDialog);
#line 15 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_g_object_unref0 (self->priv->window);
#line 16 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_g_object_unref0 (self->priv->headerBar);
#line 17 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_g_object_unref0 (self->priv->cancel_button);
#line 18 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_g_object_unref0 (self->priv->send_button);
#line 19 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_g_object_unref0 (self->priv->reload_button);
#line 20 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_g_object_unref0 (self->priv->style_context);
#line 21 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_g_object_unref0 (self->priv->tv);
#line 22 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_g_object_unref0 (self->priv->list_store);
#line 23 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_g_object_unref0 (self->priv->conn);
#line 24 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_g_object_unref0 (self->priv->ts);
#line 25 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	__g_slist_free__kde_connect_indicator_device_unref0_0 (self->priv->device_list);
#line 14 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	G_OBJECT_CLASS (kde_connect_indicator_send_dialog_parent_class)->finalize (obj);
#line 1375 "KDEConnectSend.c"
}


GType kde_connect_indicator_send_dialog_get_type (void) {
	static volatile gsize kde_connect_indicator_send_dialog_type_id__volatile = 0;
	if (g_once_init_enter (&kde_connect_indicator_send_dialog_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (KDEConnectIndicatorSendDialogClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) kde_connect_indicator_send_dialog_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (KDEConnectIndicatorSendDialog), 0, (GInstanceInitFunc) kde_connect_indicator_send_dialog_instance_init, NULL };
		GType kde_connect_indicator_send_dialog_type_id;
		kde_connect_indicator_send_dialog_type_id = g_type_register_static (gtk_application_get_type (), "KDEConnectIndicatorSendDialog", &g_define_type_info, 0);
		g_once_init_leave (&kde_connect_indicator_send_dialog_type_id__volatile, kde_connect_indicator_send_dialog_type_id);
	}
	return kde_connect_indicator_send_dialog_type_id__volatile;
}


gint kde_connect_indicator_main (gchar** args, int args_length1) {
	gint result = 0;
	KDEConnectIndicatorSendDialog* _tmp0_ = NULL;
	KDEConnectIndicatorSendDialog* _tmp1_ = NULL;
	gchar** _tmp2_ = NULL;
	gint _tmp2__length1 = 0;
	gint _tmp3_ = 0;
	gint _tmp4_ = 0;
#line 228 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp0_ = kde_connect_indicator_send_dialog_new ();
#line 228 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp1_ = _tmp0_;
#line 228 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp2_ = args;
#line 228 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp2__length1 = args_length1;
#line 228 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp3_ = g_application_run ((GApplication*) _tmp1_, _tmp2__length1, _tmp2_);
#line 228 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_tmp4_ = _tmp3_;
#line 228 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	_g_object_unref0 (_tmp1_);
#line 228 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	result = _tmp4_;
#line 228 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	return result;
#line 1417 "KDEConnectSend.c"
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
#line 227 "/home/joaomanoel/Dropbox/Public/Projetos/indicator-kdeconnect/src/kdeconnectsend/KDEConnectSend.vala"
	return kde_connect_indicator_main (argv, argc);
#line 1427 "KDEConnectSend.c"
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



